// GENERATED by scripts/measureCodeSizes.ts -- do not edit by hand; re-run it instead.
// Measured with arm-none-eabi-gcc 15.3.1 (-Os): another compiler version gives other sizes.

/** What an otherwise empty unit of each kind loads (code + data + bss): a constant into the
 *  output for an oscillator, a pass-through for an effect. */
export const CODE_BASELINE_BYTES: Record<string, number> = {
  'minilogue-xd:osc': 536,
  'nts1mkii:osc': 4259,
  'nts1mkii:modfx': 4200,
  'nts1mkii:delfx': 4244,
  'nts1mkii:revfx': 4244,
  'minilogue-xd:modfx': 464,
  'minilogue-xd:delfx': 440,
  'minilogue-xd:revfx': 440
}

export interface CodeSize {
  first: number
  extra: number
  helpers: string[]
}

export type CodeSizeContext =
  'minilogue-xd:osc' | 'minilogue-xd:fx' | 'nts1mkii:osc' | 'nts1mkii:fx'

/**
 * Code bytes (text + rodata + data; tables the estimate counts as `sharedBytes` excluded) per
 * primitive and context, all inlets wired (`unwired`: none, where it has inlets): `first` for the first instance, `extra` for each
 * further one, and the out-of-line functions it brings (`helpers`, sized in
 * `CODE_HELPER_BYTES`), which a unit carries once however many primitives call them.
 */
export const CODE_SIZE_TABLE: Record<
  CodeSizeContext,
  Record<string, CodeSize & { unwired?: CodeSize; snapshotHash: string }>
> = {
  'minilogue-xd:osc': {
    'logue/osc/sine': {
      first: 568,
      extra: 260,
      helpers: [],
      unwired: { first: 304, extra: 176, helpers: [] },
      snapshotHash: 'b34b1284af3c9ca7'
    },
    'logue/osc/saw': {
      first: 728,
      extra: 296,
      helpers: [],
      unwired: { first: 396, extra: 192, helpers: [] },
      snapshotHash: '689d43e99e06ce9c'
    },
    'logue/osc/square': {
      first: 552,
      extra: 204,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 288, extra: 112, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '9a189b5fd7ef929c'
    },
    'logue/osc/pulse': {
      first: 612,
      extra: 260,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 308, extra: 128, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '773b9bbd527f1576'
    },
    'logue/osc/triangle': {
      first: 496,
      extra: 200,
      helpers: [],
      unwired: { first: 236, extra: 88, helpers: [] },
      snapshotHash: 'c19162f9574d3fe7'
    },
    'logue/osc/additive': {
      first: 420,
      extra: 140,
      helpers: ['Osc::additive_step(float, float, float)'],
      unwired: { first: 228, extra: 92, helpers: ['Osc::additive_step(float, float, float)'] },
      snapshotHash: '8ad6107dc41ce335'
    },
    'logue/osc/granular': {
      first: 1606,
      extra: 1476,
      helpers: ['Osc::note_w0(float)', 'memset'],
      unwired: { first: 1378, extra: 1268, helpers: ['Osc::note_w0(float)', 'memset'] },
      snapshotHash: '287537a0ffee7fe9'
    },
    'logue/osc/sample': {
      first: 732,
      extra: 652,
      helpers: ['Osc::note_w0(float)'],
      unwired: { first: 652, extra: 552, helpers: ['Osc::note_w0(float)'] },
      snapshotHash: '7cb41406b040b044'
    },
    'logue/osc/wavetable': {
      first: 1016,
      extra: 724,
      helpers: [],
      unwired: { first: 844, extra: 660, helpers: [] },
      snapshotHash: 'f92185a8a2498df5'
    },
    'logue/mix/mix2': {
      first: 28,
      extra: 24,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: 'bcf10c53a2411c0f'
    },
    'logue/math/multiply': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '422c16a247da8ec8'
    },
    'logue/mix/crossfader': {
      first: 276,
      extra: 216,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 184, extra: 148, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: 'ff48b03b50520cf3'
    },
    'logue/mix/stereo-mix2': {
      first: 28,
      extra: 24,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: '73842bd820468e9f'
    },
    'logue/mix/stereo-crossfader': {
      first: 264,
      extra: 204,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 172, extra: 136, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: '779c8ef1206c74bd'
    },
    'logue/filter/lowpass-cheap': {
      first: 68,
      extra: 72,
      helpers: [],
      unwired: { first: 68, extra: 56, helpers: [] },
      snapshotHash: '9498d8e54c739257'
    },
    'logue/filter/highpass-cheap': {
      first: 68,
      extra: 76,
      helpers: [],
      unwired: { first: 68, extra: 60, helpers: [] },
      snapshotHash: '5918f33ffc84533f'
    },
    'logue/gain/vca': {
      first: 4,
      extra: 4,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: '71e7c2874a2780a1'
    },
    'logue/env/ad': {
      first: 340,
      extra: 228,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 208, extra: 160, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: 'c384655566b26ffc'
    },
    'logue/env/ahd': {
      first: 316,
      extra: 220,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 180, extra: 132, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: 'e0f896dd954801b1'
    },
    'logue/env/adsr': {
      first: 328,
      extra: 208,
      helpers: ['Osc::adsr_rate(float, float)'],
      unwired: { first: 336, extra: 184, helpers: ['Osc::adsr_rate(float, float)'] },
      snapshotHash: 'abd7e5820bec87bc'
    },
    'logue/env/one-knob-adsr': {
      first: 468,
      extra: 296,
      helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)'],
      unwired: {
        first: 472,
        extra: 240,
        helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)']
      },
      snapshotHash: 'a39fd0de0ef1ae2a'
    },
    'logue/env/multistage': {
      first: 704,
      extra: 528,
      helpers: [],
      unwired: { first: 628, extra: 388, helpers: [] },
      snapshotHash: '13bbe27c71cd6bc6'
    },
    'logue/lfo/sine-lfo': {
      first: 300,
      extra: 200,
      helpers: [],
      unwired: { first: 200, extra: 120, helpers: [] },
      snapshotHash: 'f091daaf62b2b62e'
    },
    'logue/lfo/triangle-lfo': {
      first: 220,
      extra: 168,
      helpers: [],
      unwired: { first: 132, extra: 68, helpers: [] },
      snapshotHash: '63720761f9fb074b'
    },
    'logue/lfo/square-lfo': {
      first: 212,
      extra: 140,
      helpers: [],
      unwired: { first: 116, extra: 64, helpers: [] },
      snapshotHash: '5bf8d1d088df38b0'
    },
    'logue/lfo/ramp-up': {
      first: 200,
      extra: 128,
      helpers: [],
      unwired: { first: 104, extra: 56, helpers: [] },
      snapshotHash: '657d45b8a4249ea5'
    },
    'logue/lfo/ramp-down': {
      first: 200,
      extra: 128,
      helpers: [],
      unwired: { first: 104, extra: 56, helpers: [] },
      snapshotHash: '93415749054fe77d'
    },
    'logue/lfo/fast-square': {
      first: 468,
      extra: 312,
      helpers: [],
      unwired: { first: 320, extra: 160, helpers: [] },
      snapshotHash: '9023a42eadc26048'
    },
    'logue/lfo/random-steps': {
      first: 200,
      extra: 168,
      helpers: [],
      unwired: { first: 144, extra: 112, helpers: [] },
      snapshotHash: '001bad58241c33a2'
    },
    'logue/osc/noise': {
      first: 394,
      extra: 252,
      helpers: ['memset'],
      snapshotHash: 'c55e2984e99ac4a6'
    },
    'logue/osc/lfsr': {
      first: 625,
      extra: 404,
      helpers: [],
      unwired: { first: 577, extra: 336, helpers: [] },
      snapshotHash: '7fbe59bdb96624a8'
    },
    'logue/shape/wavefolder': {
      first: 116,
      extra: 104,
      helpers: [],
      unwired: { first: 24, extra: 4, helpers: [] },
      snapshotHash: '6597b9a61c6b5800'
    },
    'logue/shape/soft-clip': {
      first: 84,
      extra: 72,
      helpers: [],
      unwired: { first: 36, extra: 20, helpers: [] },
      snapshotHash: '94bd46054709e8a4'
    },
    'logue/shape/drive': {
      first: 464,
      extra: 356,
      helpers: ['Osc::exp_approx(float)'],
      unwired: { first: 308, extra: 200, helpers: ['Osc::exp_approx(float)'] },
      snapshotHash: '47bc5cda72f6b7e2'
    },
    'logue/filter/comb': {
      first: 874,
      extra: 496,
      helpers: ['memset'],
      unwired: { first: 778, extra: 324, helpers: ['memset'] },
      snapshotHash: '1fd2dcd5f18abf0e'
    },
    'logue/filter/string': {
      first: 782,
      extra: 616,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 610,
        extra: 444,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: 'd2fb4b7548c8393b'
    },
    'logue/osc/exciter': {
      first: 940,
      extra: 336,
      helpers: [],
      unwired: { first: 916, extra: 232, helpers: [] },
      snapshotHash: '718efdc3d5a3a5fc'
    },
    'logue/osc/sync': {
      first: 288,
      extra: 216,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 192,
        extra: 176,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: 'de6812a7e1beb6e4'
    },
    'logue/osc/phase-dist': {
      first: 1224,
      extra: 1232,
      helpers: [],
      unwired: { first: 1464, extra: 784, helpers: [] },
      snapshotHash: '447d0e2b472a3a55'
    },
    'logue/osc/bass-support': {
      first: 808,
      extra: 712,
      helpers: [
        'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Osc::note_w0(float)',
        'memset'
      ],
      unwired: {
        first: 812,
        extra: 584,
        helpers: [
          'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: '8c0581583e35f2f4'
    },
    'logue/filter/svf': {
      first: 664,
      extra: 496,
      helpers: [],
      unwired: { first: 608, extra: 392, helpers: [] },
      snapshotHash: '71e157475bbe46c8'
    },
    'logue/filter/ladder': {
      first: 1174,
      extra: 960,
      helpers: ['memset'],
      unwired: { first: 982, extra: 784, helpers: ['memset'] },
      snapshotHash: '14f53da66bd476e6'
    },
    'logue/filter/eq-band': {
      first: 874,
      extra: 676,
      helpers: ['Osc::exp_approx(float)', 'memset'],
      unwired: { first: 790, extra: 572, helpers: ['Osc::exp_approx(float)', 'memset'] },
      snapshotHash: '51754dcc3757ff3f'
    },
    'logue/filter/tilt': {
      first: 600,
      extra: 352,
      helpers: [],
      unwired: { first: 548, extra: 280, helpers: [] },
      snapshotHash: '99712da0bbd917df'
    },
    'logue/filter/formant': {
      first: 646,
      extra: 624,
      helpers: ['Osc::formant_g(float, float, float, int)', 'memset'],
      unwired: {
        first: 494,
        extra: 412,
        helpers: ['Osc::formant_g(float, float, float, int)', 'memset']
      },
      snapshotHash: '0eae7be6852f4378'
    },
    'logue/sense/pitch': { first: 0, extra: 0, helpers: [], snapshotHash: 'bc482cf6e4e29433' },
    'logue/sense/control': { first: 8, extra: 0, helpers: [], snapshotHash: '550ef812bd56decd' },
    'logue/sense/shape': { first: 0, extra: 0, helpers: [], snapshotHash: '325e380beee3bc55' },
    'logue/sense/shape-2': { first: 0, extra: 0, helpers: [], snapshotHash: '0a03598e05e5c340' },
    'logue/sense/cutoff': { first: 0, extra: 0, helpers: [], snapshotHash: '6bc89bcd79ffcb07' },
    'logue/sense/resonance': { first: 0, extra: 0, helpers: [], snapshotHash: '547eb218df760f8c' },
    'logue/sense/param': { first: 4, extra: 0, helpers: [], snapshotHash: '64ad5fc4bd9ad056' },
    'logue/sense/gate': { first: 24, extra: 0, helpers: [], snapshotHash: '5c83466572c3c9c0' },
    'logue/util/constant': { first: 4, extra: 0, helpers: [], snapshotHash: 'f3edec1a842e0630' },
    'logue/util/unipolar-to-bipolar': {
      first: 44,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '7a44146c55ce7e26'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 40,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '123ed572e3392a1a'
    },
    'logue/math/negate': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '80764f40f75f22b5'
    },
    'logue/math/one-minus': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f4a6e757bc9dd221'
    },
    'logue/math/curve': {
      first: 192,
      extra: 108,
      helpers: [],
      unwired: { first: 84, extra: 56, helpers: [] },
      snapshotHash: 'a6bc9c67c8ed7f33'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '1c1ccaf32ecaf295'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'd9827f1376cc7742'
    },
    'logue/math/scale': {
      first: 20,
      extra: 12,
      helpers: [],
      unwired: { first: 24, extra: 0, helpers: [] },
      snapshotHash: '33fcee3c312305e9'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '7ad50beda32b6968'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'df0bd7fdbe016146'
    },
    'logue/math/clamp': {
      first: 44,
      extra: 36,
      helpers: [],
      unwired: { first: 48, extra: 24, helpers: [] },
      snapshotHash: '0cdd97825f4434d9'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '6b592c1cff9c6d33'
    },
    'logue/logic/greater-than': {
      first: 24,
      extra: 32,
      helpers: [],
      unwired: { first: 20, extra: 16, helpers: [] },
      snapshotHash: 'c1bb3de72d4ece0e'
    },
    'logue/logic/less-than': {
      first: 24,
      extra: 32,
      helpers: [],
      unwired: { first: 20, extra: 16, helpers: [] },
      snapshotHash: '4357ab282a1ca032'
    },
    'logue/logic/equal': {
      first: 44,
      extra: 44,
      helpers: [],
      unwired: { first: 44, extra: 28, helpers: [] },
      snapshotHash: 'f164a8c5070849fd'
    },
    'logue/logic/and': {
      first: 20,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'f80de56b91f2e236'
    },
    'logue/logic/or': {
      first: 20,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '07e57403fbf2d1de'
    },
    'logue/logic/xor': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'c9d3d1a8aab33c41'
    },
    'logue/mux/mux2': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '43132007849f2d5e'
    },
    'logue/mux/mux4': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'e7cd1ca8a0645ebe'
    },
    'logue/mux/demux2': {
      first: 16,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'e60fc2ba0786e999'
    },
    'logue/logic/schmitt': {
      first: 60,
      extra: 56,
      helpers: [],
      unwired: { first: 60, extra: 44, helpers: [] },
      snapshotHash: '5affa568710e10ce'
    },
    'logue/logic/edge': {
      first: 48,
      extra: 28,
      helpers: [],
      unwired: { first: 28, extra: 20, helpers: [] },
      snapshotHash: 'c26efc0252e90a1d'
    },
    'logue/util/sample-hold': {
      first: 44,
      extra: 28,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'a29dc3d4ed9dc21e'
    },
    'logue/util/glide': {
      first: 120,
      extra: 84,
      helpers: [],
      unwired: { first: 124, extra: 72, helpers: [] },
      snapshotHash: '006a80d815345ce6'
    },
    'logue/util/slew': {
      first: 352,
      extra: 232,
      helpers: [],
      unwired: { first: 264, extra: 128, helpers: [] },
      snapshotHash: 'e3861ecccecfc253'
    },
    'logue/util/sample-delay': {
      first: 64,
      extra: 16,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '90730202bac723c0'
    },
    'logue/util/delay': {
      first: 270,
      extra: 192,
      helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 190,
        extra: 64,
        helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: 'da512c286cda27d0'
    },
    'logue/util/quantize': {
      first: 144,
      extra: 128,
      helpers: ['Osc::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 140,
        extra: 92,
        helpers: ['Osc::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'a721587239315819'
    },
    'logue/env/follower': {
      first: 208,
      extra: 152,
      helpers: [],
      unwired: { first: 192, extra: 144, helpers: [] },
      snapshotHash: 'f7893e7c4cfddfe4'
    },
    'logue/filter/hilbert': {
      first: 334,
      extra: 264,
      helpers: ['memset'],
      unwired: { first: 342, extra: 252, helpers: ['memset'] },
      snapshotHash: 'f56fb7646016882f'
    },
    'logue/util/freq-shift': {
      first: 278,
      extra: 200,
      helpers: [
        'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 170,
        extra: 124,
        helpers: [
          'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'e1b3aaea0b6b5dba'
    },
    'logue/mix/pan': {
      first: 104,
      extra: 104,
      helpers: [],
      unwired: { first: 84, extra: 60, helpers: [] },
      snapshotHash: 'd139dc1b3b1c3b34'
    },
    'logue/mix/pan-mix2': {
      first: 220,
      extra: 208,
      helpers: [],
      unwired: { first: 36, extra: 0, helpers: [] },
      snapshotHash: '012908465f425a50'
    },
    'logue/mix/bus-send': {
      first: 16,
      extra: 12,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '574efcb254356628'
    },
    'logue/mix/bus-receive': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'fb1b473a0c1edfc3'
    },
    'logue/mix/bus-send-stereo': {
      first: 16,
      extra: 12,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'ce0f1ba491fc3493'
    },
    'logue/mix/bus-receive-stereo': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '97a974b3ae145ea1'
    },
    'logue/mix/width': {
      first: 92,
      extra: 56,
      helpers: [],
      unwired: { first: 32, extra: 4, helpers: [] },
      snapshotHash: 'e3d3cef19609c42b'
    },
    'logue/logic/chance': {
      first: 192,
      extra: 136,
      helpers: [],
      unwired: { first: 116, extra: 72, helpers: [] },
      snapshotHash: 'efecc236e2563837'
    },
    'logue/logic/round-robin': {
      first: 104,
      extra: 72,
      helpers: [],
      unwired: { first: 52, extra: 0, helpers: [] },
      snapshotHash: '7338eb6e334fed60'
    }
  },
  'minilogue-xd:fx': {
    'logue/osc/sine': {
      first: 440,
      extra: 260,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 204, extra: 100, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'b34b1284af3c9ca7'
    },
    'logue/osc/saw': {
      first: 858,
      extra: 620,
      helpers: ['Fx::harmonic_ratio(float)', 'Fx::note_w0(float)'],
      unwired: { first: 280, extra: 156, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '689d43e99e06ce9c'
    },
    'logue/osc/square': {
      first: 460,
      extra: 252,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 164,
        extra: 80,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '9a189b5fd7ef929c'
    },
    'logue/osc/pulse': {
      first: 524,
      extra: 316,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 188,
        extra: 92,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '773b9bbd527f1576'
    },
    'logue/osc/triangle': {
      first: 360,
      extra: 208,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 104, extra: 76, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'c19162f9574d3fe7'
    },
    'logue/osc/additive': {
      first: 324,
      extra: 184,
      helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)'],
      unwired: {
        first: 100,
        extra: 64,
        helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)']
      },
      snapshotHash: '8ad6107dc41ce335'
    },
    'logue/osc/granular': {
      first: 1694,
      extra: 1576,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 1474, extra: 1332, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '287537a0ffee7fe9'
    },
    'logue/mix/mix2': {
      first: 32,
      extra: 24,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: 'bcf10c53a2411c0f'
    },
    'logue/math/multiply': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '422c16a247da8ec8'
    },
    'logue/mix/crossfader': {
      first: 212,
      extra: 140,
      helpers: [],
      unwired: { first: 212, extra: 128, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: 'ff48b03b50520cf3'
    },
    'logue/mix/stereo-mix2': {
      first: 32,
      extra: 24,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: '73842bd820468e9f'
    },
    'logue/mix/stereo-crossfader': {
      first: 200,
      extra: 136,
      helpers: [],
      unwired: { first: 192, extra: 116, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: '779c8ef1206c74bd'
    },
    'logue/filter/lowpass-cheap': {
      first: 92,
      extra: 64,
      helpers: [],
      unwired: { first: 88, extra: 48, helpers: [] },
      snapshotHash: '9498d8e54c739257'
    },
    'logue/filter/highpass-cheap': {
      first: 88,
      extra: 100,
      helpers: [],
      unwired: { first: 88, extra: 52, helpers: [] },
      snapshotHash: '5918f33ffc84533f'
    },
    'logue/gain/vca': {
      first: 4,
      extra: 8,
      helpers: [],
      unwired: { first: 20, extra: 0, helpers: [] },
      snapshotHash: '71e7c2874a2780a1'
    },
    'logue/env/ad': {
      first: 452,
      extra: 336,
      helpers: ['Fx::env_rate_from_percent(float)'],
      unwired: { first: 240, extra: 136, helpers: ['Fx::env_rate_from_percent(float)'] },
      snapshotHash: 'c384655566b26ffc'
    },
    'logue/env/adsr': {
      first: 332,
      extra: 204,
      helpers: ['Fx::adsr_rate(float, float)'],
      unwired: { first: 340, extra: 144, helpers: ['Fx::adsr_rate(float, float)'] },
      snapshotHash: 'abd7e5820bec87bc'
    },
    'logue/env/one-knob-adsr': {
      first: 512,
      extra: 320,
      helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)'],
      unwired: {
        first: 480,
        extra: 208,
        helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)']
      },
      snapshotHash: 'a39fd0de0ef1ae2a'
    },
    'logue/env/multistage': {
      first: 732,
      extra: 580,
      helpers: [],
      unwired: { first: 644, extra: 388, helpers: [] },
      snapshotHash: '13bbe27c71cd6bc6'
    },
    'logue/lfo/sine-lfo': {
      first: 316,
      extra: 204,
      helpers: [],
      unwired: { first: 224, extra: 96, helpers: [] },
      snapshotHash: 'f091daaf62b2b62e'
    },
    'logue/lfo/triangle-lfo': {
      first: 236,
      extra: 188,
      helpers: [],
      unwired: { first: 140, extra: 76, helpers: [] },
      snapshotHash: '63720761f9fb074b'
    },
    'logue/lfo/square-lfo': {
      first: 224,
      extra: 152,
      helpers: [],
      unwired: { first: 124, extra: 72, helpers: [] },
      snapshotHash: '5bf8d1d088df38b0'
    },
    'logue/lfo/ramp-up': {
      first: 216,
      extra: 144,
      helpers: [],
      unwired: { first: 116, extra: 60, helpers: [] },
      snapshotHash: '657d45b8a4249ea5'
    },
    'logue/lfo/ramp-down': {
      first: 216,
      extra: 144,
      helpers: [],
      unwired: { first: 116, extra: 60, helpers: [] },
      snapshotHash: '93415749054fe77d'
    },
    'logue/lfo/fast-square': {
      first: 376,
      extra: 268,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 212, extra: 136, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '9023a42eadc26048'
    },
    'logue/lfo/random-steps': {
      first: 236,
      extra: 180,
      helpers: [],
      unwired: { first: 180, extra: 96, helpers: [] },
      snapshotHash: '001bad58241c33a2'
    },
    'logue/osc/noise': {
      first: 430,
      extra: 268,
      helpers: ['memset'],
      snapshotHash: 'c55e2984e99ac4a6'
    },
    'logue/osc/lfsr': {
      first: 525,
      extra: 364,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 477, extra: 284, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '7fbe59bdb96624a8'
    },
    'logue/shape/wavefolder': {
      first: 124,
      extra: 124,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: '6597b9a61c6b5800'
    },
    'logue/shape/soft-clip': {
      first: 92,
      extra: 92,
      helpers: [],
      unwired: { first: 44, extra: 16, helpers: [] },
      snapshotHash: '94bd46054709e8a4'
    },
    'logue/shape/drive': {
      first: 512,
      extra: 416,
      helpers: ['Fx::exp_approx(float)'],
      unwired: { first: 336, extra: 184, helpers: ['Fx::exp_approx(float)'] },
      snapshotHash: '47bc5cda72f6b7e2'
    },
    'logue/filter/comb': {
      first: 778,
      extra: 524,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 690, extra: 296, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '1fd2dcd5f18abf0e'
    },
    'logue/filter/string': {
      first: 582,
      extra: 484,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 418,
        extra: 272,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: 'd2fb4b7548c8393b'
    },
    'logue/osc/exciter': {
      first: 768,
      extra: 332,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 752, extra: 216, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '718efdc3d5a3a5fc'
    },
    'logue/osc/sync': {
      first: 316,
      extra: 240,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 264,
        extra: 128,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: 'de6812a7e1beb6e4'
    },
    'logue/osc/phase-dist': {
      first: 1548,
      extra: 1396,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 1124, extra: 996, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '447d0e2b472a3a55'
    },
    'logue/osc/bass-support': {
      first: 960,
      extra: 852,
      helpers: [
        'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Fx::note_w0(float)',
        'memset'
      ],
      unwired: {
        first: 676,
        extra: 556,
        helpers: [
          'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
          'Fx::note_w0(float)',
          'memset'
        ]
      },
      snapshotHash: '8c0581583e35f2f4'
    },
    'logue/filter/svf': {
      first: 568,
      extra: 468,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 508, extra: 344, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '71e157475bbe46c8'
    },
    'logue/filter/ladder': {
      first: 1294,
      extra: 1228,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 886, extra: 776, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '14f53da66bd476e6'
    },
    'logue/filter/eq-band': {
      first: 954,
      extra: 820,
      helpers: ['Fx::exp_approx(float)', 'Fx::note_w0(float)', 'memset'],
      unwired: {
        first: 690,
        extra: 568,
        helpers: ['Fx::exp_approx(float)', 'Fx::note_w0(float)', 'memset']
      },
      snapshotHash: '51754dcc3757ff3f'
    },
    'logue/filter/tilt': {
      first: 632,
      extra: 464,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 440, extra: 244, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '99712da0bbd917df'
    },
    'logue/filter/formant': {
      first: 714,
      extra: 648,
      helpers: ['Fx::formant_g(float, float, float, int)', 'memset'],
      unwired: {
        first: 514,
        extra: 440,
        helpers: ['Fx::formant_g(float, float, float, int)', 'memset']
      },
      snapshotHash: '0eae7be6852f4378'
    },
    'logue/sense/control': { first: 8, extra: 0, helpers: [], snapshotHash: '550ef812bd56decd' },
    'logue/util/constant': { first: 4, extra: 0, helpers: [], snapshotHash: 'f3edec1a842e0630' },
    'logue/util/unipolar-to-bipolar': {
      first: 48,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '7a44146c55ce7e26'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 36,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '123ed572e3392a1a'
    },
    'logue/math/negate': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '80764f40f75f22b5'
    },
    'logue/math/one-minus': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f4a6e757bc9dd221'
    },
    'logue/math/curve': {
      first: 204,
      extra: 96,
      helpers: [],
      unwired: { first: 96, extra: 44, helpers: [] },
      snapshotHash: 'a6bc9c67c8ed7f33'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '1c1ccaf32ecaf295'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'd9827f1376cc7742'
    },
    'logue/math/scale': {
      first: 24,
      extra: 12,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: '33fcee3c312305e9'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '7ad50beda32b6968'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'df0bd7fdbe016146'
    },
    'logue/math/clamp': {
      first: 44,
      extra: 36,
      helpers: [],
      unwired: { first: 52, extra: 20, helpers: [] },
      snapshotHash: '0cdd97825f4434d9'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '6b592c1cff9c6d33'
    },
    'logue/logic/greater-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 32, extra: 4, helpers: [] },
      snapshotHash: 'c1bb3de72d4ece0e'
    },
    'logue/logic/less-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 28, extra: 8, helpers: [] },
      snapshotHash: '4357ab282a1ca032'
    },
    'logue/logic/equal': {
      first: 56,
      extra: 40,
      helpers: [],
      unwired: { first: 48, extra: 20, helpers: [] },
      snapshotHash: 'f164a8c5070849fd'
    },
    'logue/logic/and': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'f80de56b91f2e236'
    },
    'logue/logic/or': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '07e57403fbf2d1de'
    },
    'logue/logic/xor': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'c9d3d1a8aab33c41'
    },
    'logue/mux/mux2': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '43132007849f2d5e'
    },
    'logue/mux/mux4': {
      first: 24,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'e7cd1ca8a0645ebe'
    },
    'logue/mux/demux2': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'e60fc2ba0786e999'
    },
    'logue/logic/schmitt': {
      first: 76,
      extra: 52,
      helpers: [],
      unwired: { first: 76, extra: 32, helpers: [] },
      snapshotHash: '5affa568710e10ce'
    },
    'logue/logic/edge': {
      first: 64,
      extra: 32,
      helpers: [],
      unwired: { first: 44, extra: 12, helpers: [] },
      snapshotHash: 'c26efc0252e90a1d'
    },
    'logue/util/sample-hold': {
      first: 68,
      extra: 36,
      helpers: [],
      unwired: { first: 20, extra: 0, helpers: [] },
      snapshotHash: 'a29dc3d4ed9dc21e'
    },
    'logue/util/glide': {
      first: 140,
      extra: 72,
      helpers: [],
      unwired: { first: 148, extra: 52, helpers: [] },
      snapshotHash: '006a80d815345ce6'
    },
    'logue/util/slew': {
      first: 428,
      extra: 252,
      helpers: [],
      unwired: { first: 300, extra: 104, helpers: [] },
      snapshotHash: 'e3861ecccecfc253'
    },
    'logue/util/sample-delay': {
      first: 84,
      extra: 12,
      helpers: [],
      unwired: { first: 16, extra: 0, helpers: [] },
      snapshotHash: '90730202bac723c0'
    },
    'logue/util/delay': {
      first: 306,
      extra: 212,
      helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 186,
        extra: 108,
        helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: 'da512c286cda27d0'
    },
    'logue/util/long-delay': {
      first: 686,
      extra: 348,
      helpers: ['memset'],
      unwired: { first: 586, extra: 220, helpers: ['memset'] },
      snapshotHash: '8c91d8d963960391'
    },
    'logue/util/quantize': {
      first: 164,
      extra: 136,
      helpers: ['Fx::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 164,
        extra: 92,
        helpers: ['Fx::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'a721587239315819'
    },
    'logue/filter/allpass': {
      first: 358,
      extra: 184,
      helpers: ['memset'],
      unwired: { first: 298, extra: 160, helpers: ['memset'] },
      snapshotHash: 'f2a1656c07fb52d5'
    },
    'logue/env/follower': {
      first: 248,
      extra: 136,
      helpers: [],
      unwired: { first: 232, extra: 104, helpers: [] },
      snapshotHash: 'f7893e7c4cfddfe4'
    },
    'logue/sense/tempo': { first: 120, extra: 52, helpers: [], snapshotHash: '0410106efe6cce20' },
    'logue/filter/hilbert': {
      first: 378,
      extra: 276,
      helpers: ['memset'],
      unwired: { first: 382, extra: 240, helpers: ['memset'] },
      snapshotHash: 'f56fb7646016882f'
    },
    'logue/util/freq-shift': {
      first: 306,
      extra: 232,
      helpers: [
        'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 198,
        extra: 136,
        helpers: [
          'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'e1b3aaea0b6b5dba'
    },
    'logue/util/buffer': {
      first: 558,
      extra: 480,
      helpers: ['memset'],
      unwired: { first: 542, extra: 408, helpers: ['memset'] },
      snapshotHash: 'd11fef6b9acccce2'
    },
    'logue/util/buffer-tap': {
      first: 602,
      extra: 508,
      helpers: ['memset'],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: 'c9f54d6abbaf5c76'
    },
    'logue/util/grain': {
      first: 1006,
      extra: 896,
      helpers: ['memset'],
      unwired: { first: 106, extra: 0, helpers: ['memset'] },
      snapshotHash: '8c1b233d213f6d52'
    },
    'logue/util/reverse-tap': {
      first: 998,
      extra: 924,
      helpers: ['memset'],
      unwired: { first: 78, extra: 4, helpers: ['memset'] },
      snapshotHash: 'f0f4d753989ec3d8'
    },
    'logue/mix/pan': {
      first: 208,
      extra: 172,
      helpers: [],
      unwired: { first: 112, extra: 64, helpers: [] },
      snapshotHash: 'd139dc1b3b1c3b34'
    },
    'logue/mix/pan-mix2': {
      first: 408,
      extra: 360,
      helpers: [],
      unwired: { first: 72, extra: 0, helpers: [] },
      snapshotHash: '012908465f425a50'
    },
    'logue/mix/bus-send': {
      first: 20,
      extra: 12,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '574efcb254356628'
    },
    'logue/mix/bus-receive': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'fb1b473a0c1edfc3'
    },
    'logue/mix/bus-send-stereo': {
      first: 20,
      extra: 12,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'ce0f1ba491fc3493'
    },
    'logue/mix/bus-receive-stereo': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '97a974b3ae145ea1'
    },
    'logue/mix/width': {
      first: 96,
      extra: 76,
      helpers: [],
      unwired: { first: 40, extra: 0, helpers: [] },
      snapshotHash: 'e3d3cef19609c42b'
    },
    'logue/logic/chance': {
      first: 232,
      extra: 140,
      helpers: [],
      unwired: { first: 140, extra: 76, helpers: [] },
      snapshotHash: 'efecc236e2563837'
    },
    'logue/logic/round-robin': {
      first: 124,
      extra: 76,
      helpers: [],
      unwired: { first: 76, extra: 0, helpers: [] },
      snapshotHash: '7338eb6e334fed60'
    }
  },
  'nts1mkii:osc': {
    'logue/osc/sine': {
      first: 671,
      extra: 338,
      helpers: [],
      unwired: { first: 431, extra: 226, helpers: [] },
      snapshotHash: '9d62a35321ca9ea1'
    },
    'logue/osc/saw': {
      first: 785,
      extra: 435,
      helpers: [],
      unwired: { first: 453, extra: 287, helpers: [] },
      snapshotHash: 'c45abafd27ac2b00'
    },
    'logue/osc/square': {
      first: 673,
      extra: 346,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 433, extra: 254, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '2052bf3853427931'
    },
    'logue/osc/pulse': {
      first: 737,
      extra: 398,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 453, extra: 274, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '89a5a76831726b8a'
    },
    'logue/osc/triangle': {
      first: 549,
      extra: 266,
      helpers: [],
      unwired: { first: 313, extra: 158, helpers: [] },
      snapshotHash: '5d87996ccd566443'
    },
    'logue/osc/additive': {
      first: 626,
      extra: 210,
      helpers: ['Osc::additive_step(float, float, float)'],
      unwired: { first: 462, extra: 158, helpers: ['Osc::additive_step(float, float, float)'] },
      snapshotHash: '710237512735685f'
    },
    'logue/osc/granular': {
      first: 2102,
      extra: 1528,
      helpers: ['Osc::note_w0(float)', 'memset'],
      unwired: { first: 1866, extra: 1276, helpers: ['Osc::note_w0(float)', 'memset'] },
      snapshotHash: '0f2f2bc413fac628'
    },
    'logue/osc/sample': {
      first: 963,
      extra: 644,
      helpers: ['Osc::note_w0(float)'],
      unwired: { first: 879, extra: 540, helpers: ['Osc::note_w0(float)'] },
      snapshotHash: '81e131cf2b133467'
    },
    'logue/osc/wavetable': {
      first: 1190,
      extra: 842,
      helpers: [],
      unwired: { first: 1018, extra: 778, helpers: [] },
      snapshotHash: '7f74088dc46dc84b'
    },
    'logue/mix/mix2': {
      first: 28,
      extra: 24,
      helpers: [],
      unwired: { first: 16, extra: 0, helpers: [] },
      snapshotHash: 'd4c2671f67112925'
    },
    'logue/math/multiply': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'c12a420eb6898aca'
    },
    'logue/mix/crossfader': {
      first: 343,
      extra: 216,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 271, extra: 128, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: '32d9f5523a44c519'
    },
    'logue/mix/stereo-mix2': {
      first: 28,
      extra: 24,
      helpers: [],
      unwired: { first: 16, extra: 0, helpers: [] },
      snapshotHash: '78a5e7cc5a700097'
    },
    'logue/mix/stereo-crossfader': {
      first: 331,
      extra: 204,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 259, extra: 116, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: '34dede0f2fe425f0'
    },
    'logue/filter/lowpass-cheap': {
      first: 76,
      extra: 68,
      helpers: [],
      unwired: { first: 76, extra: 52, helpers: [] },
      snapshotHash: '8a67cbbd4bc2706c'
    },
    'logue/filter/highpass-cheap': {
      first: 76,
      extra: 72,
      helpers: [],
      unwired: { first: 76, extra: 56, helpers: [] },
      snapshotHash: 'de2ed94b1b0020ae'
    },
    'logue/gain/vca': {
      first: 8,
      extra: 0,
      helpers: [],
      unwired: { first: 20, extra: 0, helpers: [] },
      snapshotHash: '55bdc9341ea63a73'
    },
    'logue/env/ad': {
      first: 425,
      extra: 300,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 301, extra: 148, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: 'df5f1d238dc76490'
    },
    'logue/env/ahd': {
      first: 437,
      extra: 293,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 313, extra: 128, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: '1eb1aac5889707f1'
    },
    'logue/env/adsr': {
      first: 405,
      extra: 291,
      helpers: ['Osc::adsr_rate(float, float)'],
      unwired: { first: 413, extra: 263, helpers: ['Osc::adsr_rate(float, float)'] },
      snapshotHash: 'e473b1d5c4aa2297'
    },
    'logue/env/one-knob-adsr': {
      first: 701,
      extra: 460,
      helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)'],
      unwired: {
        first: 705,
        extra: 404,
        helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)']
      },
      snapshotHash: 'a2b6a4d0621efcb3'
    },
    'logue/env/multistage': {
      first: 716,
      extra: 647,
      helpers: [],
      unwired: { first: 640, extra: 507, helpers: [] },
      snapshotHash: 'fa7f172c3c231698'
    },
    'logue/lfo/sine-lfo': {
      first: 350,
      extra: 208,
      helpers: [],
      unwired: { first: 250, extra: 124, helpers: [] },
      snapshotHash: 'b511f7a2cfbd7424'
    },
    'logue/lfo/triangle-lfo': {
      first: 228,
      extra: 156,
      helpers: [],
      unwired: { first: 132, extra: 72, helpers: [] },
      snapshotHash: '231e2330cae54204'
    },
    'logue/lfo/square-lfo': {
      first: 216,
      extra: 148,
      helpers: [],
      unwired: { first: 116, extra: 68, helpers: [] },
      snapshotHash: '7b163c27b233dd26'
    },
    'logue/lfo/ramp-up': {
      first: 208,
      extra: 140,
      helpers: [],
      unwired: { first: 108, extra: 56, helpers: [] },
      snapshotHash: '6d409d19fec135d7'
    },
    'logue/lfo/ramp-down': {
      first: 208,
      extra: 140,
      helpers: [],
      unwired: { first: 108, extra: 56, helpers: [] },
      snapshotHash: '720ad1f96c104bad'
    },
    'logue/lfo/fast-square': {
      first: 553,
      extra: 346,
      helpers: [],
      unwired: { first: 401, extra: 230, helpers: [] },
      snapshotHash: '8b0639df5cf67dd1'
    },
    'logue/lfo/random-steps': {
      first: 216,
      extra: 148,
      helpers: [],
      unwired: { first: 160, extra: 92, helpers: [] },
      snapshotHash: '067f77b20c4869f8'
    },
    'logue/osc/noise': {
      first: 439,
      extra: 330,
      helpers: ['memset'],
      snapshotHash: 'e881cd39c2a173f2'
    },
    'logue/osc/lfsr': {
      first: 748,
      extra: 552,
      helpers: [],
      unwired: { first: 700, extra: 484, helpers: [] },
      snapshotHash: 'bd987c099dd83217'
    },
    'logue/shape/wavefolder': {
      first: 124,
      extra: 100,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: '0c7456454ea4b737'
    },
    'logue/shape/soft-clip': {
      first: 92,
      extra: 68,
      helpers: [],
      unwired: { first: 44, extra: 16, helpers: [] },
      snapshotHash: '27c2fc93b77d9b12'
    },
    'logue/shape/drive': {
      first: 526,
      extra: 360,
      helpers: ['Osc::exp_approx(float)'],
      unwired: { first: 370, extra: 204, helpers: ['Osc::exp_approx(float)'] },
      snapshotHash: '96074ea28992bb10'
    },
    'logue/filter/comb': {
      first: 996,
      extra: 736,
      helpers: ['memset'],
      unwired: { first: 904, extra: 560, helpers: ['memset'] },
      snapshotHash: '6f2eb8a4e83b0dde'
    },
    'logue/filter/string': {
      first: 1085,
      extra: 752,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 917,
        extra: 518,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: '5ad65e1041717e95'
    },
    'logue/osc/exciter': {
      first: 1101,
      extra: 415,
      helpers: [],
      unwired: { first: 1065, extra: 343, helpers: [] },
      snapshotHash: '599828ab713214c9'
    },
    'logue/osc/sync': {
      first: 521,
      extra: 216,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 469,
        extra: 132,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: '9b6601f332d594a2'
    },
    'logue/osc/phase-dist': {
      first: 1567,
      extra: 1042,
      helpers: [],
      unwired: { first: 1783, extra: 910, helpers: [] },
      snapshotHash: 'eabca751e9792c98'
    },
    'logue/osc/bass-support': {
      first: 1157,
      extra: 728,
      helpers: [
        'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Osc::note_w0(float)',
        'memset'
      ],
      unwired: {
        first: 1103,
        extra: 670,
        helpers: [
          'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: 'ab5e9dc8f773c4de'
    },
    'logue/filter/svf': {
      first: 717,
      extra: 730,
      helpers: [],
      unwired: { first: 661, extra: 626, helpers: [] },
      snapshotHash: '5fb80e35691d10e1'
    },
    'logue/filter/ladder': {
      first: 1284,
      extra: 1030,
      helpers: ['memset'],
      unwired: { first: 1120, extra: 846, helpers: ['memset'] },
      snapshotHash: '34d91ea1fa70578d'
    },
    'logue/filter/eq-band': {
      first: 1066,
      extra: 840,
      helpers: ['Osc::exp_approx(float)', 'memset'],
      unwired: { first: 982, extra: 740, helpers: ['Osc::exp_approx(float)', 'memset'] },
      snapshotHash: '5d834bd3a27dcfb3'
    },
    'logue/filter/tilt': {
      first: 657,
      extra: 488,
      helpers: [],
      unwired: { first: 601, extra: 420, helpers: [] },
      snapshotHash: '0408df22f9d25f29'
    },
    'logue/filter/formant': {
      first: 906,
      extra: 710,
      helpers: ['Osc::formant_g(float, float, float, int)', 'memset'],
      unwired: {
        first: 754,
        extra: 502,
        helpers: ['Osc::formant_g(float, float, float, int)', 'memset']
      },
      snapshotHash: '76834d8b5114c96a'
    },
    'logue/sense/pitch': { first: 0, extra: 0, helpers: [], snapshotHash: 'd643a2204ebf8c31' },
    'logue/sense/control': { first: 12, extra: 0, helpers: [], snapshotHash: 'c73a9c82a4d426eb' },
    'logue/sense/shape': { first: 0, extra: 0, helpers: [], snapshotHash: '190902c76999cf2a' },
    'logue/sense/shape-2': { first: 0, extra: 0, helpers: [], snapshotHash: '62a192485c1e02da' },
    'logue/sense/gate': { first: 40, extra: 0, helpers: [], snapshotHash: '84073775b7e33a40' },
    'logue/sense/velocity': { first: 64, extra: 0, helpers: [], snapshotHash: 'd6e37758828b253d' },
    'logue/util/constant': { first: 8, extra: 0, helpers: [], snapshotHash: '3330059ff140d8d0' },
    'logue/util/unipolar-to-bipolar': {
      first: 52,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'b3c33aeb61a986e5'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 44,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'a4ddf45ded321d40'
    },
    'logue/math/negate': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'b3572537a4eb872a'
    },
    'logue/math/one-minus': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f6edd23d384d50bf'
    },
    'logue/math/curve': {
      first: 188,
      extra: 181,
      helpers: [],
      unwired: { first: 96, extra: 137, helpers: [] },
      snapshotHash: '25af7509bf6e4d3d'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'fe563350ef515c84'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '5d7c3d8c9a6b92e6'
    },
    'logue/math/scale': {
      first: 20,
      extra: 16,
      helpers: [],
      unwired: { first: 28, extra: 4, helpers: [] },
      snapshotHash: 'c70f86a68a8f7f59'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '2cdad2b6d986b91f'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '34d04ce8b0aeed32'
    },
    'logue/math/clamp': {
      first: 48,
      extra: 36,
      helpers: [],
      unwired: { first: 56, extra: 24, helpers: [] },
      snapshotHash: 'd276a7683aa4e906'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '5fe455fe592d0fab'
    },
    'logue/logic/greater-than': {
      first: 36,
      extra: 24,
      helpers: [],
      unwired: { first: 32, extra: 8, helpers: [] },
      snapshotHash: '2425ce5b17c9e9af'
    },
    'logue/logic/less-than': {
      first: 36,
      extra: 24,
      helpers: [],
      unwired: { first: 32, extra: 8, helpers: [] },
      snapshotHash: 'a2138d4be323435a'
    },
    'logue/logic/equal': {
      first: 56,
      extra: 40,
      helpers: [],
      unwired: { first: 52, extra: 24, helpers: [] },
      snapshotHash: '70f3c81c4f62fce3'
    },
    'logue/logic/and': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '95af1d6cebd18869'
    },
    'logue/logic/or': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '0522842afeda8238'
    },
    'logue/logic/xor': {
      first: 8,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'a43dfe2dba6c4ada'
    },
    'logue/mux/mux2': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'f4afe5aa62ccb8ed'
    },
    'logue/mux/mux4': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'f87b33d5fd416602'
    },
    'logue/mux/demux2': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '1123200d547c0a35'
    },
    'logue/logic/schmitt': {
      first: 60,
      extra: 56,
      helpers: [],
      unwired: { first: 60, extra: 44, helpers: [] },
      snapshotHash: '139083adaa4c99e7'
    },
    'logue/logic/edge': {
      first: 56,
      extra: 28,
      helpers: [],
      unwired: { first: 36, extra: 12, helpers: [] },
      snapshotHash: 'e7198e51022b71c3'
    },
    'logue/util/sample-hold': {
      first: 52,
      extra: 32,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '0bbcd9f952c45116'
    },
    'logue/util/glide': {
      first: 124,
      extra: 167,
      helpers: [],
      unwired: { first: 132, extra: 155, helpers: [] },
      snapshotHash: 'c4c54bfe01cea0ae'
    },
    'logue/util/slew': {
      first: 344,
      extra: 377,
      helpers: [],
      unwired: { first: 256, extra: 281, helpers: [] },
      snapshotHash: '4d4575a0c936f266'
    },
    'logue/util/sample-delay': {
      first: 76,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '4871fdd6f8101c12'
    },
    'logue/util/delay': {
      first: 424,
      extra: 180,
      helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 336,
        extra: 80,
        helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: '5a261f7f4b38f586'
    },
    'logue/util/quantize': {
      first: 319,
      extra: 184,
      helpers: ['Osc::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 319,
        extra: 168,
        helpers: ['Osc::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'c14b68d30bfa3a3a'
    },
    'logue/env/follower': {
      first: 216,
      extra: 140,
      helpers: [],
      unwired: { first: 204, extra: 128, helpers: [] },
      snapshotHash: 'd9321a1a2791842a'
    },
    'logue/filter/hilbert': {
      first: 391,
      extra: 272,
      helpers: ['memset'],
      unwired: { first: 399, extra: 260, helpers: ['memset'] },
      snapshotHash: 'fd2f3aa1ec8fb4d1'
    },
    'logue/util/freq-shift': {
      first: 475,
      extra: 204,
      helpers: [
        'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 391,
        extra: 108,
        helpers: [
          'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'daf2604bb8c5df78'
    },
    'logue/mix/pan': {
      first: 116,
      extra: 88,
      helpers: [],
      unwired: { first: 96, extra: 56, helpers: [] },
      snapshotHash: '85c3069b7deec2a4'
    },
    'logue/mix/pan-mix2': {
      first: 224,
      extra: 204,
      helpers: [],
      unwired: { first: 40, extra: 0, helpers: [] },
      snapshotHash: '52a2d85076e67439'
    },
    'logue/mix/bus-send': {
      first: 20,
      extra: 8,
      helpers: [],
      unwired: { first: 16, extra: 0, helpers: [] },
      snapshotHash: '68f1c0e5a1d6f3b9'
    },
    'logue/mix/bus-receive': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '0da35584e3057bd0'
    },
    'logue/mix/bus-send-stereo': {
      first: 20,
      extra: 8,
      helpers: [],
      unwired: { first: 16, extra: 0, helpers: [] },
      snapshotHash: '4a8fc721767aa382'
    },
    'logue/mix/bus-receive-stereo': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '69b1fb98a7af0a4a'
    },
    'logue/mix/width': {
      first: 96,
      extra: 60,
      helpers: [],
      unwired: { first: 36, extra: 8, helpers: [] },
      snapshotHash: '06015c35efef39ea'
    },
    'logue/logic/chance': {
      first: 196,
      extra: 128,
      helpers: [],
      unwired: { first: 120, extra: 76, helpers: [] },
      snapshotHash: 'acb6bf64b0ba217f'
    },
    'logue/logic/round-robin': {
      first: 112,
      extra: 76,
      helpers: [],
      unwired: { first: 60, extra: 0, helpers: [] },
      snapshotHash: 'd40597ea765b39b4'
    }
  },
  'nts1mkii:fx': {
    'logue/osc/sine': {
      first: 559,
      extra: 337,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 327, extra: 116, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '9d62a35321ca9ea1'
    },
    'logue/osc/saw': {
      first: 994,
      extra: 692,
      helpers: ['Fx::harmonic_ratio(float)', 'Fx::note_w0(float)'],
      unwired: { first: 345, extra: 184, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'c45abafd27ac2b00'
    },
    'logue/osc/square': {
      first: 588,
      extra: 404,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 312,
        extra: 155,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '2052bf3853427931'
    },
    'logue/osc/pulse': {
      first: 652,
      extra: 472,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 336,
        extra: 171,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '89a5a76831726b8a'
    },
    'logue/osc/triangle': {
      first: 417,
      extra: 285,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 185, extra: 72, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '5d87996ccd566443'
    },
    'logue/osc/additive': {
      first: 540,
      extra: 257,
      helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)'],
      unwired: {
        first: 336,
        extra: 64,
        helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)']
      },
      snapshotHash: '710237512735685f'
    },
    'logue/osc/granular': {
      first: 2181,
      extra: 1604,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 1953, extra: 1340, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '0f2f2bc413fac628'
    },
    'logue/mix/mix2': {
      first: 28,
      extra: 24,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'd4c2671f67112925'
    },
    'logue/math/multiply': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'c12a420eb6898aca'
    },
    'logue/mix/crossfader': {
      first: 204,
      extra: 144,
      helpers: [],
      unwired: { first: 298, extra: 124, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: '32d9f5523a44c519'
    },
    'logue/mix/stereo-mix2': {
      first: 28,
      extra: 24,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '78a5e7cc5a700097'
    },
    'logue/mix/stereo-crossfader': {
      first: 192,
      extra: 140,
      helpers: [],
      unwired: { first: 286, extra: 112, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: '34dede0f2fe425f0'
    },
    'logue/filter/lowpass-cheap': {
      first: 92,
      extra: 72,
      helpers: [],
      unwired: { first: 92, extra: 48, helpers: [] },
      snapshotHash: '8a67cbbd4bc2706c'
    },
    'logue/filter/highpass-cheap': {
      first: 88,
      extra: 88,
      helpers: [],
      unwired: { first: 92, extra: 52, helpers: [] },
      snapshotHash: 'de2ed94b1b0020ae'
    },
    'logue/gain/vca': {
      first: 8,
      extra: 4,
      helpers: [],
      unwired: { first: 24, extra: 0, helpers: [] },
      snapshotHash: '55bdc9341ea63a73'
    },
    'logue/env/ad': {
      first: 564,
      extra: 415,
      helpers: ['Fx::env_rate_from_percent(float)'],
      unwired: { first: 348, extra: 152, helpers: ['Fx::env_rate_from_percent(float)'] },
      snapshotHash: 'df5f1d238dc76490'
    },
    'logue/env/adsr': {
      first: 428,
      extra: 290,
      helpers: ['Fx::adsr_rate(float, float)'],
      unwired: { first: 432, extra: 250, helpers: ['Fx::adsr_rate(float, float)'] },
      snapshotHash: 'e473b1d5c4aa2297'
    },
    'logue/env/one-knob-adsr': {
      first: 762,
      extra: 482,
      helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)'],
      unwired: {
        first: 730,
        extra: 394,
        helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)']
      },
      snapshotHash: 'a2b6a4d0621efcb3'
    },
    'logue/env/multistage': {
      first: 756,
      extra: 690,
      helpers: [],
      unwired: { first: 668, extra: 506, helpers: [] },
      snapshotHash: 'fa7f172c3c231698'
    },
    'logue/lfo/sine-lfo': {
      first: 366,
      extra: 216,
      helpers: [],
      unwired: { first: 270, extra: 128, helpers: [] },
      snapshotHash: 'b511f7a2cfbd7424'
    },
    'logue/lfo/triangle-lfo': {
      first: 244,
      extra: 172,
      helpers: [],
      unwired: { first: 148, extra: 80, helpers: [] },
      snapshotHash: '231e2330cae54204'
    },
    'logue/lfo/square-lfo': {
      first: 228,
      extra: 160,
      helpers: [],
      unwired: { first: 132, extra: 76, helpers: [] },
      snapshotHash: '7b163c27b233dd26'
    },
    'logue/lfo/ramp-up': {
      first: 224,
      extra: 148,
      helpers: [],
      unwired: { first: 124, extra: 64, helpers: [] },
      snapshotHash: '6d409d19fec135d7'
    },
    'logue/lfo/ramp-down': {
      first: 224,
      extra: 148,
      helpers: [],
      unwired: { first: 124, extra: 64, helpers: [] },
      snapshotHash: '720ad1f96c104bad'
    },
    'logue/lfo/fast-square': {
      first: 445,
      extra: 264,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 301, extra: 128, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '8b0639df5cf67dd1'
    },
    'logue/lfo/random-steps': {
      first: 252,
      extra: 184,
      helpers: [],
      unwired: { first: 200, extra: 112, helpers: [] },
      snapshotHash: '067f77b20c4869f8'
    },
    'logue/osc/noise': {
      first: 499,
      extra: 373,
      helpers: ['memset'],
      snapshotHash: 'e881cd39c2a173f2'
    },
    'logue/osc/lfsr': {
      first: 675,
      extra: 437,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 631, extra: 361, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'bd987c099dd83217'
    },
    'logue/shape/wavefolder': {
      first: 124,
      extra: 104,
      helpers: [],
      unwired: { first: 36, extra: 0, helpers: [] },
      snapshotHash: '0c7456454ea4b737'
    },
    'logue/shape/soft-clip': {
      first: 92,
      extra: 72,
      helpers: [],
      unwired: { first: 48, extra: 4, helpers: [] },
      snapshotHash: '27c2fc93b77d9b12'
    },
    'logue/shape/drive': {
      first: 609,
      extra: 416,
      helpers: ['Fx::exp_approx(float)'],
      unwired: { first: 433, extra: 204, helpers: ['Fx::exp_approx(float)'] },
      snapshotHash: '96074ea28992bb10'
    },
    'logue/filter/comb': {
      first: 936,
      extra: 684,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 848, extra: 488, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '6f2eb8a4e83b0dde'
    },
    'logue/filter/string': {
      first: 838,
      extra: 569,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 670,
        extra: 320,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: '5ad65e1041717e95'
    },
    'logue/osc/exciter': {
      first: 893,
      extra: 402,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 865, extra: 310, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '599828ab713214c9'
    },
    'logue/osc/sync': {
      first: 510,
      extra: 264,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 454,
        extra: 176,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: '9b6601f332d594a2'
    },
    'logue/osc/phase-dist': {
      first: 1675,
      extra: 1424,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 1503, extra: 1028, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'eabca751e9792c98'
    },
    'logue/osc/bass-support': {
      first: 1290,
      extra: 840,
      helpers: [
        'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Fx::note_w0(float)',
        'memset'
      ],
      unwired: {
        first: 1002,
        extra: 568,
        helpers: [
          'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
          'Fx::note_w0(float)',
          'memset'
        ]
      },
      snapshotHash: 'ab5e9dc8f773c4de'
    },
    'logue/filter/svf': {
      first: 665,
      extra: 630,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 601, extra: 526, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '5fb80e35691d10e1'
    },
    'logue/filter/ladder': {
      first: 1472,
      extra: 1192,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 1068, extra: 792, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '34d91ea1fa70578d'
    },
    'logue/filter/eq-band': {
      first: 1197,
      extra: 905,
      helpers: ['Fx::exp_approx(float)', 'Fx::note_w0(float)', 'memset'],
      unwired: {
        first: 933,
        extra: 669,
        helpers: ['Fx::exp_approx(float)', 'Fx::note_w0(float)', 'memset']
      },
      snapshotHash: '5d834bd3a27dcfb3'
    },
    'logue/filter/tilt': {
      first: 725,
      extra: 533,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 533, extra: 329, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '0408df22f9d25f29'
    },
    'logue/filter/formant': {
      first: 967,
      extra: 737,
      helpers: ['Fx::formant_g(float, float, float, int)', 'memset'],
      unwired: {
        first: 771,
        extra: 545,
        helpers: ['Fx::formant_g(float, float, float, int)', 'memset']
      },
      snapshotHash: '76834d8b5114c96a'
    },
    'logue/sense/control': { first: 8, extra: 0, helpers: [], snapshotHash: 'c73a9c82a4d426eb' },
    'logue/util/constant': { first: 8, extra: 0, helpers: [], snapshotHash: '3330059ff140d8d0' },
    'logue/util/unipolar-to-bipolar': {
      first: 48,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'b3c33aeb61a986e5'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 36,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'a4ddf45ded321d40'
    },
    'logue/math/negate': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'b3572537a4eb872a'
    },
    'logue/math/one-minus': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f6edd23d384d50bf'
    },
    'logue/math/curve': {
      first: 188,
      extra: 176,
      helpers: [],
      unwired: { first: 100, extra: 124, helpers: [] },
      snapshotHash: '25af7509bf6e4d3d'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'fe563350ef515c84'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '5d7c3d8c9a6b92e6'
    },
    'logue/math/scale': {
      first: 24,
      extra: 16,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: 'c70f86a68a8f7f59'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '2cdad2b6d986b91f'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '34d04ce8b0aeed32'
    },
    'logue/math/clamp': {
      first: 48,
      extra: 36,
      helpers: [],
      unwired: { first: 56, extra: 16, helpers: [] },
      snapshotHash: 'd276a7683aa4e906'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '5fe455fe592d0fab'
    },
    'logue/logic/greater-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 36, extra: 0, helpers: [] },
      snapshotHash: '2425ce5b17c9e9af'
    },
    'logue/logic/less-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: 'a2138d4be323435a'
    },
    'logue/logic/equal': {
      first: 56,
      extra: 44,
      helpers: [],
      unwired: { first: 52, extra: 16, helpers: [] },
      snapshotHash: '70f3c81c4f62fce3'
    },
    'logue/logic/and': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '95af1d6cebd18869'
    },
    'logue/logic/or': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '0522842afeda8238'
    },
    'logue/logic/xor': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'a43dfe2dba6c4ada'
    },
    'logue/mux/mux2': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'f4afe5aa62ccb8ed'
    },
    'logue/mux/mux4': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'f87b33d5fd416602'
    },
    'logue/mux/demux2': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '1123200d547c0a35'
    },
    'logue/logic/schmitt': {
      first: 76,
      extra: 60,
      helpers: [],
      unwired: { first: 76, extra: 40, helpers: [] },
      snapshotHash: '139083adaa4c99e7'
    },
    'logue/logic/edge': {
      first: 72,
      extra: 28,
      helpers: [],
      unwired: { first: 48, extra: 12, helpers: [] },
      snapshotHash: 'e7198e51022b71c3'
    },
    'logue/util/sample-hold': {
      first: 76,
      extra: 36,
      helpers: [],
      unwired: { first: 28, extra: 0, helpers: [] },
      snapshotHash: '0bbcd9f952c45116'
    },
    'logue/util/glide': {
      first: 140,
      extra: 178,
      helpers: [],
      unwired: { first: 148, extra: 150, helpers: [] },
      snapshotHash: 'c4c54bfe01cea0ae'
    },
    'logue/util/slew': {
      first: 444,
      extra: 407,
      helpers: [],
      unwired: { first: 312, extra: 279, helpers: [] },
      snapshotHash: '4d4575a0c936f266'
    },
    'logue/util/sample-delay': {
      first: 88,
      extra: 12,
      helpers: [],
      unwired: { first: 24, extra: 0, helpers: [] },
      snapshotHash: '4871fdd6f8101c12'
    },
    'logue/util/delay': {
      first: 479,
      extra: 204,
      helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 387,
        extra: 92,
        helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: '5a261f7f4b38f586'
    },
    'logue/util/long-delay': {
      first: 867,
      extra: 453,
      helpers: ['memset'],
      unwired: { first: 767, extra: 353, helpers: ['memset'] },
      snapshotHash: '0f339c0669d70b3c'
    },
    'logue/util/quantize': {
      first: 353,
      extra: 199,
      helpers: ['Fx::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 353,
        extra: 163,
        helpers: ['Fx::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'c14b68d30bfa3a3a'
    },
    'logue/filter/allpass': {
      first: 455,
      extra: 269,
      helpers: ['memset'],
      unwired: { first: 391, extra: 176, helpers: ['memset'] },
      snapshotHash: '5d6e2a6002a2916f'
    },
    'logue/env/follower': {
      first: 236,
      extra: 136,
      helpers: [],
      unwired: { first: 220, extra: 124, helpers: [] },
      snapshotHash: 'd9321a1a2791842a'
    },
    'logue/sense/tempo': { first: 209, extra: 56, helpers: [], snapshotHash: '64379ef9e400a346' },
    'logue/filter/hilbert': {
      first: 451,
      extra: 288,
      helpers: ['memset'],
      unwired: { first: 455, extra: 268, helpers: ['memset'] },
      snapshotHash: 'fd2f3aa1ec8fb4d1'
    },
    'logue/util/freq-shift': {
      first: 550,
      extra: 220,
      helpers: [
        'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 462,
        extra: 124,
        helpers: [
          'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'daf2604bb8c5df78'
    },
    'logue/util/buffer': {
      first: 647,
      extra: 484,
      helpers: ['memset'],
      unwired: { first: 631, extra: 436, helpers: ['memset'] },
      snapshotHash: 'ff5fa08c27c0dd0b'
    },
    'logue/util/buffer-tap': {
      first: 691,
      extra: 516,
      helpers: ['memset'],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: 'a2775113d5091c02'
    },
    'logue/util/grain': {
      first: 1099,
      extra: 904,
      helpers: ['memset'],
      unwired: { first: 223, extra: 0, helpers: ['memset'] },
      snapshotHash: '56068fdec015b527'
    },
    'logue/util/reverse-tap': {
      first: 1087,
      extra: 932,
      helpers: ['memset'],
      unwired: { first: 179, extra: 12, helpers: ['memset'] },
      snapshotHash: '8889deaa4a87a71f'
    },
    'logue/mix/pan': {
      first: 240,
      extra: 164,
      helpers: [],
      unwired: { first: 152, extra: 60, helpers: [] },
      snapshotHash: '85c3069b7deec2a4'
    },
    'logue/mix/pan-mix2': {
      first: 428,
      extra: 360,
      helpers: [],
      unwired: { first: 108, extra: 0, helpers: [] },
      snapshotHash: '52a2d85076e67439'
    },
    'logue/mix/bus-send': {
      first: 24,
      extra: 8,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: '68f1c0e5a1d6f3b9'
    },
    'logue/mix/bus-receive': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '0da35584e3057bd0'
    },
    'logue/mix/bus-send-stereo': {
      first: 24,
      extra: 8,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: '4a8fc721767aa382'
    },
    'logue/mix/bus-receive-stereo': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '69b1fb98a7af0a4a'
    },
    'logue/mix/width': {
      first: 92,
      extra: 64,
      helpers: [],
      unwired: { first: 40, extra: 0, helpers: [] },
      snapshotHash: '06015c35efef39ea'
    },
    'logue/logic/chance': {
      first: 224,
      extra: 168,
      helpers: [],
      unwired: { first: 152, extra: 100, helpers: [] },
      snapshotHash: 'acb6bf64b0ba217f'
    },
    'logue/logic/round-robin': {
      first: 136,
      extra: 84,
      helpers: [],
      unwired: { first: 88, extra: 0, helpers: [] },
      snapshotHash: 'd40597ea765b39b4'
    }
  }
}

/** The unit shell each context was measured in (`shellHash`, measureCodeSizes.ts). */
export const CODE_SHELL_HASH: Record<CodeSizeContext, string> = {
  'minilogue-xd:osc': 'f3edec1a842e0630',
  'minilogue-xd:fx': 'a0991e3ab2775c69',
  'nts1mkii:osc': '3330059ff140d8d0',
  'nts1mkii:fx': 'eff37e806744f307'
}

/** Bytes of each out-of-line function (demangled name) per context. */
export const CODE_HELPER_BYTES: Record<CodeSizeContext, Record<string, number>> = {
  'minilogue-xd:osc': {
    memset: 134,
    'Osc::additive_step(float, float, float)': 480,
    'Osc::adsr_rate(float, float)': 72,
    'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1482,
    'Osc::delay_step(short*, int*, float, float, float, float)': 328,
    'Osc::env_rate_from_percent(float)': 76,
    'Osc::exp_approx(float)': 68,
    'Osc::formant_g(float, float, float, int)': 468,
    'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 728,
    'Osc::knob_env_value(float, int)': 172,
    'Osc::note_w0(float)': 164,
    'Osc::polyblep(float, float)': 96,
    'Osc::quantize_step(float, int, float*, float*)': 328,
    'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)': 848,
    'Osc::xfade_settle(float*, float, float)': 172
  },
  'minilogue-xd:fx': {
    'Fx::additive_step(float, float, float)': 480,
    'Fx::adsr_rate(float, float)': 72,
    'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1482,
    'Fx::delay_step(short*, int*, float, float, float, float)': 328,
    'Fx::env_rate_from_percent(float)': 76,
    'Fx::exp_approx(float)': 68,
    'Fx::formant_g(float, float, float, int)': 608,
    'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 728,
    'Fx::harmonic_ratio(float)': 74,
    'Fx::knob_env_value(float, int)': 172,
    'Fx::note_w0(float)': 308,
    'Fx::polyblep(float, float)': 96,
    'Fx::quantize_step(float, int, float*, float*)': 328,
    'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)': 848,
    'Fx::xfade_settle(float*, float, float)': 172,
    memset: 134
  },
  'nts1mkii:osc': {
    memset: 16,
    'Osc::additive_step(float, float, float)': 488,
    'Osc::adsr_rate(float, float)': 72,
    'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1498,
    'Osc::delay_step(short*, int*, float, float, float, float)': 328,
    'Osc::env_rate_from_percent(float)': 76,
    'Osc::exp_approx(float)': 68,
    'Osc::formant_g(float, float, float, int)': 480,
    'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 744,
    'Osc::knob_env_value(float, int)': 180,
    'Osc::note_w0(float)': 176,
    'Osc::polyblep(float, float)': 96,
    'Osc::quantize_step(float, int, float*, float*)': 328,
    'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)': 864,
    'Osc::xfade_settle(float*, float, float)': 172
  },
  'nts1mkii:fx': {
    'Fx::additive_step(float, float, float)': 488,
    'Fx::adsr_rate(float, float)': 72,
    'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1498,
    'Fx::delay_step(short*, int*, float, float, float, float)': 328,
    'Fx::env_rate_from_percent(float)': 76,
    'Fx::exp_approx(float)': 68,
    'Fx::formant_g(float, float, float, int)': 616,
    'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 744,
    'Fx::harmonic_ratio(float)': 76,
    'Fx::knob_env_value(float, int)': 180,
    'Fx::note_w0(float)': 308,
    'Fx::polyblep(float, float)': 96,
    'Fx::quantize_step(float, int, float*, float*)': 328,
    'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)': 864,
    'Fx::xfade_settle(float*, float, float)': 172,
    memset: 16
  }
}
