// GENERATED by scripts/measureCodeSizes.ts -- do not edit by hand; re-run it instead.
// Measured with arm-none-eabi-gcc 15.3.1 (-Os): another compiler version gives other sizes.

/** What an otherwise empty unit of each kind loads (code + data + bss): a constant into the
 *  output for an oscillator, a pass-through for an effect. */
export const CODE_BASELINE_BYTES: Record<string, number> = {
  'minilogue-xd:osc': 536,
  'nts1mkii:osc': 4259,
  'nts1mkii:modfx': 4200,
  'nts1mkii:delfx': 4244,
  'nts1mkii:revfx': 4244,
  'minilogue-xd:modfx': 464,
  'minilogue-xd:delfx': 440,
  'minilogue-xd:revfx': 440
}

export interface CodeSize {
  first: number
  extra: number
  helpers: string[]
}

export type CodeSizeContext =
  'minilogue-xd:osc' | 'minilogue-xd:fx' | 'nts1mkii:osc' | 'nts1mkii:fx'

/**
 * Code bytes (text + rodata + data; tables the estimate counts as `sharedBytes` excluded) per
 * primitive and context, all inlets wired (`unwired`: none, where it has inlets): `first` for the first instance, `extra` for each
 * further one, and the out-of-line functions it brings (`helpers`, sized in
 * `CODE_HELPER_BYTES`), which a unit carries once however many primitives call them.
 */
export const CODE_SIZE_TABLE: Record<
  CodeSizeContext,
  Record<string, CodeSize & { unwired?: CodeSize; snapshotHash: string }>
> = {
  'minilogue-xd:osc': {
    'logue/osc/sine': {
      first: 568,
      extra: 260,
      helpers: [],
      unwired: { first: 304, extra: 176, helpers: [] },
      snapshotHash: 'b34b1284af3c9ca7'
    },
    'logue/osc/saw': {
      first: 728,
      extra: 296,
      helpers: [],
      unwired: { first: 396, extra: 192, helpers: [] },
      snapshotHash: '689d43e99e06ce9c'
    },
    'logue/osc/square': {
      first: 552,
      extra: 204,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 288, extra: 112, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '9a189b5fd7ef929c'
    },
    'logue/osc/pulse': {
      first: 612,
      extra: 260,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 308, extra: 128, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '773b9bbd527f1576'
    },
    'logue/osc/triangle': {
      first: 496,
      extra: 200,
      helpers: [],
      unwired: { first: 236, extra: 88, helpers: [] },
      snapshotHash: 'c19162f9574d3fe7'
    },
    'logue/osc/additive': {
      first: 420,
      extra: 140,
      helpers: ['Osc::additive_step(float, float, float)'],
      unwired: { first: 228, extra: 92, helpers: ['Osc::additive_step(float, float, float)'] },
      snapshotHash: '8ad6107dc41ce335'
    },
    'logue/osc/granular': {
      first: 1606,
      extra: 1476,
      helpers: ['Osc::note_w0(float)', 'memset'],
      unwired: { first: 1378, extra: 1268, helpers: ['Osc::note_w0(float)', 'memset'] },
      snapshotHash: '287537a0ffee7fe9'
    },
    'logue/osc/sample': {
      first: 732,
      extra: 652,
      helpers: ['Osc::note_w0(float)'],
      unwired: { first: 652, extra: 552, helpers: ['Osc::note_w0(float)'] },
      snapshotHash: '7cb41406b040b044'
    },
    'logue/osc/wavetable': {
      first: 1016,
      extra: 724,
      helpers: [],
      unwired: { first: 844, extra: 660, helpers: [] },
      snapshotHash: 'f92185a8a2498df5'
    },
    'logue/mix/mix2': {
      first: 24,
      extra: 20,
      helpers: [],
      unwired: { first: 28, extra: 8, helpers: [] },
      snapshotHash: '996f8fc72e564aa8'
    },
    'logue/math/multiply': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '422c16a247da8ec8'
    },
    'logue/mix/crossfader': {
      first: 276,
      extra: 216,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 184, extra: 148, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: 'ff48b03b50520cf3'
    },
    'logue/mix/stereo-mix2': {
      first: 24,
      extra: 20,
      helpers: [],
      unwired: { first: 28, extra: 8, helpers: [] },
      snapshotHash: 'a9fb88bd2914a2f3'
    },
    'logue/mix/stereo-crossfader': {
      first: 264,
      extra: 204,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 172, extra: 136, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: '779c8ef1206c74bd'
    },
    'logue/filter/lowpass-cheap': {
      first: 64,
      extra: 72,
      helpers: [],
      unwired: { first: 68, extra: 60, helpers: [] },
      snapshotHash: 'bfb55ed722e29c07'
    },
    'logue/filter/highpass-cheap': {
      first: 64,
      extra: 80,
      helpers: [],
      unwired: { first: 68, extra: 64, helpers: [] },
      snapshotHash: '4dc6fa6c0e39cc62'
    },
    'logue/gain/vca': {
      first: 4,
      extra: 4,
      helpers: [],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: '71e7c2874a2780a1'
    },
    'logue/env/ad': {
      first: 340,
      extra: 228,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 208, extra: 160, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: 'c384655566b26ffc'
    },
    'logue/env/ahd': {
      first: 316,
      extra: 220,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 180, extra: 132, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: 'e0f896dd954801b1'
    },
    'logue/env/adsr': {
      first: 328,
      extra: 208,
      helpers: ['Osc::adsr_rate(float, float)'],
      unwired: { first: 336, extra: 184, helpers: ['Osc::adsr_rate(float, float)'] },
      snapshotHash: 'abd7e5820bec87bc'
    },
    'logue/env/one-knob-adsr': {
      first: 468,
      extra: 296,
      helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)'],
      unwired: {
        first: 472,
        extra: 240,
        helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)']
      },
      snapshotHash: 'a39fd0de0ef1ae2a'
    },
    'logue/env/multistage': {
      first: 824,
      extra: 604,
      helpers: ['Osc::mseg_rate_from_percent(float)'],
      unwired: { first: 756, extra: 460, helpers: ['Osc::mseg_rate_from_percent(float)'] },
      snapshotHash: '8672d9936f6615d1'
    },
    'logue/lfo/sine-lfo': {
      first: 300,
      extra: 200,
      helpers: [],
      unwired: { first: 200, extra: 120, helpers: [] },
      snapshotHash: 'f091daaf62b2b62e'
    },
    'logue/lfo/triangle-lfo': {
      first: 220,
      extra: 168,
      helpers: [],
      unwired: { first: 132, extra: 68, helpers: [] },
      snapshotHash: '63720761f9fb074b'
    },
    'logue/lfo/square-lfo': {
      first: 212,
      extra: 140,
      helpers: [],
      unwired: { first: 116, extra: 64, helpers: [] },
      snapshotHash: '5bf8d1d088df38b0'
    },
    'logue/lfo/ramp-up': {
      first: 200,
      extra: 128,
      helpers: [],
      unwired: { first: 104, extra: 56, helpers: [] },
      snapshotHash: '657d45b8a4249ea5'
    },
    'logue/lfo/ramp-down': {
      first: 200,
      extra: 128,
      helpers: [],
      unwired: { first: 104, extra: 56, helpers: [] },
      snapshotHash: '93415749054fe77d'
    },
    'logue/lfo/fast-square': {
      first: 468,
      extra: 312,
      helpers: [],
      unwired: { first: 320, extra: 160, helpers: [] },
      snapshotHash: '9023a42eadc26048'
    },
    'logue/lfo/random-steps': {
      first: 200,
      extra: 168,
      helpers: [],
      unwired: { first: 144, extra: 112, helpers: [] },
      snapshotHash: '001bad58241c33a2'
    },
    'logue/osc/noise': {
      first: 394,
      extra: 252,
      helpers: ['memset'],
      snapshotHash: 'c55e2984e99ac4a6'
    },
    'logue/osc/lfsr': {
      first: 625,
      extra: 404,
      helpers: [],
      unwired: { first: 577, extra: 336, helpers: [] },
      snapshotHash: '7fbe59bdb96624a8'
    },
    'logue/shape/wavefolder': {
      first: 116,
      extra: 104,
      helpers: [],
      unwired: { first: 24, extra: 4, helpers: [] },
      snapshotHash: '6597b9a61c6b5800'
    },
    'logue/shape/soft-clip': {
      first: 84,
      extra: 72,
      helpers: [],
      unwired: { first: 36, extra: 20, helpers: [] },
      snapshotHash: '94bd46054709e8a4'
    },
    'logue/filter/comb': {
      first: 874,
      extra: 496,
      helpers: ['memset'],
      unwired: { first: 778, extra: 324, helpers: ['memset'] },
      snapshotHash: '1fd2dcd5f18abf0e'
    },
    'logue/filter/string': {
      first: 782,
      extra: 616,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 610,
        extra: 444,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: 'd2fb4b7548c8393b'
    },
    'logue/osc/exciter': {
      first: 940,
      extra: 336,
      helpers: [],
      unwired: { first: 916, extra: 232, helpers: [] },
      snapshotHash: '718efdc3d5a3a5fc'
    },
    'logue/osc/sync': {
      first: 288,
      extra: 216,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 192,
        extra: 176,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: 'de6812a7e1beb6e4'
    },
    'logue/osc/phase-dist': {
      first: 1224,
      extra: 1232,
      helpers: [],
      unwired: { first: 1464, extra: 784, helpers: [] },
      snapshotHash: '447d0e2b472a3a55'
    },
    'logue/osc/bass-support': {
      first: 790,
      extra: 676,
      helpers: [
        'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Osc::note_w0(float)'
      ],
      unwired: {
        first: 790,
        extra: 552,
        helpers: [
          'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)'
        ]
      },
      snapshotHash: 'da5adbf9ea4c7a45'
    },
    'logue/filter/svf': {
      first: 608,
      extra: 476,
      helpers: [],
      unwired: { first: 552, extra: 372, helpers: [] },
      snapshotHash: 'c762be0833d80be7'
    },
    'logue/filter/formant': {
      first: 284,
      extra: 232,
      helpers: [
        'Osc::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
      ],
      unwired: {
        first: 100,
        extra: 64,
        helpers: [
          'Osc::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
        ]
      },
      snapshotHash: '3064386816179abd'
    },
    'logue/sense/pitch': { first: 0, extra: 0, helpers: [], snapshotHash: 'bc482cf6e4e29433' },
    'logue/sense/control': { first: 8, extra: 0, helpers: [], snapshotHash: '550ef812bd56decd' },
    'logue/sense/shape': { first: 0, extra: 0, helpers: [], snapshotHash: '325e380beee3bc55' },
    'logue/sense/shape-2': { first: 0, extra: 0, helpers: [], snapshotHash: '0a03598e05e5c340' },
    'logue/sense/cutoff': { first: 0, extra: 0, helpers: [], snapshotHash: '6bc89bcd79ffcb07' },
    'logue/sense/resonance': { first: 0, extra: 0, helpers: [], snapshotHash: '547eb218df760f8c' },
    'logue/sense/param': { first: 4, extra: 0, helpers: [], snapshotHash: '64ad5fc4bd9ad056' },
    'logue/sense/gate': { first: 24, extra: 0, helpers: [], snapshotHash: '5c83466572c3c9c0' },
    'logue/util/constant': { first: 4, extra: 0, helpers: [], snapshotHash: 'f3edec1a842e0630' },
    'logue/util/unipolar-to-bipolar': {
      first: 44,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '7a44146c55ce7e26'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 40,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '123ed572e3392a1a'
    },
    'logue/math/negate': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '80764f40f75f22b5'
    },
    'logue/math/one-minus': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f4a6e757bc9dd221'
    },
    'logue/math/curve': {
      first: 192,
      extra: 108,
      helpers: [],
      unwired: { first: 84, extra: 56, helpers: [] },
      snapshotHash: 'a6bc9c67c8ed7f33'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '1c1ccaf32ecaf295'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'd9827f1376cc7742'
    },
    'logue/math/scale': {
      first: 20,
      extra: 12,
      helpers: [],
      unwired: { first: 24, extra: 0, helpers: [] },
      snapshotHash: '33fcee3c312305e9'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '7ad50beda32b6968'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'df0bd7fdbe016146'
    },
    'logue/math/clamp': {
      first: 44,
      extra: 36,
      helpers: [],
      unwired: { first: 48, extra: 24, helpers: [] },
      snapshotHash: '0cdd97825f4434d9'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '6b592c1cff9c6d33'
    },
    'logue/logic/greater-than': {
      first: 24,
      extra: 32,
      helpers: [],
      unwired: { first: 20, extra: 16, helpers: [] },
      snapshotHash: 'c1bb3de72d4ece0e'
    },
    'logue/logic/less-than': {
      first: 24,
      extra: 32,
      helpers: [],
      unwired: { first: 20, extra: 16, helpers: [] },
      snapshotHash: '4357ab282a1ca032'
    },
    'logue/logic/equal': {
      first: 44,
      extra: 44,
      helpers: [],
      unwired: { first: 44, extra: 28, helpers: [] },
      snapshotHash: 'f164a8c5070849fd'
    },
    'logue/logic/and': {
      first: 20,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'f80de56b91f2e236'
    },
    'logue/logic/or': {
      first: 20,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '07e57403fbf2d1de'
    },
    'logue/logic/xor': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'c9d3d1a8aab33c41'
    },
    'logue/mux/mux2': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '43132007849f2d5e'
    },
    'logue/mux/mux4': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'e7cd1ca8a0645ebe'
    },
    'logue/mux/demux2': {
      first: 16,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'e60fc2ba0786e999'
    },
    'logue/logic/schmitt': {
      first: 60,
      extra: 56,
      helpers: [],
      unwired: { first: 60, extra: 44, helpers: [] },
      snapshotHash: '5affa568710e10ce'
    },
    'logue/logic/edge': {
      first: 48,
      extra: 28,
      helpers: [],
      unwired: { first: 28, extra: 20, helpers: [] },
      snapshotHash: 'c26efc0252e90a1d'
    },
    'logue/util/sample-hold': {
      first: 44,
      extra: 28,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'a29dc3d4ed9dc21e'
    },
    'logue/util/glide': {
      first: 120,
      extra: 84,
      helpers: [],
      unwired: { first: 124, extra: 72, helpers: [] },
      snapshotHash: '006a80d815345ce6'
    },
    'logue/util/slew': {
      first: 352,
      extra: 232,
      helpers: [],
      unwired: { first: 264, extra: 128, helpers: [] },
      snapshotHash: 'e3861ecccecfc253'
    },
    'logue/util/sample-delay': {
      first: 64,
      extra: 16,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '90730202bac723c0'
    },
    'logue/util/delay': {
      first: 270,
      extra: 192,
      helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 190,
        extra: 64,
        helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: 'da512c286cda27d0'
    },
    'logue/util/quantize': {
      first: 144,
      extra: 128,
      helpers: ['Osc::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 140,
        extra: 92,
        helpers: ['Osc::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'a721587239315819'
    },
    'logue/env/follower': {
      first: 208,
      extra: 152,
      helpers: [],
      unwired: { first: 192, extra: 144, helpers: [] },
      snapshotHash: 'f7893e7c4cfddfe4'
    },
    'logue/filter/hilbert': {
      first: 334,
      extra: 264,
      helpers: ['memset'],
      unwired: { first: 342, extra: 252, helpers: ['memset'] },
      snapshotHash: 'f56fb7646016882f'
    },
    'logue/util/freq-shift': {
      first: 278,
      extra: 200,
      helpers: [
        'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 170,
        extra: 124,
        helpers: [
          'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'e1b3aaea0b6b5dba'
    },
    'logue/mix/pan': {
      first: 104,
      extra: 104,
      helpers: [],
      unwired: { first: 84, extra: 60, helpers: [] },
      snapshotHash: 'd139dc1b3b1c3b34'
    },
    'logue/mix/width': {
      first: 92,
      extra: 56,
      helpers: [],
      unwired: { first: 32, extra: 4, helpers: [] },
      snapshotHash: 'e3d3cef19609c42b'
    },
    'logue/logic/chance': {
      first: 192,
      extra: 136,
      helpers: [],
      unwired: { first: 116, extra: 72, helpers: [] },
      snapshotHash: 'efecc236e2563837'
    },
    'logue/logic/round-robin': {
      first: 104,
      extra: 72,
      helpers: [],
      unwired: { first: 52, extra: 0, helpers: [] },
      snapshotHash: '7338eb6e334fed60'
    }
  },
  'minilogue-xd:fx': {
    'logue/osc/sine': {
      first: 440,
      extra: 260,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 204, extra: 100, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'b34b1284af3c9ca7'
    },
    'logue/osc/saw': {
      first: 858,
      extra: 620,
      helpers: ['Fx::harmonic_ratio(float)', 'Fx::note_w0(float)'],
      unwired: { first: 280, extra: 156, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '689d43e99e06ce9c'
    },
    'logue/osc/square': {
      first: 460,
      extra: 252,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 164,
        extra: 80,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '9a189b5fd7ef929c'
    },
    'logue/osc/pulse': {
      first: 524,
      extra: 316,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 188,
        extra: 92,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '773b9bbd527f1576'
    },
    'logue/osc/triangle': {
      first: 360,
      extra: 208,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 104, extra: 76, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'c19162f9574d3fe7'
    },
    'logue/osc/additive': {
      first: 324,
      extra: 184,
      helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)'],
      unwired: {
        first: 100,
        extra: 64,
        helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)']
      },
      snapshotHash: '8ad6107dc41ce335'
    },
    'logue/osc/granular': {
      first: 1694,
      extra: 1576,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 1474, extra: 1332, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '287537a0ffee7fe9'
    },
    'logue/mix/mix2': {
      first: 28,
      extra: 20,
      helpers: [],
      unwired: { first: 32, extra: 4, helpers: [] },
      snapshotHash: '996f8fc72e564aa8'
    },
    'logue/math/multiply': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '422c16a247da8ec8'
    },
    'logue/mix/crossfader': {
      first: 212,
      extra: 140,
      helpers: [],
      unwired: { first: 212, extra: 128, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: 'ff48b03b50520cf3'
    },
    'logue/mix/stereo-mix2': {
      first: 28,
      extra: 20,
      helpers: [],
      unwired: { first: 32, extra: 4, helpers: [] },
      snapshotHash: 'a9fb88bd2914a2f3'
    },
    'logue/mix/stereo-crossfader': {
      first: 200,
      extra: 136,
      helpers: [],
      unwired: { first: 192, extra: 116, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: '779c8ef1206c74bd'
    },
    'logue/filter/lowpass-cheap': {
      first: 92,
      extra: 64,
      helpers: [],
      unwired: { first: 92, extra: 36, helpers: [] },
      snapshotHash: 'bfb55ed722e29c07'
    },
    'logue/filter/highpass-cheap': {
      first: 88,
      extra: 100,
      helpers: [],
      unwired: { first: 88, extra: 48, helpers: [] },
      snapshotHash: '4dc6fa6c0e39cc62'
    },
    'logue/gain/vca': {
      first: 4,
      extra: 8,
      helpers: [],
      unwired: { first: 20, extra: 0, helpers: [] },
      snapshotHash: '71e7c2874a2780a1'
    },
    'logue/env/ad': {
      first: 452,
      extra: 336,
      helpers: ['Fx::env_rate_from_percent(float)'],
      unwired: { first: 240, extra: 136, helpers: ['Fx::env_rate_from_percent(float)'] },
      snapshotHash: 'c384655566b26ffc'
    },
    'logue/env/adsr': {
      first: 332,
      extra: 204,
      helpers: ['Fx::adsr_rate(float, float)'],
      unwired: { first: 340, extra: 144, helpers: ['Fx::adsr_rate(float, float)'] },
      snapshotHash: 'abd7e5820bec87bc'
    },
    'logue/env/one-knob-adsr': {
      first: 512,
      extra: 320,
      helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)'],
      unwired: {
        first: 480,
        extra: 208,
        helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)']
      },
      snapshotHash: 'a39fd0de0ef1ae2a'
    },
    'logue/env/multistage': {
      first: 820,
      extra: 600,
      helpers: ['Fx::mseg_rate_from_percent(float)'],
      unwired: { first: 760, extra: 444, helpers: ['Fx::mseg_rate_from_percent(float)'] },
      snapshotHash: '8672d9936f6615d1'
    },
    'logue/lfo/sine-lfo': {
      first: 316,
      extra: 204,
      helpers: [],
      unwired: { first: 224, extra: 96, helpers: [] },
      snapshotHash: 'f091daaf62b2b62e'
    },
    'logue/lfo/triangle-lfo': {
      first: 236,
      extra: 188,
      helpers: [],
      unwired: { first: 140, extra: 76, helpers: [] },
      snapshotHash: '63720761f9fb074b'
    },
    'logue/lfo/square-lfo': {
      first: 224,
      extra: 152,
      helpers: [],
      unwired: { first: 124, extra: 72, helpers: [] },
      snapshotHash: '5bf8d1d088df38b0'
    },
    'logue/lfo/ramp-up': {
      first: 216,
      extra: 144,
      helpers: [],
      unwired: { first: 116, extra: 60, helpers: [] },
      snapshotHash: '657d45b8a4249ea5'
    },
    'logue/lfo/ramp-down': {
      first: 216,
      extra: 144,
      helpers: [],
      unwired: { first: 116, extra: 60, helpers: [] },
      snapshotHash: '93415749054fe77d'
    },
    'logue/lfo/fast-square': {
      first: 376,
      extra: 268,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 212, extra: 136, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '9023a42eadc26048'
    },
    'logue/lfo/random-steps': {
      first: 236,
      extra: 180,
      helpers: [],
      unwired: { first: 180, extra: 96, helpers: [] },
      snapshotHash: '001bad58241c33a2'
    },
    'logue/osc/noise': {
      first: 430,
      extra: 268,
      helpers: ['memset'],
      snapshotHash: 'c55e2984e99ac4a6'
    },
    'logue/osc/lfsr': {
      first: 525,
      extra: 364,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 477, extra: 284, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '7fbe59bdb96624a8'
    },
    'logue/shape/wavefolder': {
      first: 124,
      extra: 124,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: '6597b9a61c6b5800'
    },
    'logue/shape/soft-clip': {
      first: 92,
      extra: 92,
      helpers: [],
      unwired: { first: 44, extra: 16, helpers: [] },
      snapshotHash: '94bd46054709e8a4'
    },
    'logue/filter/comb': {
      first: 778,
      extra: 524,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 690, extra: 296, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '1fd2dcd5f18abf0e'
    },
    'logue/filter/string': {
      first: 582,
      extra: 484,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 418,
        extra: 272,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: 'd2fb4b7548c8393b'
    },
    'logue/osc/exciter': {
      first: 768,
      extra: 332,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 752, extra: 216, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '718efdc3d5a3a5fc'
    },
    'logue/osc/sync': {
      first: 316,
      extra: 240,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 264,
        extra: 128,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: 'de6812a7e1beb6e4'
    },
    'logue/osc/phase-dist': {
      first: 1548,
      extra: 1396,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 1124, extra: 996, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '447d0e2b472a3a55'
    },
    'logue/osc/bass-support': {
      first: 778,
      extra: 648,
      helpers: [
        'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Fx::note_w0(float)'
      ],
      unwired: {
        first: 646,
        extra: 488,
        helpers: [
          'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
          'Fx::note_w0(float)'
        ]
      },
      snapshotHash: 'da5adbf9ea4c7a45'
    },
    'logue/filter/svf': {
      first: 496,
      extra: 440,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 436, extra: 316, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'c762be0833d80be7'
    },
    'logue/filter/formant': {
      first: 302,
      extra: 244,
      helpers: [
        'Fx::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
      ],
      unwired: {
        first: 114,
        extra: 76,
        helpers: [
          'Fx::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
        ]
      },
      snapshotHash: '3064386816179abd'
    },
    'logue/sense/control': { first: 8, extra: 0, helpers: [], snapshotHash: '550ef812bd56decd' },
    'logue/util/constant': { first: 4, extra: 0, helpers: [], snapshotHash: 'f3edec1a842e0630' },
    'logue/util/unipolar-to-bipolar': {
      first: 48,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '7a44146c55ce7e26'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 36,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '123ed572e3392a1a'
    },
    'logue/math/negate': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: '80764f40f75f22b5'
    },
    'logue/math/one-minus': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f4a6e757bc9dd221'
    },
    'logue/math/curve': {
      first: 204,
      extra: 96,
      helpers: [],
      unwired: { first: 96, extra: 44, helpers: [] },
      snapshotHash: 'a6bc9c67c8ed7f33'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '1c1ccaf32ecaf295'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'd9827f1376cc7742'
    },
    'logue/math/scale': {
      first: 24,
      extra: 12,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: '33fcee3c312305e9'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '7ad50beda32b6968'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'df0bd7fdbe016146'
    },
    'logue/math/clamp': {
      first: 44,
      extra: 36,
      helpers: [],
      unwired: { first: 52, extra: 20, helpers: [] },
      snapshotHash: '0cdd97825f4434d9'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '6b592c1cff9c6d33'
    },
    'logue/logic/greater-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 32, extra: 4, helpers: [] },
      snapshotHash: 'c1bb3de72d4ece0e'
    },
    'logue/logic/less-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 28, extra: 8, helpers: [] },
      snapshotHash: '4357ab282a1ca032'
    },
    'logue/logic/equal': {
      first: 56,
      extra: 40,
      helpers: [],
      unwired: { first: 48, extra: 20, helpers: [] },
      snapshotHash: 'f164a8c5070849fd'
    },
    'logue/logic/and': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'f80de56b91f2e236'
    },
    'logue/logic/or': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '07e57403fbf2d1de'
    },
    'logue/logic/xor': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'c9d3d1a8aab33c41'
    },
    'logue/mux/mux2': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '43132007849f2d5e'
    },
    'logue/mux/mux4': {
      first: 24,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'e7cd1ca8a0645ebe'
    },
    'logue/mux/demux2': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'e60fc2ba0786e999'
    },
    'logue/logic/schmitt': {
      first: 76,
      extra: 52,
      helpers: [],
      unwired: { first: 76, extra: 32, helpers: [] },
      snapshotHash: '5affa568710e10ce'
    },
    'logue/logic/edge': {
      first: 64,
      extra: 32,
      helpers: [],
      unwired: { first: 44, extra: 12, helpers: [] },
      snapshotHash: 'c26efc0252e90a1d'
    },
    'logue/util/sample-hold': {
      first: 68,
      extra: 36,
      helpers: [],
      unwired: { first: 20, extra: 0, helpers: [] },
      snapshotHash: 'a29dc3d4ed9dc21e'
    },
    'logue/util/glide': {
      first: 140,
      extra: 72,
      helpers: [],
      unwired: { first: 148, extra: 52, helpers: [] },
      snapshotHash: '006a80d815345ce6'
    },
    'logue/util/slew': {
      first: 428,
      extra: 252,
      helpers: [],
      unwired: { first: 300, extra: 104, helpers: [] },
      snapshotHash: 'e3861ecccecfc253'
    },
    'logue/util/sample-delay': {
      first: 84,
      extra: 12,
      helpers: [],
      unwired: { first: 16, extra: 0, helpers: [] },
      snapshotHash: '90730202bac723c0'
    },
    'logue/util/delay': {
      first: 306,
      extra: 212,
      helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 186,
        extra: 108,
        helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: 'da512c286cda27d0'
    },
    'logue/util/long-delay': {
      first: 686,
      extra: 348,
      helpers: ['memset'],
      unwired: { first: 586, extra: 220, helpers: ['memset'] },
      snapshotHash: '8c91d8d963960391'
    },
    'logue/util/quantize': {
      first: 164,
      extra: 136,
      helpers: ['Fx::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 164,
        extra: 92,
        helpers: ['Fx::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'a721587239315819'
    },
    'logue/filter/allpass': {
      first: 358,
      extra: 184,
      helpers: ['memset'],
      unwired: { first: 298, extra: 160, helpers: ['memset'] },
      snapshotHash: 'f2a1656c07fb52d5'
    },
    'logue/env/follower': {
      first: 248,
      extra: 136,
      helpers: [],
      unwired: { first: 232, extra: 104, helpers: [] },
      snapshotHash: 'f7893e7c4cfddfe4'
    },
    'logue/sense/tempo': { first: 120, extra: 52, helpers: [], snapshotHash: '0410106efe6cce20' },
    'logue/filter/hilbert': {
      first: 378,
      extra: 276,
      helpers: ['memset'],
      unwired: { first: 382, extra: 240, helpers: ['memset'] },
      snapshotHash: 'f56fb7646016882f'
    },
    'logue/util/freq-shift': {
      first: 306,
      extra: 232,
      helpers: [
        'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 198,
        extra: 136,
        helpers: [
          'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'e1b3aaea0b6b5dba'
    },
    'logue/util/buffer': {
      first: 558,
      extra: 480,
      helpers: ['memset'],
      unwired: { first: 542, extra: 408, helpers: ['memset'] },
      snapshotHash: 'd11fef6b9acccce2'
    },
    'logue/util/buffer-tap': {
      first: 602,
      extra: 508,
      helpers: ['memset'],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: 'c9f54d6abbaf5c76'
    },
    'logue/util/grain': {
      first: 1006,
      extra: 896,
      helpers: ['memset'],
      unwired: { first: 106, extra: 0, helpers: ['memset'] },
      snapshotHash: '8c1b233d213f6d52'
    },
    'logue/util/reverse-tap': {
      first: 998,
      extra: 924,
      helpers: ['memset'],
      unwired: { first: 78, extra: 4, helpers: ['memset'] },
      snapshotHash: 'f0f4d753989ec3d8'
    },
    'logue/mix/pan': {
      first: 208,
      extra: 172,
      helpers: [],
      unwired: { first: 112, extra: 64, helpers: [] },
      snapshotHash: 'd139dc1b3b1c3b34'
    },
    'logue/mix/width': {
      first: 96,
      extra: 76,
      helpers: [],
      unwired: { first: 40, extra: 0, helpers: [] },
      snapshotHash: 'e3d3cef19609c42b'
    },
    'logue/logic/chance': {
      first: 232,
      extra: 140,
      helpers: [],
      unwired: { first: 140, extra: 76, helpers: [] },
      snapshotHash: 'efecc236e2563837'
    },
    'logue/logic/round-robin': {
      first: 124,
      extra: 76,
      helpers: [],
      unwired: { first: 76, extra: 0, helpers: [] },
      snapshotHash: '7338eb6e334fed60'
    }
  },
  'nts1mkii:osc': {
    'logue/osc/sine': {
      first: 671,
      extra: 338,
      helpers: [],
      unwired: { first: 431, extra: 226, helpers: [] },
      snapshotHash: 'd07a2e163e11d947'
    },
    'logue/osc/saw': {
      first: 785,
      extra: 435,
      helpers: [],
      unwired: { first: 453, extra: 287, helpers: [] },
      snapshotHash: '3a9ffe3e3d2124b3'
    },
    'logue/osc/square': {
      first: 673,
      extra: 346,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 433, extra: 254, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '4eac9e98563c8536'
    },
    'logue/osc/pulse': {
      first: 737,
      extra: 398,
      helpers: ['Osc::polyblep(float, float)'],
      unwired: { first: 453, extra: 274, helpers: ['Osc::polyblep(float, float)'] },
      snapshotHash: '90d83d49292969b8'
    },
    'logue/osc/triangle': {
      first: 549,
      extra: 266,
      helpers: [],
      unwired: { first: 313, extra: 158, helpers: [] },
      snapshotHash: '84542d8e80e4b65c'
    },
    'logue/osc/additive': {
      first: 626,
      extra: 210,
      helpers: ['Osc::additive_step(float, float, float)'],
      unwired: { first: 462, extra: 158, helpers: ['Osc::additive_step(float, float, float)'] },
      snapshotHash: '4663861446fc5f05'
    },
    'logue/osc/granular': {
      first: 2102,
      extra: 1528,
      helpers: ['Osc::note_w0(float)', 'memset'],
      unwired: { first: 1866, extra: 1276, helpers: ['Osc::note_w0(float)', 'memset'] },
      snapshotHash: '36a3f52804303136'
    },
    'logue/osc/sample': {
      first: 963,
      extra: 644,
      helpers: ['Osc::note_w0(float)'],
      unwired: { first: 879, extra: 540, helpers: ['Osc::note_w0(float)'] },
      snapshotHash: '8b8c9ba689f8af40'
    },
    'logue/osc/wavetable': {
      first: 1190,
      extra: 842,
      helpers: [],
      unwired: { first: 1018, extra: 778, helpers: [] },
      snapshotHash: '7b26d43d1b740a72'
    },
    'logue/mix/mix2': {
      first: 24,
      extra: 20,
      helpers: [],
      unwired: { first: 32, extra: 8, helpers: [] },
      snapshotHash: '2ac9302e900204a8'
    },
    'logue/math/multiply': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '0b26d1b6c51171af'
    },
    'logue/mix/crossfader': {
      first: 343,
      extra: 216,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 271, extra: 128, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: '089b0063484764a0'
    },
    'logue/mix/stereo-mix2': {
      first: 24,
      extra: 20,
      helpers: [],
      unwired: { first: 32, extra: 8, helpers: [] },
      snapshotHash: '8dc968f7e941e464'
    },
    'logue/mix/stereo-crossfader': {
      first: 331,
      extra: 204,
      helpers: ['Osc::xfade_settle(float*, float, float)'],
      unwired: { first: 259, extra: 116, helpers: ['Osc::xfade_settle(float*, float, float)'] },
      snapshotHash: '691c2bffa3b82a56'
    },
    'logue/filter/lowpass-cheap': {
      first: 72,
      extra: 68,
      helpers: [],
      unwired: { first: 72, extra: 48, helpers: [] },
      snapshotHash: '4e29af352381896e'
    },
    'logue/filter/highpass-cheap': {
      first: 72,
      extra: 76,
      helpers: [],
      unwired: { first: 72, extra: 56, helpers: [] },
      snapshotHash: '3505c088a06bee86'
    },
    'logue/gain/vca': {
      first: 8,
      extra: 0,
      helpers: [],
      unwired: { first: 20, extra: 0, helpers: [] },
      snapshotHash: '03c6cd9004bde762'
    },
    'logue/env/ad': {
      first: 425,
      extra: 300,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 301, extra: 148, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: 'ea61b20e11d84ffe'
    },
    'logue/env/ahd': {
      first: 437,
      extra: 293,
      helpers: ['Osc::env_rate_from_percent(float)'],
      unwired: { first: 313, extra: 128, helpers: ['Osc::env_rate_from_percent(float)'] },
      snapshotHash: '96dceec900792551'
    },
    'logue/env/adsr': {
      first: 405,
      extra: 291,
      helpers: ['Osc::adsr_rate(float, float)'],
      unwired: { first: 413, extra: 263, helpers: ['Osc::adsr_rate(float, float)'] },
      snapshotHash: '62fe233b7fc67d5c'
    },
    'logue/env/one-knob-adsr': {
      first: 701,
      extra: 460,
      helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)'],
      unwired: {
        first: 705,
        extra: 404,
        helpers: ['Osc::adsr_rate(float, float)', 'Osc::knob_env_value(float, int)']
      },
      snapshotHash: '9c5705d6ac6db998'
    },
    'logue/env/multistage': {
      first: 926,
      extra: 714,
      helpers: ['Osc::mseg_rate_from_percent(float)'],
      unwired: { first: 850, extra: 578, helpers: ['Osc::mseg_rate_from_percent(float)'] },
      snapshotHash: 'c717614593848225'
    },
    'logue/lfo/sine-lfo': {
      first: 350,
      extra: 208,
      helpers: [],
      unwired: { first: 250, extra: 124, helpers: [] },
      snapshotHash: 'd9221d9bc61e3c32'
    },
    'logue/lfo/triangle-lfo': {
      first: 228,
      extra: 156,
      helpers: [],
      unwired: { first: 132, extra: 72, helpers: [] },
      snapshotHash: 'c6429d93a678c350'
    },
    'logue/lfo/square-lfo': {
      first: 216,
      extra: 148,
      helpers: [],
      unwired: { first: 116, extra: 68, helpers: [] },
      snapshotHash: 'f8cf468759e87de9'
    },
    'logue/lfo/ramp-up': {
      first: 208,
      extra: 140,
      helpers: [],
      unwired: { first: 108, extra: 56, helpers: [] },
      snapshotHash: 'ced3469dbc75f86b'
    },
    'logue/lfo/ramp-down': {
      first: 208,
      extra: 140,
      helpers: [],
      unwired: { first: 108, extra: 56, helpers: [] },
      snapshotHash: '785b4d8a503639cd'
    },
    'logue/lfo/fast-square': {
      first: 553,
      extra: 346,
      helpers: [],
      unwired: { first: 401, extra: 230, helpers: [] },
      snapshotHash: '802700d4e0a165bb'
    },
    'logue/lfo/random-steps': {
      first: 216,
      extra: 148,
      helpers: [],
      unwired: { first: 160, extra: 92, helpers: [] },
      snapshotHash: '54ebeef1bdb03998'
    },
    'logue/osc/noise': {
      first: 439,
      extra: 330,
      helpers: ['memset'],
      snapshotHash: '7de83902830d40d1'
    },
    'logue/osc/lfsr': {
      first: 748,
      extra: 552,
      helpers: [],
      unwired: { first: 700, extra: 484, helpers: [] },
      snapshotHash: '77efd6de7c58ca1a'
    },
    'logue/shape/wavefolder': {
      first: 124,
      extra: 100,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: '3c64304026c12c68'
    },
    'logue/shape/soft-clip': {
      first: 92,
      extra: 68,
      helpers: [],
      unwired: { first: 44, extra: 16, helpers: [] },
      snapshotHash: '216989a0fb3b382f'
    },
    'logue/filter/comb': {
      first: 996,
      extra: 736,
      helpers: ['memset'],
      unwired: { first: 904, extra: 560, helpers: ['memset'] },
      snapshotHash: '57e9015d9f1c40fe'
    },
    'logue/filter/string': {
      first: 1085,
      extra: 752,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 917,
        extra: 518,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: 'f88b0f3adf944f68'
    },
    'logue/osc/exciter': {
      first: 1101,
      extra: 415,
      helpers: [],
      unwired: { first: 1065, extra: 343, helpers: [] },
      snapshotHash: '644ef3d8dff0b64d'
    },
    'logue/osc/sync': {
      first: 521,
      extra: 216,
      helpers: [
        'Osc::note_w0(float)',
        'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 469,
        extra: 132,
        helpers: [
          'Osc::note_w0(float)',
          'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: '1d1c1ce43766ec40'
    },
    'logue/osc/phase-dist': {
      first: 1567,
      extra: 1042,
      helpers: [],
      unwired: { first: 1783, extra: 910, helpers: [] },
      snapshotHash: '7e367a90928dd9f0'
    },
    'logue/osc/bass-support': {
      first: 1054,
      extra: 696,
      helpers: [
        'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Osc::note_w0(float)'
      ],
      unwired: {
        first: 1000,
        extra: 638,
        helpers: [
          'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)'
        ]
      },
      snapshotHash: '3ecec297631c48fa'
    },
    'logue/filter/svf': {
      first: 661,
      extra: 703,
      helpers: [],
      unwired: { first: 605, extra: 599, helpers: [] },
      snapshotHash: '6536ded8663fbbfe'
    },
    'logue/filter/formant': {
      first: 507,
      extra: 232,
      helpers: [
        'Osc::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
      ],
      unwired: {
        first: 343,
        extra: 64,
        helpers: [
          'Osc::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
        ]
      },
      snapshotHash: '65230083185e249c'
    },
    'logue/sense/pitch': { first: 0, extra: 0, helpers: [], snapshotHash: 'e86f9bdb5b25a186' },
    'logue/sense/control': { first: 12, extra: 0, helpers: [], snapshotHash: '0601f991f0cabfe7' },
    'logue/sense/shape': { first: 0, extra: 0, helpers: [], snapshotHash: '46e0474dc7468567' },
    'logue/sense/shape-2': { first: 0, extra: 0, helpers: [], snapshotHash: '64c0d75b574e1d04' },
    'logue/sense/gate': { first: 40, extra: 0, helpers: [], snapshotHash: '5b7aafa89eacc7f4' },
    'logue/sense/velocity': { first: 64, extra: 0, helpers: [], snapshotHash: '48e367520b125ed7' },
    'logue/util/constant': { first: 8, extra: 0, helpers: [], snapshotHash: '2f68421838833402' },
    'logue/util/unipolar-to-bipolar': {
      first: 52,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f2494343837c201f'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 44,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'bb1738541e78eeeb'
    },
    'logue/math/negate': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'da3d23ef4dc8bd10'
    },
    'logue/math/one-minus': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'b2ff1f5356954df7'
    },
    'logue/math/curve': {
      first: 188,
      extra: 181,
      helpers: [],
      unwired: { first: 96, extra: 137, helpers: [] },
      snapshotHash: 'ed3494b8b9f73650'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'd6383a2bddff31c9'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '918fbb911cef34bb'
    },
    'logue/math/scale': {
      first: 20,
      extra: 16,
      helpers: [],
      unwired: { first: 28, extra: 4, helpers: [] },
      snapshotHash: '7f1622cf03e56cc4'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '19ea78a55e2ace19'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '120d7299e59c6493'
    },
    'logue/math/clamp': {
      first: 48,
      extra: 36,
      helpers: [],
      unwired: { first: 56, extra: 24, helpers: [] },
      snapshotHash: '4d5747eb038a6557'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '311386b00707e5f3'
    },
    'logue/logic/greater-than': {
      first: 36,
      extra: 24,
      helpers: [],
      unwired: { first: 32, extra: 8, helpers: [] },
      snapshotHash: '8781970f0743cd8c'
    },
    'logue/logic/less-than': {
      first: 36,
      extra: 24,
      helpers: [],
      unwired: { first: 32, extra: 8, helpers: [] },
      snapshotHash: 'c6fa8901ca039b63'
    },
    'logue/logic/equal': {
      first: 56,
      extra: 40,
      helpers: [],
      unwired: { first: 52, extra: 24, helpers: [] },
      snapshotHash: '82393989846b664c'
    },
    'logue/logic/and': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '49482c0a15580834'
    },
    'logue/logic/or': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '7b83921269f92ec4'
    },
    'logue/logic/xor': {
      first: 8,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'aab77423e726dbff'
    },
    'logue/mux/mux2': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'a690e18ea8e50652'
    },
    'logue/mux/mux4': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '54c9d70a1f71bf2f'
    },
    'logue/mux/demux2': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '28008d86bbb48b0f'
    },
    'logue/logic/schmitt': {
      first: 60,
      extra: 56,
      helpers: [],
      unwired: { first: 60, extra: 44, helpers: [] },
      snapshotHash: 'c432dc8aa076ba4b'
    },
    'logue/logic/edge': {
      first: 56,
      extra: 28,
      helpers: [],
      unwired: { first: 36, extra: 12, helpers: [] },
      snapshotHash: '34ab1d63a921d3f9'
    },
    'logue/util/sample-hold': {
      first: 52,
      extra: 32,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'b950918e40dec78c'
    },
    'logue/util/glide': {
      first: 124,
      extra: 167,
      helpers: [],
      unwired: { first: 132, extra: 155, helpers: [] },
      snapshotHash: '7506a1ae4eb21ddf'
    },
    'logue/util/slew': {
      first: 344,
      extra: 377,
      helpers: [],
      unwired: { first: 256, extra: 281, helpers: [] },
      snapshotHash: 'bbf766ecc1632195'
    },
    'logue/util/sample-delay': {
      first: 76,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'a625e1ea19059647'
    },
    'logue/util/delay': {
      first: 424,
      extra: 180,
      helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 336,
        extra: 80,
        helpers: ['Osc::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: 'd0aa0f54bfd774b8'
    },
    'logue/util/quantize': {
      first: 319,
      extra: 184,
      helpers: ['Osc::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 319,
        extra: 168,
        helpers: ['Osc::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'ee2363ac72ce02b8'
    },
    'logue/env/follower': {
      first: 216,
      extra: 140,
      helpers: [],
      unwired: { first: 204, extra: 128, helpers: [] },
      snapshotHash: 'eca79cd82627972c'
    },
    'logue/filter/hilbert': {
      first: 391,
      extra: 272,
      helpers: ['memset'],
      unwired: { first: 399, extra: 260, helpers: ['memset'] },
      snapshotHash: '3ffe84d6a2d98867'
    },
    'logue/util/freq-shift': {
      first: 475,
      extra: 204,
      helpers: [
        'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 391,
        extra: 108,
        helpers: [
          'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'af1f86022bd303b9'
    },
    'logue/mix/pan': {
      first: 116,
      extra: 88,
      helpers: [],
      unwired: { first: 96, extra: 56, helpers: [] },
      snapshotHash: '62ccf9014c7ba69e'
    },
    'logue/mix/width': {
      first: 96,
      extra: 60,
      helpers: [],
      unwired: { first: 36, extra: 8, helpers: [] },
      snapshotHash: '2cffba2ea3591b93'
    },
    'logue/logic/chance': {
      first: 196,
      extra: 128,
      helpers: [],
      unwired: { first: 120, extra: 76, helpers: [] },
      snapshotHash: '2858ec9dd42d3f1d'
    },
    'logue/logic/round-robin': {
      first: 112,
      extra: 76,
      helpers: [],
      unwired: { first: 60, extra: 0, helpers: [] },
      snapshotHash: '6d2369b06f37d67d'
    }
  },
  'nts1mkii:fx': {
    'logue/osc/sine': {
      first: 559,
      extra: 337,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 327, extra: 116, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: 'd07a2e163e11d947'
    },
    'logue/osc/saw': {
      first: 994,
      extra: 692,
      helpers: ['Fx::harmonic_ratio(float)', 'Fx::note_w0(float)'],
      unwired: { first: 345, extra: 184, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '3a9ffe3e3d2124b3'
    },
    'logue/osc/square': {
      first: 588,
      extra: 404,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 312,
        extra: 155,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '4eac9e98563c8536'
    },
    'logue/osc/pulse': {
      first: 652,
      extra: 472,
      helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)'],
      unwired: {
        first: 336,
        extra: 171,
        helpers: ['Fx::note_w0(float)', 'Fx::polyblep(float, float)']
      },
      snapshotHash: '90d83d49292969b8'
    },
    'logue/osc/triangle': {
      first: 417,
      extra: 285,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 185, extra: 72, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '84542d8e80e4b65c'
    },
    'logue/osc/additive': {
      first: 540,
      extra: 257,
      helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)'],
      unwired: {
        first: 336,
        extra: 64,
        helpers: ['Fx::additive_step(float, float, float)', 'Fx::note_w0(float)']
      },
      snapshotHash: '4663861446fc5f05'
    },
    'logue/osc/granular': {
      first: 2181,
      extra: 1604,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 1953, extra: 1340, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '36a3f52804303136'
    },
    'logue/mix/mix2': {
      first: 24,
      extra: 20,
      helpers: [],
      unwired: { first: 28, extra: 0, helpers: [] },
      snapshotHash: '2ac9302e900204a8'
    },
    'logue/math/multiply': {
      first: 0,
      extra: 4,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '0b26d1b6c51171af'
    },
    'logue/mix/crossfader': {
      first: 204,
      extra: 144,
      helpers: [],
      unwired: { first: 298, extra: 124, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: '089b0063484764a0'
    },
    'logue/mix/stereo-mix2': {
      first: 24,
      extra: 20,
      helpers: [],
      unwired: { first: 28, extra: 0, helpers: [] },
      snapshotHash: '8dc968f7e941e464'
    },
    'logue/mix/stereo-crossfader': {
      first: 192,
      extra: 140,
      helpers: [],
      unwired: { first: 286, extra: 112, helpers: ['Fx::xfade_settle(float*, float, float)'] },
      snapshotHash: '691c2bffa3b82a56'
    },
    'logue/filter/lowpass-cheap': {
      first: 92,
      extra: 72,
      helpers: [],
      unwired: { first: 92, extra: 40, helpers: [] },
      snapshotHash: '4e29af352381896e'
    },
    'logue/filter/highpass-cheap': {
      first: 88,
      extra: 88,
      helpers: [],
      unwired: { first: 88, extra: 52, helpers: [] },
      snapshotHash: '3505c088a06bee86'
    },
    'logue/gain/vca': {
      first: 8,
      extra: 4,
      helpers: [],
      unwired: { first: 24, extra: 0, helpers: [] },
      snapshotHash: '03c6cd9004bde762'
    },
    'logue/env/ad': {
      first: 564,
      extra: 415,
      helpers: ['Fx::env_rate_from_percent(float)'],
      unwired: { first: 348, extra: 152, helpers: ['Fx::env_rate_from_percent(float)'] },
      snapshotHash: 'ea61b20e11d84ffe'
    },
    'logue/env/adsr': {
      first: 428,
      extra: 290,
      helpers: ['Fx::adsr_rate(float, float)'],
      unwired: { first: 432, extra: 250, helpers: ['Fx::adsr_rate(float, float)'] },
      snapshotHash: '62fe233b7fc67d5c'
    },
    'logue/env/one-knob-adsr': {
      first: 762,
      extra: 482,
      helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)'],
      unwired: {
        first: 730,
        extra: 394,
        helpers: ['Fx::adsr_rate(float, float)', 'Fx::knob_env_value(float, int)']
      },
      snapshotHash: '9c5705d6ac6db998'
    },
    'logue/env/multistage': {
      first: 941,
      extra: 697,
      helpers: ['Fx::mseg_rate_from_percent(float)'],
      unwired: { first: 877, extra: 561, helpers: ['Fx::mseg_rate_from_percent(float)'] },
      snapshotHash: 'c717614593848225'
    },
    'logue/lfo/sine-lfo': {
      first: 366,
      extra: 216,
      helpers: [],
      unwired: { first: 270, extra: 128, helpers: [] },
      snapshotHash: 'd9221d9bc61e3c32'
    },
    'logue/lfo/triangle-lfo': {
      first: 244,
      extra: 172,
      helpers: [],
      unwired: { first: 148, extra: 80, helpers: [] },
      snapshotHash: 'c6429d93a678c350'
    },
    'logue/lfo/square-lfo': {
      first: 228,
      extra: 160,
      helpers: [],
      unwired: { first: 132, extra: 76, helpers: [] },
      snapshotHash: 'f8cf468759e87de9'
    },
    'logue/lfo/ramp-up': {
      first: 224,
      extra: 148,
      helpers: [],
      unwired: { first: 124, extra: 64, helpers: [] },
      snapshotHash: 'ced3469dbc75f86b'
    },
    'logue/lfo/ramp-down': {
      first: 224,
      extra: 148,
      helpers: [],
      unwired: { first: 124, extra: 64, helpers: [] },
      snapshotHash: '785b4d8a503639cd'
    },
    'logue/lfo/fast-square': {
      first: 445,
      extra: 264,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 301, extra: 128, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '802700d4e0a165bb'
    },
    'logue/lfo/random-steps': {
      first: 252,
      extra: 184,
      helpers: [],
      unwired: { first: 200, extra: 112, helpers: [] },
      snapshotHash: '54ebeef1bdb03998'
    },
    'logue/osc/noise': {
      first: 499,
      extra: 373,
      helpers: ['memset'],
      snapshotHash: '7de83902830d40d1'
    },
    'logue/osc/lfsr': {
      first: 675,
      extra: 437,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 631, extra: 361, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '77efd6de7c58ca1a'
    },
    'logue/shape/wavefolder': {
      first: 124,
      extra: 104,
      helpers: [],
      unwired: { first: 36, extra: 0, helpers: [] },
      snapshotHash: '3c64304026c12c68'
    },
    'logue/shape/soft-clip': {
      first: 92,
      extra: 72,
      helpers: [],
      unwired: { first: 48, extra: 4, helpers: [] },
      snapshotHash: '216989a0fb3b382f'
    },
    'logue/filter/comb': {
      first: 936,
      extra: 684,
      helpers: ['Fx::note_w0(float)', 'memset'],
      unwired: { first: 848, extra: 488, helpers: ['Fx::note_w0(float)', 'memset'] },
      snapshotHash: '57e9015d9f1c40fe'
    },
    'logue/filter/string': {
      first: 838,
      extra: 569,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
        'memset'
      ],
      unwired: {
        first: 670,
        extra: 320,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)',
          'memset'
        ]
      },
      snapshotHash: 'f88b0f3adf944f68'
    },
    'logue/osc/exciter': {
      first: 893,
      extra: 402,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 865, extra: 310, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '644ef3d8dff0b64d'
    },
    'logue/osc/sync': {
      first: 510,
      extra: 264,
      helpers: [
        'Fx::note_w0(float)',
        'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
      ],
      unwired: {
        first: 454,
        extra: 176,
        helpers: [
          'Fx::note_w0(float)',
          'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)'
        ]
      },
      snapshotHash: '1d1c1ce43766ec40'
    },
    'logue/osc/phase-dist': {
      first: 1675,
      extra: 1424,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 1503, extra: 1028, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '7e367a90928dd9f0'
    },
    'logue/osc/bass-support': {
      first: 1007,
      extra: 656,
      helpers: [
        'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
        'Fx::note_w0(float)'
      ],
      unwired: {
        first: 871,
        extra: 516,
        helpers: [
          'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)',
          'Fx::note_w0(float)'
        ]
      },
      snapshotHash: '3ecec297631c48fa'
    },
    'logue/filter/svf': {
      first: 565,
      extra: 599,
      helpers: ['Fx::note_w0(float)'],
      unwired: { first: 501, extra: 495, helpers: ['Fx::note_w0(float)'] },
      snapshotHash: '6536ded8663fbbfe'
    },
    'logue/filter/formant': {
      first: 514,
      extra: 248,
      helpers: [
        'Fx::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
      ],
      unwired: {
        first: 350,
        extra: 64,
        helpers: [
          'Fx::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)'
        ]
      },
      snapshotHash: '65230083185e249c'
    },
    'logue/sense/control': { first: 8, extra: 0, helpers: [], snapshotHash: '0601f991f0cabfe7' },
    'logue/util/constant': { first: 8, extra: 0, helpers: [], snapshotHash: '2f68421838833402' },
    'logue/util/unipolar-to-bipolar': {
      first: 48,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'f2494343837c201f'
    },
    'logue/util/bipolar-to-unipolar': {
      first: 36,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'bb1738541e78eeeb'
    },
    'logue/math/negate': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'da3d23ef4dc8bd10'
    },
    'logue/math/one-minus': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 0, extra: 0, helpers: [] },
      snapshotHash: 'b2ff1f5356954df7'
    },
    'logue/math/curve': {
      first: 188,
      extra: 176,
      helpers: [],
      unwired: { first: 100, extra: 124, helpers: [] },
      snapshotHash: 'ed3494b8b9f73650'
    },
    'logue/math/add': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'd6383a2bddff31c9'
    },
    'logue/math/subtract': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '918fbb911cef34bb'
    },
    'logue/math/scale': {
      first: 24,
      extra: 16,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: '7f1622cf03e56cc4'
    },
    'logue/math/min': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '19ea78a55e2ace19'
    },
    'logue/math/max': {
      first: 0,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '120d7299e59c6493'
    },
    'logue/math/clamp': {
      first: 48,
      extra: 36,
      helpers: [],
      unwired: { first: 56, extra: 16, helpers: [] },
      snapshotHash: '4d5747eb038a6557'
    },
    'logue/math/abs': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '311386b00707e5f3'
    },
    'logue/logic/greater-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 36, extra: 0, helpers: [] },
      snapshotHash: '8781970f0743cd8c'
    },
    'logue/logic/less-than': {
      first: 36,
      extra: 28,
      helpers: [],
      unwired: { first: 32, extra: 0, helpers: [] },
      snapshotHash: 'c6fa8901ca039b63'
    },
    'logue/logic/equal': {
      first: 56,
      extra: 44,
      helpers: [],
      unwired: { first: 52, extra: 16, helpers: [] },
      snapshotHash: '82393989846b664c'
    },
    'logue/logic/and': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '49482c0a15580834'
    },
    'logue/logic/or': {
      first: 24,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: '7b83921269f92ec4'
    },
    'logue/logic/xor': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 4, extra: 0, helpers: [] },
      snapshotHash: 'aab77423e726dbff'
    },
    'logue/mux/mux2': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: 'a690e18ea8e50652'
    },
    'logue/mux/mux4': {
      first: 4,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '54c9d70a1f71bf2f'
    },
    'logue/mux/demux2': {
      first: 28,
      extra: 0,
      helpers: [],
      unwired: { first: 8, extra: 0, helpers: [] },
      snapshotHash: '28008d86bbb48b0f'
    },
    'logue/logic/schmitt': {
      first: 76,
      extra: 60,
      helpers: [],
      unwired: { first: 76, extra: 40, helpers: [] },
      snapshotHash: 'c432dc8aa076ba4b'
    },
    'logue/logic/edge': {
      first: 72,
      extra: 28,
      helpers: [],
      unwired: { first: 48, extra: 12, helpers: [] },
      snapshotHash: '34ab1d63a921d3f9'
    },
    'logue/util/sample-hold': {
      first: 76,
      extra: 36,
      helpers: [],
      unwired: { first: 28, extra: 0, helpers: [] },
      snapshotHash: 'b950918e40dec78c'
    },
    'logue/util/glide': {
      first: 140,
      extra: 178,
      helpers: [],
      unwired: { first: 148, extra: 150, helpers: [] },
      snapshotHash: '7506a1ae4eb21ddf'
    },
    'logue/util/slew': {
      first: 444,
      extra: 407,
      helpers: [],
      unwired: { first: 312, extra: 279, helpers: [] },
      snapshotHash: 'bbf766ecc1632195'
    },
    'logue/util/sample-delay': {
      first: 88,
      extra: 12,
      helpers: [],
      unwired: { first: 24, extra: 0, helpers: [] },
      snapshotHash: 'a625e1ea19059647'
    },
    'logue/util/delay': {
      first: 479,
      extra: 204,
      helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset'],
      unwired: {
        first: 387,
        extra: 92,
        helpers: ['Fx::delay_step(short*, int*, float, float, float, float)', 'memset']
      },
      snapshotHash: 'd0aa0f54bfd774b8'
    },
    'logue/util/long-delay': {
      first: 867,
      extra: 453,
      helpers: ['memset'],
      unwired: { first: 767, extra: 353, helpers: ['memset'] },
      snapshotHash: '71982873d100822a'
    },
    'logue/util/quantize': {
      first: 353,
      extra: 199,
      helpers: ['Fx::quantize_step(float, int, float*, float*)'],
      unwired: {
        first: 353,
        extra: 163,
        helpers: ['Fx::quantize_step(float, int, float*, float*)']
      },
      snapshotHash: 'ee2363ac72ce02b8'
    },
    'logue/filter/allpass': {
      first: 455,
      extra: 269,
      helpers: ['memset'],
      unwired: { first: 391, extra: 176, helpers: ['memset'] },
      snapshotHash: 'b519e3644b9984fd'
    },
    'logue/env/follower': {
      first: 236,
      extra: 136,
      helpers: [],
      unwired: { first: 220, extra: 124, helpers: [] },
      snapshotHash: 'eca79cd82627972c'
    },
    'logue/sense/tempo': { first: 209, extra: 56, helpers: [], snapshotHash: 'e88ae0f82b4156d9' },
    'logue/filter/hilbert': {
      first: 451,
      extra: 288,
      helpers: ['memset'],
      unwired: { first: 455, extra: 268, helpers: ['memset'] },
      snapshotHash: '3ffe84d6a2d98867'
    },
    'logue/util/freq-shift': {
      first: 550,
      extra: 220,
      helpers: [
        'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
        'memset'
      ],
      unwired: {
        first: 462,
        extra: 124,
        helpers: [
          'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)',
          'memset'
        ]
      },
      snapshotHash: 'af1f86022bd303b9'
    },
    'logue/util/buffer': {
      first: 647,
      extra: 484,
      helpers: ['memset'],
      unwired: { first: 631, extra: 436, helpers: ['memset'] },
      snapshotHash: '3872c18be0a5e7da'
    },
    'logue/util/buffer-tap': {
      first: 691,
      extra: 516,
      helpers: ['memset'],
      unwired: { first: 12, extra: 0, helpers: [] },
      snapshotHash: '0f912bec0e5e8559'
    },
    'logue/util/grain': {
      first: 1099,
      extra: 904,
      helpers: ['memset'],
      unwired: { first: 223, extra: 0, helpers: ['memset'] },
      snapshotHash: '1e061b197f88e3c0'
    },
    'logue/util/reverse-tap': {
      first: 1087,
      extra: 932,
      helpers: ['memset'],
      unwired: { first: 179, extra: 12, helpers: ['memset'] },
      snapshotHash: '8cabc0a2bc1490e9'
    },
    'logue/mix/pan': {
      first: 240,
      extra: 164,
      helpers: [],
      unwired: { first: 152, extra: 60, helpers: [] },
      snapshotHash: '62ccf9014c7ba69e'
    },
    'logue/mix/width': {
      first: 92,
      extra: 64,
      helpers: [],
      unwired: { first: 40, extra: 0, helpers: [] },
      snapshotHash: '2cffba2ea3591b93'
    },
    'logue/logic/chance': {
      first: 224,
      extra: 168,
      helpers: [],
      unwired: { first: 152, extra: 100, helpers: [] },
      snapshotHash: '2858ec9dd42d3f1d'
    },
    'logue/logic/round-robin': {
      first: 136,
      extra: 84,
      helpers: [],
      unwired: { first: 88, extra: 0, helpers: [] },
      snapshotHash: '6d2369b06f37d67d'
    }
  }
}

/** The unit shell each context was measured in (`shellHash`, measureCodeSizes.ts). */
export const CODE_SHELL_HASH: Record<CodeSizeContext, string> = {
  'minilogue-xd:osc': 'f3edec1a842e0630',
  'minilogue-xd:fx': '323c55ee855d1752',
  'nts1mkii:osc': '2f68421838833402',
  'nts1mkii:fx': '91502563103d0945'
}

/** Bytes of each out-of-line function (demangled name) per context. */
export const CODE_HELPER_BYTES: Record<CodeSizeContext, Record<string, number>> = {
  'minilogue-xd:osc': {
    memset: 134,
    'Osc::additive_step(float, float, float)': 480,
    'Osc::adsr_rate(float, float)': 72,
    'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1482,
    'Osc::delay_step(short*, int*, float, float, float, float)': 328,
    'Osc::env_rate_from_percent(float)': 76,
    'Osc::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)': 1192,
    'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 728,
    'Osc::knob_env_value(float, int)': 172,
    'Osc::mseg_rate_from_percent(float)': 68,
    'Osc::note_w0(float)': 164,
    'Osc::polyblep(float, float)': 96,
    'Osc::quantize_step(float, int, float*, float*)': 328,
    'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)': 848,
    'Osc::xfade_settle(float*, float, float)': 172
  },
  'minilogue-xd:fx': {
    'Fx::additive_step(float, float, float)': 480,
    'Fx::adsr_rate(float, float)': 72,
    'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1482,
    'Fx::delay_step(short*, int*, float, float, float, float)': 328,
    'Fx::env_rate_from_percent(float)': 76,
    'Fx::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)': 1470,
    'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 728,
    'Fx::harmonic_ratio(float)': 74,
    'Fx::knob_env_value(float, int)': 172,
    'Fx::mseg_rate_from_percent(float)': 68,
    'Fx::note_w0(float)': 308,
    'Fx::polyblep(float, float)': 96,
    'Fx::quantize_step(float, int, float*, float*)': 328,
    'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)': 848,
    'Fx::xfade_settle(float*, float, float)': 172,
    memset: 134
  },
  'nts1mkii:osc': {
    memset: 16,
    'Osc::additive_step(float, float, float)': 488,
    'Osc::adsr_rate(float, float)': 72,
    'Osc::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1498,
    'Osc::delay_step(short*, int*, float, float, float, float)': 328,
    'Osc::env_rate_from_percent(float)': 76,
    'Osc::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)': 1216,
    'Osc::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 744,
    'Osc::knob_env_value(float, int)': 180,
    'Osc::mseg_rate_from_percent(float)': 68,
    'Osc::note_w0(float)': 176,
    'Osc::polyblep(float, float)': 96,
    'Osc::quantize_step(float, int, float*, float*)': 328,
    'Osc::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Osc::sync_osc_step(float*, float*, float*, float, float, int, float)': 864,
    'Osc::xfade_settle(float*, float, float)': 172
  },
  'nts1mkii:fx': {
    'Fx::additive_step(float, float, float)': 488,
    'Fx::adsr_rate(float, float)': 72,
    'Fx::bass_support_step(float*, float, float, float, float, float, float, float, float, float)': 1498,
    'Fx::delay_step(short*, int*, float, float, float, float)': 328,
    'Fx::env_rate_from_percent(float)': 76,
    'Fx::formant_step(float*, float*, float*, float*, float*, float*, float, float, float, float, float)': 1490,
    'Fx::freq_shift_step(float*, int*, float*, float*, float*, float, float, float, float, float*)': 744,
    'Fx::harmonic_ratio(float)': 76,
    'Fx::knob_env_value(float, int)': 180,
    'Fx::mseg_rate_from_percent(float)': 68,
    'Fx::note_w0(float)': 308,
    'Fx::polyblep(float, float)': 96,
    'Fx::quantize_step(float, int, float*, float*)': 328,
    'Fx::string_step(float*, int*, float*, float*, float*, float*, float, float, float, float, float)': 524,
    'Fx::sync_osc_step(float*, float*, float*, float, float, int, float)': 864,
    'Fx::xfade_settle(float*, float, float)': 172,
    memset: 16
  }
}
