// GENERATED by scripts/measureCpuCosts.ts -- do not edit by hand; re-run it instead.
// Emulator estimates (scripts/emulateXdCycles.py) of minilogue xd cycles per voice-sample, on the
// emulator's own scale -- not hardware measurements. See estimateOscCpuCost.ts.

/** The fixed per-unit overhead: a unit that's just one util/constant. */
export const CPU_COST_BASELINE_CYCLES = 19

/**
 * Cycles per voice-sample above the baseline, per primitive (xd only), per measured variant:
 * `base` (audio inputs wired, control inputs free), `control` (every inlet wired), `<CHECKBOX>`
 * and `<CHECKBOX>+control` (that checkbox flipped); `heavy-*` are extra worst-case settings.
 * `worst` is the largest of them.
 */
export const CPU_COST_TABLE: Record<
  string,
  { variants: Record<string, number>; worst: number; snapshotHash: string }
> = {
  'logue/env/ad': {
    variants: { base: 37, control: 39, EXP: 35, 'EXP+control': 37 },
    worst: 39,
    snapshotHash: 'c384655566b26ffc'
  },
  'logue/env/adsr': {
    variants: { base: 46, control: 38 },
    worst: 46,
    snapshotHash: 'abd7e5820bec87bc'
  },
  'logue/env/ahd': {
    variants: { base: 24, control: 26 },
    worst: 26,
    snapshotHash: 'e0f896dd954801b1'
  },
  'logue/env/follower': { variants: { base: 20 }, worst: 20, snapshotHash: 'f7893e7c4cfddfe4' },
  'logue/env/multistage': {
    variants: { base: 123, control: 47, 'heavy-cycle': 113 },
    worst: 123,
    snapshotHash: '8672d9936f6615d1'
  },
  'logue/env/one-knob-adsr': {
    variants: { base: 51, control: 42, 'heavy-moving-shape': 131 },
    worst: 131,
    snapshotHash: 'a39fd0de0ef1ae2a'
  },
  'logue/filter/comb': {
    variants: { base: 58, control: 59, TRACK: 59, 'TRACK+control': 59 },
    worst: 59,
    snapshotHash: '1fd2dcd5f18abf0e'
  },
  'logue/filter/formant': {
    variants: { base: 491, control: 543 },
    worst: 543,
    snapshotHash: '3064386816179abd'
  },
  'logue/filter/highpass-cheap': {
    variants: { base: 16, control: 16 },
    worst: 16,
    snapshotHash: '4dc6fa6c0e39cc62'
  },
  'logue/filter/hilbert': { variants: { base: 103 }, worst: 103, snapshotHash: 'f56fb7646016882f' },
  'logue/filter/ladder': {
    variants: {
      base: 118,
      control: 119,
      TRACK: 118,
      'TRACK+control': 119,
      'heavy-moving-cutoff': 244
    },
    worst: 244,
    snapshotHash: '14f53da66bd476e6'
  },
  'logue/filter/lowpass-cheap': {
    variants: { base: 15, control: 16 },
    worst: 16,
    snapshotHash: 'bfb55ed722e29c07'
  },
  'logue/filter/string': {
    variants: { base: 367, control: 392 },
    worst: 392,
    snapshotHash: 'd2fb4b7548c8393b'
  },
  'logue/filter/svf': {
    variants: { base: 45, control: 45, TRACK: 47, 'TRACK+control': 47 },
    worst: 47,
    snapshotHash: 'c762be0833d80be7'
  },
  'logue/gain/vca': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: '71e7c2874a2780a1'
  },
  'logue/lfo/fast-square': {
    variants: { base: 11, control: 28, TRACK: 11, 'TRACK+control': 28 },
    worst: 28,
    snapshotHash: '9023a42eadc26048'
  },
  'logue/lfo/ramp-down': {
    variants: { base: 15, control: 22 },
    worst: 22,
    snapshotHash: '93415749054fe77d'
  },
  'logue/lfo/ramp-up': {
    variants: { base: 15, control: 22 },
    worst: 22,
    snapshotHash: '657d45b8a4249ea5'
  },
  'logue/lfo/random-steps': {
    variants: { base: 8, control: 17 },
    worst: 17,
    snapshotHash: '001bad58241c33a2'
  },
  'logue/lfo/sine-lfo': {
    variants: { base: 36, control: 42 },
    worst: 42,
    snapshotHash: 'f091daaf62b2b62e'
  },
  'logue/lfo/square-lfo': {
    variants: { base: 9, control: 16 },
    worst: 16,
    snapshotHash: '5bf8d1d088df38b0'
  },
  'logue/lfo/triangle-lfo': {
    variants: { base: 16, control: 23 },
    worst: 23,
    snapshotHash: '63720761f9fb074b'
  },
  'logue/logic/and': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: 'f80de56b91f2e236'
  },
  'logue/logic/chance': {
    variants: { base: 10, control: 22 },
    worst: 22,
    snapshotHash: 'efecc236e2563837'
  },
  'logue/logic/edge': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: 'c26efc0252e90a1d'
  },
  'logue/logic/equal': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: 'f164a8c5070849fd'
  },
  'logue/logic/greater-than': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: 'c1bb3de72d4ece0e'
  },
  'logue/logic/less-than': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: '4357ab282a1ca032'
  },
  'logue/logic/or': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: '07e57403fbf2d1de'
  },
  'logue/logic/round-robin': {
    variants: { base: 0, control: 13 },
    worst: 13,
    snapshotHash: '7338eb6e334fed60'
  },
  'logue/logic/schmitt': {
    variants: { base: 15, control: 8 },
    worst: 15,
    snapshotHash: '5affa568710e10ce'
  },
  'logue/logic/xor': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: 'c9d3d1a8aab33c41'
  },
  'logue/math/abs': { variants: { base: 0 }, worst: 0, snapshotHash: '6b592c1cff9c6d33' },
  'logue/math/add': { variants: { base: 0 }, worst: 0, snapshotHash: '1c1ccaf32ecaf295' },
  'logue/math/clamp': { variants: { base: 0 }, worst: 0, snapshotHash: '0cdd97825f4434d9' },
  'logue/math/curve': {
    variants: { base: 1, control: 1 },
    worst: 1,
    snapshotHash: 'a6bc9c67c8ed7f33'
  },
  'logue/math/max': { variants: { base: 0 }, worst: 0, snapshotHash: 'df0bd7fdbe016146' },
  'logue/math/min': { variants: { base: 0 }, worst: 0, snapshotHash: '7ad50beda32b6968' },
  'logue/math/multiply': { variants: { base: 0 }, worst: 0, snapshotHash: '422c16a247da8ec8' },
  'logue/math/negate': { variants: { base: 0 }, worst: 0, snapshotHash: '80764f40f75f22b5' },
  'logue/math/one-minus': { variants: { base: 0 }, worst: 0, snapshotHash: 'f4a6e757bc9dd221' },
  'logue/math/scale': { variants: { base: 0 }, worst: 0, snapshotHash: '33fcee3c312305e9' },
  'logue/math/subtract': { variants: { base: 0 }, worst: 0, snapshotHash: 'd9827f1376cc7742' },
  'logue/mix/crossfader': {
    variants: { base: 16, control: 16 },
    worst: 16,
    snapshotHash: 'ff48b03b50520cf3'
  },
  'logue/mix/mix2': { variants: { base: 0 }, worst: 0, snapshotHash: '996f8fc72e564aa8' },
  'logue/mix/pan': {
    variants: { base: 4, control: 4 },
    worst: 4,
    snapshotHash: 'd139dc1b3b1c3b34'
  },
  'logue/mix/pan-mix2': {
    variants: { base: 4, control: 4 },
    worst: 4,
    snapshotHash: '6464e3e0e076302a'
  },
  'logue/mix/stereo-crossfader': {
    variants: { base: 15, control: 15 },
    worst: 15,
    snapshotHash: '779c8ef1206c74bd'
  },
  'logue/mix/stereo-mix2': { variants: { base: 0 }, worst: 0, snapshotHash: 'a9fb88bd2914a2f3' },
  'logue/mix/width': {
    variants: { base: 6, control: 17 },
    worst: 17,
    snapshotHash: 'e3d3cef19609c42b'
  },
  'logue/mux/demux2': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: 'e60fc2ba0786e999'
  },
  'logue/mux/mux2': {
    variants: { base: 0, control: 0 },
    worst: 0,
    snapshotHash: '43132007849f2d5e'
  },
  'logue/mux/mux4': {
    variants: { base: 15, control: 29 },
    worst: 29,
    snapshotHash: 'e7cd1ca8a0645ebe'
  },
  'logue/osc/additive': {
    variants: { base: 178, control: 176 },
    worst: 178,
    snapshotHash: '8ad6107dc41ce335'
  },
  'logue/osc/bass-support': {
    variants: { base: 265, control: 392, RETRIG: 265, 'RETRIG+control': 392 },
    worst: 392,
    snapshotHash: 'da5adbf9ea4c7a45'
  },
  'logue/osc/exciter': {
    variants: { base: 192, control: 196 },
    worst: 196,
    snapshotHash: '718efdc3d5a3a5fc'
  },
  'logue/osc/granular': {
    variants: {
      base: 244,
      control: 335,
      SYNC: 234,
      'SYNC+control': 317,
      'heavy-size-window-100': 474,
      'heavy-sync-off-density-100': 343
    },
    worst: 474,
    snapshotHash: '287537a0ffee7fe9'
  },
  'logue/osc/lfsr': {
    variants: {
      base: 30,
      control: 31,
      TRACK: 28,
      'TRACK+control': 30,
      'heavy-short': 18,
      'heavy-short-control': 18
    },
    worst: 31,
    snapshotHash: '7fbe59bdb96624a8'
  },
  'logue/osc/noise': {
    variants: { base: 10, 'heavy-pink': 35, 'heavy-brown': 28, 'heavy-violet': 28 },
    worst: 35,
    snapshotHash: 'c55e2984e99ac4a6'
  },
  'logue/osc/phase-dist': {
    variants: {
      base: 85,
      control: 99,
      'heavy-reso': 97,
      'heavy-wave2': 101,
      'heavy-moving-dcw': 285
    },
    worst: 285,
    snapshotHash: '447d0e2b472a3a55'
  },
  'logue/osc/pulse': {
    variants: { base: 97, control: 124 },
    worst: 124,
    snapshotHash: '773b9bbd527f1576'
  },
  'logue/osc/sample': {
    variants: {
      base: 88,
      control: 95,
      REVERSE: 95,
      'REVERSE+control': 102,
      TRACK: 88,
      'TRACK+control': 95,
      'heavy-pingpong-reverse': 100
    },
    worst: 102,
    snapshotHash: '7cb41406b040b044'
  },
  'logue/osc/saw': {
    variants: { base: 86, control: 99, TZFM: 76, 'TZFM+control': 94 },
    worst: 99,
    snapshotHash: '689d43e99e06ce9c'
  },
  'logue/osc/sine': {
    variants: { base: 50, control: 61 },
    worst: 61,
    snapshotHash: 'b34b1284af3c9ca7'
  },
  'logue/osc/square': {
    variants: { base: 100, control: 114 },
    worst: 114,
    snapshotHash: '9a189b5fd7ef929c'
  },
  'logue/osc/sync': {
    variants: { base: 108, control: 112 },
    worst: 112,
    snapshotHash: 'de6812a7e1beb6e4'
  },
  'logue/osc/triangle': {
    variants: { base: 29, control: 43 },
    worst: 43,
    snapshotHash: 'c19162f9574d3fe7'
  },
  'logue/osc/wavetable': {
    variants: { base: 146, control: 149, 'heavy-moving-position': 208 },
    worst: 208,
    snapshotHash: 'f92185a8a2498df5'
  },
  'logue/sense/control': { variants: { base: 0 }, worst: 0, snapshotHash: '550ef812bd56decd' },
  'logue/sense/cutoff': { variants: { base: 0 }, worst: 0, snapshotHash: '6bc89bcd79ffcb07' },
  'logue/sense/gate': { variants: { base: 0 }, worst: 0, snapshotHash: '5c83466572c3c9c0' },
  'logue/sense/param': { variants: { base: 0 }, worst: 0, snapshotHash: '64ad5fc4bd9ad056' },
  'logue/sense/pitch': { variants: { base: 0 }, worst: 0, snapshotHash: 'bc482cf6e4e29433' },
  'logue/sense/resonance': { variants: { base: 0 }, worst: 0, snapshotHash: '547eb218df760f8c' },
  'logue/sense/shape': { variants: { base: 0 }, worst: 0, snapshotHash: '325e380beee3bc55' },
  'logue/sense/shape-2': { variants: { base: 0 }, worst: 0, snapshotHash: '0a03598e05e5c340' },
  'logue/shape/soft-clip': {
    variants: { base: 20, control: 30 },
    worst: 30,
    snapshotHash: '94bd46054709e8a4'
  },
  'logue/shape/wavefolder': {
    variants: { base: 12, control: 23 },
    worst: 23,
    snapshotHash: '6597b9a61c6b5800'
  },
  'logue/util/bipolar-to-unipolar': {
    variants: { base: 0 },
    worst: 0,
    snapshotHash: '123ed572e3392a1a'
  },
  'logue/util/constant': { variants: { base: 0 }, worst: 0, snapshotHash: 'f3edec1a842e0630' },
  'logue/util/delay': {
    variants: { base: 154, control: 185 },
    worst: 185,
    snapshotHash: 'da512c286cda27d0'
  },
  'logue/util/freq-shift': {
    variants: { base: 284, control: 296 },
    worst: 296,
    snapshotHash: 'e1b3aaea0b6b5dba'
  },
  'logue/util/glide': { variants: { base: 37 }, worst: 37, snapshotHash: '006a80d815345ce6' },
  'logue/util/quantize': {
    variants: { base: 63, 'heavy-moving-input': 184 },
    worst: 184,
    snapshotHash: 'a721587239315819'
  },
  'logue/util/sample-delay': {
    variants: { base: 10 },
    worst: 10,
    snapshotHash: '90730202bac723c0'
  },
  'logue/util/sample-hold': {
    variants: { base: 0, control: 9 },
    worst: 9,
    snapshotHash: 'a29dc3d4ed9dc21e'
  },
  'logue/util/slew': {
    variants: { base: 25, control: 19 },
    worst: 25,
    snapshotHash: 'e3861ecccecfc253'
  },
  'logue/util/unipolar-to-bipolar': {
    variants: { base: 0 },
    worst: 0,
    snapshotHash: '7a44146c55ce7e26'
  }
}
