// GENERATED by scripts/measureXdFxCpuCosts.ts -- do not edit by hand; re-run it instead.
// Emulator estimates (scripts/emulateXdFxCycles.py) of minilogue xd EFFECT cycles per sample, on
// the emulator's own scale -- not hardware measurements.

/** Cycles per sample at SDRAM_PENALTY 0, plus the SDRAM accesses per sample: at a penalty of p
 *  cycles per access the cost is `cycles + p * sdram`. */
export interface FxCpuCost {
  cycles: number
  sdram: number
}

/** The unit shell alone (audio-in's mono to the output), per effect module. */
export const FX_CPU_BASELINE: Record<'modfx' | 'delfx' | 'revfx', FxCpuCost> = {
  modfx: { cycles: 47, sdram: 0 },
  delfx: { cycles: 25, sdram: 0 },
  revfx: { cycles: 25, sdram: 0 }
}

/** The xd fx goldens the table was measured against (`fxShellHash`). */
export const FX_CPU_SHELL_HASH = 'a0991e3ab2775c69'

/** Primitives no delfx can hold (its SRAM overflowed in every variant), with the snapshot hash
 *  they were built from: they have no entry, and a codegen change may make them fit. */
export const FX_CPU_DOES_NOT_FIT: Record<string, string> = {
  'logue/filter/string': 'd2fb4b7548c8393b',
  'logue/osc/additive': '8ad6107dc41ce335'
}

/**
 * Per primitive, above the delfx baseline, per measured variant (`cpuVariants.ts`: `base`,
 * `control` -- control inlets fed a moving signal --, `<CHECKBOX>`, `<CHECKBOX>+control`,
 * `heavy-*`): `first` for a unit's first instance of the primitive, `extra` for each further
 * one, and `shared` once when there are two or more (GCC inlines code with one caller and
 * shares it between several). A buffer writer's or reader's partner (`bufferPartners.ts`) is
 * subtracted.
 */
export const FX_CPU_COST_TABLE: Record<
  string,
  {
    variants: Record<string, { first: FxCpuCost; shared: FxCpuCost; extra: FxCpuCost }>
    snapshotHash: string
  }
> = {
  'logue/env/ad': {
    variants: {
      base: {
        first: { cycles: 27, sdram: 0 },
        shared: { cycles: -78, sdram: 0 },
        extra: { cycles: 112, sdram: 0 }
      },
      control: {
        first: { cycles: 88, sdram: 0 },
        shared: { cycles: 17, sdram: 0 },
        extra: { cycles: 91, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 28, sdram: 0 },
        shared: { cycles: 22, sdram: 0 },
        extra: { cycles: 61, sdram: 0 }
      },
      EXP: {
        first: { cycles: 25, sdram: 0 },
        shared: { cycles: -78, sdram: 0 },
        extra: { cycles: 110, sdram: 0 }
      },
      'EXP+control': {
        first: { cycles: 88, sdram: 0 },
        shared: { cycles: 20, sdram: 0 },
        extra: { cycles: 90, sdram: 0 }
      },
      'EXP+control-still': {
        first: { cycles: 26, sdram: 0 },
        shared: { cycles: 22, sdram: 0 },
        extra: { cycles: 59, sdram: 0 }
      }
    },
    snapshotHash: 'c384655566b26ffc'
  },
  'logue/env/adsr': {
    variants: {
      base: {
        first: { cycles: 41, sdram: 0 },
        shared: { cycles: 26, sdram: 0 },
        extra: { cycles: 76, sdram: 0 }
      },
      control: {
        first: { cycles: 43, sdram: 0 },
        shared: { cycles: 30, sdram: 0 },
        extra: { cycles: 75, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 31, sdram: 0 },
        shared: { cycles: 37, sdram: 0 },
        extra: { cycles: 76, sdram: 0 }
      }
    },
    snapshotHash: 'abd7e5820bec87bc'
  },
  'logue/env/follower': {
    variants: {
      base: {
        first: { cycles: 27, sdram: 0 },
        shared: { cycles: -53, sdram: 0 },
        extra: { cycles: 76, sdram: 0 }
      }
    },
    snapshotHash: 'f7893e7c4cfddfe4'
  },
  'logue/env/multistage': {
    variants: {
      base: {
        first: { cycles: 38, sdram: 0 },
        shared: { cycles: 51, sdram: 0 },
        extra: { cycles: 96, sdram: 0 }
      },
      control: {
        first: { cycles: 146, sdram: 0 },
        shared: { cycles: 68, sdram: 0 },
        extra: { cycles: 184, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 38, sdram: 0 },
        shared: { cycles: 64, sdram: 0 },
        extra: { cycles: 107, sdram: 0 }
      },
      'heavy-cycle': {
        first: { cycles: 134, sdram: 0 },
        shared: { cycles: 70, sdram: 0 },
        extra: { cycles: 171, sdram: 0 }
      }
    },
    snapshotHash: '13bbe27c71cd6bc6'
  },
  'logue/env/one-knob-adsr': {
    variants: {
      base: {
        first: { cycles: 45, sdram: 0 },
        shared: { cycles: 25, sdram: 0 },
        extra: { cycles: 81, sdram: 0 }
      },
      control: {
        first: { cycles: 96, sdram: 0 },
        shared: { cycles: 29, sdram: 0 },
        extra: { cycles: 109, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 35, sdram: 0 },
        shared: { cycles: 37, sdram: 0 },
        extra: { cycles: 80, sdram: 0 }
      },
      'heavy-moving-shape': {
        first: { cycles: 123, sdram: 0 },
        shared: { cycles: 24, sdram: 0 },
        extra: { cycles: 114, sdram: 0 }
      }
    },
    snapshotHash: 'a39fd0de0ef1ae2a'
  },
  'logue/filter/allpass': {
    variants: {
      base: {
        first: { cycles: 31, sdram: 2 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 32, sdram: 2 }
      },
      control: {
        first: { cycles: 73, sdram: 3 },
        shared: { cycles: 25, sdram: 0 },
        extra: { cycles: 91, sdram: 3 }
      },
      'control-still': {
        first: { cycles: 44, sdram: 3 },
        shared: { cycles: 21, sdram: 0 },
        extra: { cycles: 65, sdram: 3 }
      }
    },
    snapshotHash: 'f2a1656c07fb52d5'
  },
  'logue/filter/comb': {
    variants: {
      base: {
        first: { cycles: 55, sdram: 0 },
        shared: { cycles: 41, sdram: 0 },
        extra: { cycles: 101, sdram: 0 }
      },
      control: {
        first: { cycles: 140, sdram: 0 },
        shared: { cycles: 69, sdram: 0 },
        extra: { cycles: 209, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 56, sdram: 0 },
        shared: { cycles: 43, sdram: 0 },
        extra: { cycles: 100, sdram: 0 }
      },
      TRACK: {
        first: { cycles: 57, sdram: 0 },
        shared: { cycles: 41, sdram: 0 },
        extra: { cycles: 103, sdram: 0 }
      },
      'TRACK+control': {
        first: { cycles: 262, sdram: 0 },
        shared: { cycles: 69, sdram: 0 },
        extra: { cycles: 332, sdram: 0 }
      },
      'TRACK+control-still': {
        first: { cycles: 57, sdram: 0 },
        shared: { cycles: 42, sdram: 0 },
        extra: { cycles: 103, sdram: 0 }
      }
    },
    snapshotHash: '1fd2dcd5f18abf0e'
  },
  'logue/filter/eq-band': {
    variants: {
      base: {
        first: { cycles: 52, sdram: 0 },
        shared: { cycles: 29, sdram: 0 },
        extra: { cycles: 95, sdram: 0 }
      },
      control: {
        first: { cycles: 137, sdram: 0 },
        shared: { cycles: 35, sdram: 0 },
        extra: { cycles: 158, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 53, sdram: 0 },
        shared: { cycles: 27, sdram: 0 },
        extra: { cycles: 96, sdram: 0 }
      }
    },
    snapshotHash: '51754dcc3757ff3f'
  },
  'logue/filter/formant': {
    variants: {
      base: {
        first: { cycles: 614, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 616, sdram: 0 }
      },
      control: {
        first: { cycles: 649, sdram: 0 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 642, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 662, sdram: 0 },
        shared: { cycles: -4, sdram: 0 },
        extra: { cycles: 650, sdram: 0 }
      }
    },
    snapshotHash: '3064386816179abd'
  },
  'logue/filter/highpass-cheap': {
    variants: {
      base: {
        first: { cycles: 12, sdram: 0 },
        shared: { cycles: -5, sdram: 0 },
        extra: { cycles: 19, sdram: 0 }
      },
      control: {
        first: { cycles: 21, sdram: 0 },
        shared: { cycles: -50, sdram: 0 },
        extra: { cycles: 70, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 12, sdram: 0 },
        shared: { cycles: -9, sdram: 0 },
        extra: { cycles: 21, sdram: 0 }
      }
    },
    snapshotHash: '5918f33ffc84533f'
  },
  'logue/filter/hilbert': {
    variants: {
      base: {
        first: { cycles: 107, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 103, sdram: 0 }
      }
    },
    snapshotHash: 'f56fb7646016882f'
  },
  'logue/filter/ladder': {
    variants: {
      base: {
        first: { cycles: 116, sdram: 0 },
        shared: { cycles: -24, sdram: 0 },
        extra: { cycles: 142, sdram: 0 }
      },
      control: {
        first: { cycles: 251, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 247, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 117, sdram: 0 },
        shared: { cycles: -22, sdram: 0 },
        extra: { cycles: 142, sdram: 0 }
      },
      TRACK: {
        first: { cycles: 116, sdram: 0 },
        shared: { cycles: -24, sdram: 0 },
        extra: { cycles: 142, sdram: 0 }
      },
      'TRACK+control': {
        first: { cycles: 250, sdram: 0 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 248, sdram: 0 }
      },
      'TRACK+control-still': {
        first: { cycles: 117, sdram: 0 },
        shared: { cycles: -23, sdram: 0 },
        extra: { cycles: 142, sdram: 0 }
      },
      'heavy-moving-cutoff': {
        first: { cycles: 249, sdram: 0 },
        shared: { cycles: -5, sdram: 0 },
        extra: { cycles: 207, sdram: 0 }
      }
    },
    snapshotHash: '14f53da66bd476e6'
  },
  'logue/filter/lowpass-cheap': {
    variants: {
      base: {
        first: { cycles: 9, sdram: 0 },
        shared: { cycles: -15, sdram: 0 },
        extra: { cycles: 24, sdram: 0 }
      },
      control: {
        first: { cycles: 17, sdram: 0 },
        shared: { cycles: -43, sdram: 0 },
        extra: { cycles: 62, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 9, sdram: 0 },
        shared: { cycles: -15, sdram: 0 },
        extra: { cycles: 24, sdram: 0 }
      }
    },
    snapshotHash: '9498d8e54c739257'
  },
  'logue/filter/svf': {
    variants: {
      base: {
        first: { cycles: 50, sdram: 0 },
        shared: { cycles: 38, sdram: 0 },
        extra: { cycles: 89, sdram: 0 }
      },
      control: {
        first: { cycles: 124, sdram: 0 },
        shared: { cycles: 8, sdram: 0 },
        extra: { cycles: 211, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 50, sdram: 0 },
        shared: { cycles: 39, sdram: 0 },
        extra: { cycles: 89, sdram: 0 }
      },
      TRACK: {
        first: { cycles: 52, sdram: 0 },
        shared: { cycles: 39, sdram: 0 },
        extra: { cycles: 91, sdram: 0 }
      },
      'TRACK+control': {
        first: { cycles: 277, sdram: 0 },
        shared: { cycles: 55, sdram: 0 },
        extra: { cycles: 327, sdram: 0 }
      },
      'TRACK+control-still': {
        first: { cycles: 52, sdram: 0 },
        shared: { cycles: 40, sdram: 0 },
        extra: { cycles: 91, sdram: 0 }
      }
    },
    snapshotHash: '71e157475bbe46c8'
  },
  'logue/filter/tilt': {
    variants: {
      base: {
        first: { cycles: 21, sdram: 0 },
        shared: { cycles: -5, sdram: 0 },
        extra: { cycles: 23, sdram: 0 }
      },
      control: {
        first: { cycles: 80, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 77, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 21, sdram: 0 },
        shared: { cycles: -4, sdram: 0 },
        extra: { cycles: 23, sdram: 0 }
      }
    },
    snapshotHash: '99712da0bbd917df'
  },
  'logue/gain/vca': {
    variants: {
      base: {
        first: { cycles: 3, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 4, sdram: 0 }
      },
      control: {
        first: { cycles: 1, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 1, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '71e7c2874a2780a1'
  },
  'logue/lfo/fast-square': {
    variants: {
      base: {
        first: { cycles: 15, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 28, sdram: 0 }
      },
      control: {
        first: { cycles: 76, sdram: 0 },
        shared: { cycles: -47, sdram: 0 },
        extra: { cycles: 108, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 30, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 42, sdram: 0 }
      },
      TRACK: {
        first: { cycles: 15, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 28, sdram: 0 }
      },
      'TRACK+control': {
        first: { cycles: 173, sdram: 0 },
        shared: { cycles: 3, sdram: 0 },
        extra: { cycles: 157, sdram: 0 }
      },
      'TRACK+control-still': {
        first: { cycles: 30, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 42, sdram: 0 }
      }
    },
    snapshotHash: '9023a42eadc26048'
  },
  'logue/lfo/ramp-down': {
    variants: {
      base: {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 18, sdram: 0 }
      },
      control: {
        first: { cycles: 60, sdram: 0 },
        shared: { cycles: 11, sdram: 0 },
        extra: { cycles: 56, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 16, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 24, sdram: 0 }
      }
    },
    snapshotHash: '93415749054fe77d'
  },
  'logue/lfo/ramp-up': {
    variants: {
      base: {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 18, sdram: 0 }
      },
      control: {
        first: { cycles: 60, sdram: 0 },
        shared: { cycles: 11, sdram: 0 },
        extra: { cycles: 56, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 16, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 24, sdram: 0 }
      }
    },
    snapshotHash: '657d45b8a4249ea5'
  },
  'logue/lfo/random-steps': {
    variants: {
      base: {
        first: { cycles: 2, sdram: 0 },
        shared: { cycles: 5, sdram: 0 },
        extra: { cycles: 10, sdram: 0 }
      },
      control: {
        first: { cycles: 54, sdram: 0 },
        shared: { cycles: 12, sdram: 0 },
        extra: { cycles: 50, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: 6, sdram: 0 },
        extra: { cycles: 18, sdram: 0 }
      }
    },
    snapshotHash: '001bad58241c33a2'
  },
  'logue/lfo/sine-lfo': {
    variants: {
      base: {
        first: { cycles: 30, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 37, sdram: 0 }
      },
      control: {
        first: { cycles: 81, sdram: 0 },
        shared: { cycles: 14, sdram: 0 },
        extra: { cycles: 75, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 37, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 44, sdram: 0 }
      }
    },
    snapshotHash: 'f091daaf62b2b62e'
  },
  'logue/lfo/square-lfo': {
    variants: {
      base: {
        first: { cycles: 4, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 18, sdram: 0 }
      },
      control: {
        first: { cycles: 54, sdram: 0 },
        shared: { cycles: 11, sdram: 0 },
        extra: { cycles: 56, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 25, sdram: 0 }
      }
    },
    snapshotHash: '5bf8d1d088df38b0'
  },
  'logue/lfo/triangle-lfo': {
    variants: {
      base: {
        first: { cycles: 11, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 19, sdram: 0 }
      },
      control: {
        first: { cycles: 61, sdram: 0 },
        shared: { cycles: 12, sdram: 0 },
        extra: { cycles: 57, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 22, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 30, sdram: 0 }
      }
    },
    snapshotHash: '63720761f9fb074b'
  },
  'logue/logic/and': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -8, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'f80de56b91f2e236'
  },
  'logue/logic/chance': {
    variants: {
      base: {
        first: { cycles: 4, sdram: 0 },
        shared: { cycles: -96, sdram: 0 },
        extra: { cycles: 106, sdram: 0 }
      },
      control: {
        first: { cycles: 41, sdram: 0 },
        shared: { cycles: -75, sdram: 0 },
        extra: { cycles: 97, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 16, sdram: 0 },
        shared: { cycles: -84, sdram: 0 },
        extra: { cycles: 105, sdram: 0 }
      }
    },
    snapshotHash: 'efecc236e2563837'
  },
  'logue/logic/edge': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 7, sdram: 0 }
      },
      control: {
        first: { cycles: 4, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 7, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 7, sdram: 0 }
      }
    },
    snapshotHash: 'c26efc0252e90a1d'
  },
  'logue/logic/equal': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 7, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 11, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'f164a8c5070849fd'
  },
  'logue/logic/greater-than': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 7, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'c1bb3de72d4ece0e'
  },
  'logue/logic/less-than': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 7, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '4357ab282a1ca032'
  },
  'logue/logic/or': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -8, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '07e57403fbf2d1de'
  },
  'logue/logic/round-robin': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -8, sdram: 0 },
        extra: { cycles: 1, sdram: 0 }
      },
      control: {
        first: { cycles: 32, sdram: 0 },
        shared: { cycles: -62, sdram: 0 },
        extra: { cycles: 91, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 20, sdram: 0 },
        shared: { cycles: -115, sdram: 0 },
        extra: { cycles: 143, sdram: 0 }
      }
    },
    snapshotHash: '7338eb6e334fed60'
  },
  'logue/logic/schmitt': {
    variants: {
      base: {
        first: { cycles: 13, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 20, sdram: 0 }
      },
      control: {
        first: { cycles: 16, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 19, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 6, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 13, sdram: 0 }
      }
    },
    snapshotHash: '5affa568710e10ce'
  },
  'logue/logic/xor': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -8, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -8, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'c9d3d1a8aab33c41'
  },
  'logue/math/abs': {
    variants: {
      base: {
        first: { cycles: 1, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '6b592c1cff9c6d33'
  },
  'logue/math/add': {
    variants: {
      base: {
        first: { cycles: 1, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '1c1ccaf32ecaf295'
  },
  'logue/math/clamp': {
    variants: {
      base: {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 11, sdram: 0 }
      }
    },
    snapshotHash: '0cdd97825f4434d9'
  },
  'logue/math/curve': {
    variants: {
      base: {
        first: { cycles: 42, sdram: 0 },
        shared: { cycles: 6, sdram: 0 },
        extra: { cycles: 45, sdram: 0 }
      },
      control: {
        first: { cycles: 54, sdram: 0 },
        shared: { cycles: 10, sdram: 0 },
        extra: { cycles: 53, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 51, sdram: 0 },
        shared: { cycles: 10, sdram: 0 },
        extra: { cycles: 51, sdram: 0 }
      }
    },
    snapshotHash: 'a6bc9c67c8ed7f33'
  },
  'logue/math/max': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'df0bd7fdbe016146'
  },
  'logue/math/min': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '7ad50beda32b6968'
  },
  'logue/math/multiply': {
    variants: {
      base: {
        first: { cycles: 1, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '422c16a247da8ec8'
  },
  'logue/math/negate': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 1, sdram: 0 }
      }
    },
    snapshotHash: '80764f40f75f22b5'
  },
  'logue/math/one-minus': {
    variants: {
      base: {
        first: { cycles: 3, sdram: 0 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'f4a6e757bc9dd221'
  },
  'logue/math/scale': {
    variants: {
      base: {
        first: { cycles: 3, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 4, sdram: 0 }
      }
    },
    snapshotHash: '33fcee3c312305e9'
  },
  'logue/math/subtract': {
    variants: {
      base: {
        first: { cycles: 1, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'd9827f1376cc7742'
  },
  'logue/mix/bus-receive': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'fb1b473a0c1edfc3'
  },
  'logue/mix/bus-receive-stereo': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '97a974b3ae145ea1'
  },
  'logue/mix/bus-send': {
    variants: {
      base: {
        first: { cycles: 5, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 6, sdram: 0 }
      }
    },
    snapshotHash: '574efcb254356628'
  },
  'logue/mix/bus-send-stereo': {
    variants: {
      base: {
        first: { cycles: 5, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 7, sdram: 0 }
      }
    },
    snapshotHash: 'ce0f1ba491fc3493'
  },
  'logue/mix/crossfader': {
    variants: {
      base: {
        first: { cycles: 17, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 16, sdram: 0 }
      },
      control: {
        first: { cycles: 59, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 55, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 19, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 15, sdram: 0 }
      }
    },
    snapshotHash: 'ff48b03b50520cf3'
  },
  'logue/mix/mix2': {
    variants: {
      base: {
        first: { cycles: 11, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 12, sdram: 0 }
      }
    },
    snapshotHash: 'bcf10c53a2411c0f'
  },
  'logue/mix/pan': {
    variants: {
      base: {
        first: { cycles: 7, sdram: 0 },
        shared: { cycles: 2, sdram: 0 },
        extra: { cycles: 9, sdram: 0 }
      },
      control: {
        first: { cycles: 32, sdram: 0 },
        shared: { cycles: 2, sdram: 0 },
        extra: { cycles: 32, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 9, sdram: 0 }
      }
    },
    snapshotHash: 'd139dc1b3b1c3b34'
  },
  'logue/mix/pan-mix2': {
    variants: {
      base: {
        first: { cycles: 18, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 16, sdram: 0 }
      },
      control: {
        first: { cycles: 74, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 72, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 18, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 16, sdram: 0 }
      }
    },
    snapshotHash: '012908465f425a50'
  },
  'logue/mix/stereo-crossfader': {
    variants: {
      base: {
        first: { cycles: 14, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 17, sdram: 0 }
      },
      control: {
        first: { cycles: 58, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 57, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 16, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 18, sdram: 0 }
      }
    },
    snapshotHash: '779c8ef1206c74bd'
  },
  'logue/mix/stereo-mix2': {
    variants: {
      base: {
        first: { cycles: 11, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 13, sdram: 0 }
      }
    },
    snapshotHash: '73842bd820468e9f'
  },
  'logue/mix/width': {
    variants: {
      base: {
        first: { cycles: 13, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 11, sdram: 0 }
      },
      control: {
        first: { cycles: 21, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 19, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 22, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 20, sdram: 0 }
      }
    },
    snapshotHash: 'e3d3cef19609c42b'
  },
  'logue/mux/demux2': {
    variants: {
      base: {
        first: { cycles: 12, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 14, sdram: 0 }
      },
      control: {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -7, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -7, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'e60fc2ba0786e999'
  },
  'logue/mux/mux2': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '43132007849f2d5e'
  },
  'logue/mux/mux4': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -100, sdram: 0 },
        extra: { cycles: 100, sdram: 0 }
      },
      control: {
        first: { cycles: 2, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 2, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'e7cd1ca8a0645ebe'
  },
  'logue/osc/bass-support': {
    variants: {
      base: {
        first: { cycles: 257, sdram: 0 },
        shared: { cycles: -7, sdram: 0 },
        extra: { cycles: 273, sdram: 0 }
      },
      control: {
        first: { cycles: 533, sdram: 0 },
        shared: { cycles: 8, sdram: 0 },
        extra: { cycles: 525, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 435, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 452, sdram: 0 }
      },
      RETRIG: {
        first: { cycles: 257, sdram: 0 },
        shared: { cycles: -7, sdram: 0 },
        extra: { cycles: 273, sdram: 0 }
      },
      'RETRIG+control': {
        first: { cycles: 533, sdram: 0 },
        shared: { cycles: 8, sdram: 0 },
        extra: { cycles: 525, sdram: 0 }
      },
      'RETRIG+control-still': {
        first: { cycles: 435, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 452, sdram: 0 }
      }
    },
    snapshotHash: 'da5adbf9ea4c7a45'
  },
  'logue/osc/exciter': {
    variants: {
      base: {
        first: { cycles: 242, sdram: 0 },
        shared: { cycles: 62, sdram: 0 },
        extra: { cycles: 303, sdram: 0 }
      },
      control: {
        first: { cycles: 249, sdram: 0 },
        shared: { cycles: 71, sdram: 0 },
        extra: { cycles: 309, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 245, sdram: 0 },
        shared: { cycles: 69, sdram: 0 },
        extra: { cycles: 314, sdram: 0 }
      }
    },
    snapshotHash: '718efdc3d5a3a5fc'
  },
  'logue/osc/granular': {
    variants: {
      base: {
        first: { cycles: 245, sdram: 0 },
        shared: { cycles: -21, sdram: 0 },
        extra: { cycles: 274, sdram: 0 }
      },
      control: {
        first: { cycles: 277, sdram: 0 },
        shared: { cycles: -7, sdram: 0 },
        extra: { cycles: 273, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 336, sdram: 0 },
        shared: { cycles: -19, sdram: 0 },
        extra: { cycles: 360, sdram: 0 }
      },
      SYNC: {
        first: { cycles: 237, sdram: 0 },
        shared: { cycles: -18, sdram: 0 },
        extra: { cycles: 263, sdram: 0 }
      },
      'SYNC+control': {
        first: { cycles: 259, sdram: 0 },
        shared: { cycles: -6, sdram: 0 },
        extra: { cycles: 255, sdram: 0 }
      },
      'SYNC+control-still': {
        first: { cycles: 319, sdram: 0 },
        shared: { cycles: -17, sdram: 0 },
        extra: { cycles: 341, sdram: 0 }
      },
      'heavy-size-window-100': {
        first: { cycles: 448, sdram: 0 },
        shared: { cycles: -7, sdram: 0 },
        extra: { cycles: 444, sdram: 0 }
      },
      'heavy-sync-off-density-100': {
        first: { cycles: 339, sdram: 0 },
        shared: { cycles: -6, sdram: 0 },
        extra: { cycles: 335, sdram: 0 }
      }
    },
    snapshotHash: '287537a0ffee7fe9'
  },
  'logue/osc/lfsr': {
    variants: {
      base: {
        first: { cycles: 22, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 31, sdram: 0 }
      },
      control: {
        first: { cycles: 169, sdram: 0 },
        shared: { cycles: 6, sdram: 0 },
        extra: { cycles: 160, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 23, sdram: 0 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 32, sdram: 0 }
      },
      TRACK: {
        first: { cycles: 19, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 28, sdram: 0 }
      },
      'TRACK+control': {
        first: { cycles: 68, sdram: 0 },
        shared: { cycles: -42, sdram: 0 },
        extra: { cycles: 107, sdram: 0 }
      },
      'TRACK+control-still': {
        first: { cycles: 22, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 31, sdram: 0 }
      },
      'heavy-short': {
        first: { cycles: 10, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 20, sdram: 0 }
      },
      'heavy-short-control': {
        first: { cycles: 158, sdram: 0 },
        shared: { cycles: 13, sdram: 0 },
        extra: { cycles: 144, sdram: 0 }
      }
    },
    snapshotHash: '7fbe59bdb96624a8'
  },
  'logue/osc/noise': {
    variants: {
      base: {
        first: { cycles: 4, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 12, sdram: 0 }
      },
      'heavy-pink': {
        first: { cycles: 31, sdram: 0 },
        shared: { cycles: -8, sdram: 0 },
        extra: { cycles: 41, sdram: 0 }
      },
      'heavy-brown': {
        first: { cycles: 22, sdram: 0 },
        shared: { cycles: -4, sdram: 0 },
        extra: { cycles: 31, sdram: 0 }
      },
      'heavy-violet': {
        first: { cycles: 22, sdram: 0 },
        shared: { cycles: -4, sdram: 0 },
        extra: { cycles: 31, sdram: 0 }
      }
    },
    snapshotHash: 'c55e2984e99ac4a6'
  },
  'logue/osc/phase-dist': {
    variants: {
      base: {
        first: { cycles: 93, sdram: 0 },
        shared: { cycles: -56, sdram: 0 },
        extra: { cycles: 149, sdram: 0 }
      },
      control: {
        first: { cycles: 332, sdram: 0 },
        shared: { cycles: -26, sdram: 0 },
        extra: { cycles: 304, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 115, sdram: 0 },
        shared: { cycles: -80, sdram: 0 },
        extra: { cycles: 189, sdram: 0 }
      },
      'heavy-reso': {
        first: { cycles: 105, sdram: 0 },
        shared: { cycles: -60, sdram: 0 },
        extra: { cycles: 165, sdram: 0 }
      },
      'heavy-wave2': {
        first: { cycles: 109, sdram: 0 },
        shared: { cycles: -69, sdram: 0 },
        extra: { cycles: 177, sdram: 0 }
      },
      'heavy-moving-dcw': {
        first: { cycles: 346, sdram: 0 },
        shared: { cycles: -35, sdram: 0 },
        extra: { cycles: 322, sdram: 0 }
      }
    },
    snapshotHash: '447d0e2b472a3a55'
  },
  'logue/osc/pulse': {
    variants: {
      base: {
        first: { cycles: 103, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 156, sdram: 0 }
      },
      control: {
        first: { cycles: 396, sdram: 0 },
        shared: { cycles: 8, sdram: 0 },
        extra: { cycles: 435, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 125, sdram: 0 },
        shared: { cycles: -6, sdram: 0 },
        extra: { cycles: 176, sdram: 0 }
      }
    },
    snapshotHash: '773b9bbd527f1576'
  },
  'logue/osc/saw': {
    variants: {
      base: {
        first: { cycles: 104, sdram: 0 },
        shared: { cycles: -14, sdram: 0 },
        extra: { cycles: 143, sdram: 0 }
      },
      control: {
        first: { cycles: 436, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 461, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 113, sdram: 0 },
        shared: { cycles: -17, sdram: 0 },
        extra: { cycles: 150, sdram: 0 }
      },
      TZFM: {
        first: { cycles: 96, sdram: 0 },
        shared: { cycles: 13, sdram: 0 },
        extra: { cycles: 108, sdram: 0 }
      },
      'TZFM+control': {
        first: { cycles: 443, sdram: 0 },
        shared: { cycles: 29, sdram: 0 },
        extra: { cycles: 430, sdram: 0 }
      },
      'TZFM+control-still': {
        first: { cycles: 117, sdram: 0 },
        shared: { cycles: 10, sdram: 0 },
        extra: { cycles: 128, sdram: 0 }
      }
    },
    snapshotHash: '689d43e99e06ce9c'
  },
  'logue/osc/sine': {
    variants: {
      base: {
        first: { cycles: 52, sdram: 0 },
        shared: { cycles: -25, sdram: 0 },
        extra: { cycles: 76, sdram: 0 }
      },
      control: {
        first: { cycles: 222, sdram: 0 },
        shared: { cycles: -15, sdram: 0 },
        extra: { cycles: 231, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 62, sdram: 0 },
        shared: { cycles: -26, sdram: 0 },
        extra: { cycles: 84, sdram: 0 }
      }
    },
    snapshotHash: 'b34b1284af3c9ca7'
  },
  'logue/osc/square': {
    variants: {
      base: {
        first: { cycles: 102, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 154, sdram: 0 }
      },
      control: {
        first: { cycles: 388, sdram: 0 },
        shared: { cycles: 8, sdram: 0 },
        extra: { cycles: 422, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 114, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 164, sdram: 0 }
      }
    },
    snapshotHash: '9a189b5fd7ef929c'
  },
  'logue/osc/sync': {
    variants: {
      base: {
        first: { cycles: 100, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 104, sdram: 0 }
      },
      control: {
        first: { cycles: 358, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 337, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 104, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 109, sdram: 0 }
      }
    },
    snapshotHash: 'de6812a7e1beb6e4'
  },
  'logue/osc/triangle': {
    variants: {
      base: {
        first: { cycles: 32, sdram: 0 },
        shared: { cycles: -29, sdram: 0 },
        extra: { cycles: 62, sdram: 0 }
      },
      control: {
        first: { cycles: 203, sdram: 0 },
        shared: { cycles: -17, sdram: 0 },
        extra: { cycles: 214, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 44, sdram: 0 },
        shared: { cycles: -26, sdram: 0 },
        extra: { cycles: 66, sdram: 0 }
      }
    },
    snapshotHash: 'c19162f9574d3fe7'
  },
  'logue/sense/control': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '550ef812bd56decd'
  },
  'logue/sense/tempo': {
    variants: {
      base: {
        first: { cycles: 43, sdram: 0 },
        shared: { cycles: 32, sdram: 0 },
        extra: { cycles: 78, sdram: 0 }
      }
    },
    snapshotHash: '0410106efe6cce20'
  },
  'logue/shape/drive': {
    variants: {
      base: {
        first: { cycles: 26, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 25, sdram: 0 }
      },
      control: {
        first: { cycles: 121, sdram: 0 },
        shared: { cycles: 2, sdram: 0 },
        extra: { cycles: 118, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 28, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 27, sdram: 0 }
      }
    },
    snapshotHash: 'fd99dae03aa4746d'
  },
  'logue/shape/soft-clip': {
    variants: {
      base: {
        first: { cycles: 23, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 23, sdram: 0 }
      },
      control: {
        first: { cycles: 33, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 31, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 31, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 30, sdram: 0 }
      }
    },
    snapshotHash: '94bd46054709e8a4'
  },
  'logue/shape/wavefolder': {
    variants: {
      base: {
        first: { cycles: 13, sdram: 0 },
        shared: { cycles: -31, sdram: 0 },
        extra: { cycles: 47, sdram: 0 }
      },
      control: {
        first: { cycles: 26, sdram: 0 },
        shared: { cycles: -31, sdram: 0 },
        extra: { cycles: 54, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 24, sdram: 0 },
        shared: { cycles: -29, sdram: 0 },
        extra: { cycles: 52, sdram: 0 }
      }
    },
    snapshotHash: '6597b9a61c6b5800'
  },
  'logue/util/bipolar-to-unipolar': {
    variants: {
      base: {
        first: { cycles: 7, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '123ed572e3392a1a'
  },
  'logue/util/buffer': {
    variants: {
      base: {
        first: { cycles: 61, sdram: 2 },
        shared: { cycles: -14, sdram: 0 },
        extra: { cycles: 71, sdram: 2 }
      },
      control: {
        first: { cycles: 65, sdram: 2 },
        shared: { cycles: -15, sdram: 0 },
        extra: { cycles: 74, sdram: 2 }
      },
      'control-still': {
        first: { cycles: 64, sdram: 2 },
        shared: { cycles: -14, sdram: 0 },
        extra: { cycles: 74, sdram: 2 }
      },
      FREEZE: {
        first: { cycles: 27, sdram: 0 },
        shared: { cycles: -10, sdram: 0 },
        extra: { cycles: 35, sdram: 0 }
      },
      'FREEZE+control': {
        first: { cycles: 30, sdram: 0 },
        shared: { cycles: -8, sdram: 0 },
        extra: { cycles: 40, sdram: 0 }
      },
      'FREEZE+control-still': {
        first: { cycles: 28, sdram: 0 },
        shared: { cycles: -6, sdram: 0 },
        extra: { cycles: 40, sdram: 0 }
      }
    },
    snapshotHash: 'd11fef6b9acccce2'
  },
  'logue/util/buffer-tap': {
    variants: {
      base: {
        first: { cycles: 82, sdram: 4 },
        shared: { cycles: 6, sdram: 0 },
        extra: { cycles: 72, sdram: 4 }
      },
      control: {
        first: { cycles: 94, sdram: 4 },
        shared: { cycles: 4, sdram: 0 },
        extra: { cycles: 79, sdram: 4 }
      },
      'control-still': {
        first: { cycles: 93, sdram: 4 },
        shared: { cycles: 5, sdram: 0 },
        extra: { cycles: 79, sdram: 4 }
      }
    },
    snapshotHash: 'c9f54d6abbaf5c76'
  },
  'logue/util/constant': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: 'f3edec1a842e0630'
  },
  'logue/util/delay': {
    variants: {
      base: {
        first: { cycles: 151, sdram: 0 },
        shared: { cycles: -3, sdram: 0 },
        extra: { cycles: 144, sdram: 0 }
      },
      control: {
        first: { cycles: 172, sdram: 0 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 164, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 181, sdram: 0 },
        shared: { cycles: -4, sdram: 0 },
        extra: { cycles: 163, sdram: 0 }
      }
    },
    snapshotHash: 'da512c286cda27d0'
  },
  'logue/util/freq-shift': {
    variants: {
      base: {
        first: { cycles: 284, sdram: 0 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 284, sdram: 0 }
      },
      control: {
        first: { cycles: 315, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 301, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 293, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 289, sdram: 0 }
      }
    },
    snapshotHash: 'e1b3aaea0b6b5dba'
  },
  'logue/util/glide': {
    variants: {
      base: {
        first: { cycles: 40, sdram: 0 },
        shared: { cycles: 12, sdram: 0 },
        extra: { cycles: 58, sdram: 0 }
      }
    },
    snapshotHash: '006a80d815345ce6'
  },
  'logue/util/grain': {
    variants: {
      base: {
        first: { cycles: 102, sdram: 3 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 100, sdram: 3 }
      },
      control: {
        first: { cycles: 68, sdram: 1 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 50, sdram: 1 }
      },
      'control-still': {
        first: { cycles: 25, sdram: 0 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 25, sdram: 0 }
      },
      'heavy-capturing': {
        first: { cycles: 111, sdram: 3 },
        shared: { cycles: -1, sdram: 0 },
        extra: { cycles: 93, sdram: 3 }
      }
    },
    snapshotHash: '8c1b233d213f6d52'
  },
  'logue/util/long-delay': {
    variants: {
      base: {
        first: { cycles: 118, sdram: 3 },
        shared: { cycles: 32, sdram: 0 },
        extra: { cycles: 148, sdram: 3 }
      },
      control: {
        first: { cycles: 140, sdram: 3 },
        shared: { cycles: 33, sdram: 0 },
        extra: { cycles: 168, sdram: 3 }
      },
      'control-still': {
        first: { cycles: 147, sdram: 3 },
        shared: { cycles: 29, sdram: 0 },
        extra: { cycles: 168, sdram: 3 }
      },
      SYNC: {
        first: { cycles: 134, sdram: 3 },
        shared: { cycles: 36, sdram: 0 },
        extra: { cycles: 168, sdram: 3 }
      },
      'SYNC+control': {
        first: { cycles: 159, sdram: 3 },
        shared: { cycles: 37, sdram: 0 },
        extra: { cycles: 191, sdram: 3 }
      },
      'SYNC+control-still': {
        first: { cycles: 166, sdram: 3 },
        shared: { cycles: 33, sdram: 0 },
        extra: { cycles: 191, sdram: 3 }
      }
    },
    snapshotHash: '8c91d8d963960391'
  },
  'logue/util/quantize': {
    variants: {
      base: {
        first: { cycles: 174, sdram: 0 },
        shared: { cycles: -2, sdram: 0 },
        extra: { cycles: 169, sdram: 0 }
      },
      'heavy-moving-input': {
        first: { cycles: 184, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 175, sdram: 0 }
      }
    },
    snapshotHash: 'a721587239315819'
  },
  'logue/util/reverse-tap': {
    variants: {
      base: {
        first: { cycles: 96, sdram: 2 },
        shared: { cycles: 3, sdram: 0 },
        extra: { cycles: 92, sdram: 2 }
      },
      control: {
        first: { cycles: 96, sdram: 2 },
        shared: { cycles: 1, sdram: 0 },
        extra: { cycles: 93, sdram: 2 }
      },
      'control-still': {
        first: { cycles: 98, sdram: 2 },
        shared: { cycles: 2, sdram: 0 },
        extra: { cycles: 94, sdram: 2 }
      }
    },
    snapshotHash: 'f0f4d753989ec3d8'
  },
  'logue/util/sample-delay': {
    variants: {
      base: {
        first: { cycles: 12, sdram: 0 },
        shared: { cycles: -5, sdram: 0 },
        extra: { cycles: 7, sdram: 0 }
      }
    },
    snapshotHash: '90730202bac723c0'
  },
  'logue/util/sample-hold': {
    variants: {
      base: {
        first: { cycles: 0, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      },
      control: {
        first: { cycles: 16, sdram: 0 },
        shared: { cycles: 8, sdram: 0 },
        extra: { cycles: 12, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 3, sdram: 0 },
        shared: { cycles: 5, sdram: 0 },
        extra: { cycles: 12, sdram: 0 }
      }
    },
    snapshotHash: 'a29dc3d4ed9dc21e'
  },
  'logue/util/slew': {
    variants: {
      base: {
        first: { cycles: 23, sdram: 0 },
        shared: { cycles: 19, sdram: 0 },
        extra: { cycles: 42, sdram: 0 }
      },
      control: {
        first: { cycles: 54, sdram: 0 },
        shared: { cycles: 19, sdram: 0 },
        extra: { cycles: 73, sdram: 0 }
      },
      'control-still': {
        first: { cycles: 24, sdram: 0 },
        shared: { cycles: 17, sdram: 0 },
        extra: { cycles: 43, sdram: 0 }
      }
    },
    snapshotHash: 'e3861ecccecfc253'
  },
  'logue/util/unipolar-to-bipolar': {
    variants: {
      base: {
        first: { cycles: 12, sdram: 0 },
        shared: { cycles: 0, sdram: 0 },
        extra: { cycles: 0, sdram: 0 }
      }
    },
    snapshotHash: '7a44146c55ce7e26'
  }
}
