// Embeds parts of Korg's logue SDK (the xd's tpl/_unit.c, ld/*.ld and Makefile), Copyright (c)
// 2018, KORG INC., under the BSD 3-Clause License -- full text in THIRD_PARTY_NOTICES.md.
import type { LogueEffectModule, PatchDocument } from '../../../src/shared/domain/patch'
import type { LogueKnob } from '../../../src/shared/domain/paramValueTypes'
import { UnsupportedLogueNodeError, type ResolvedSource } from '../oscInstances'
import type { SubpatchDefinitions } from '../subpatches'
import { resolveUnit } from '../resolveUnit'
import { buildOscBodyPieces, sdramLayout, sourceVar } from '../oscBody'
import { KNOB_POSITION_MEMBER } from '../oscParams'
import {
  fixedKnobInits,
  formatKb,
  FX_FIXED_MEMBER_DECLS,
  OSC_API_STAND_INS,
  sdramClears,
  sdramInits,
  sdramPointerDecls,
  type SdramLayout
} from '../fxShared'
import { findUnitKind, isEffectModule, MODULE_LABEL, type UnitKind } from '../unitKinds'
import {
  MAKEFILE,
  RULES_LD,
  validateNoBreakingChars,
  type LogueOldGenOscUnitMeta
} from './generateOscUnit'

/**
 * A `PatchDocument` whose module is an effect -> buildable minilogue xd effect unit source (phase
 * 7 of "effect patches", docs/PLAN-effects.md). The graph goes through the same pipeline as every
 * other unit (`resolveUnit`, `buildOscBodyPieces`); this file is the old-gen outer shell,
 * after Korg's `platform/minilogue-xd/dummy-{modfx,delfx,revfx}` and the phase 0 spike units
 * that loaded on a real xd:
 * - modfx: `MODFX_PROCESS(main_xn, main_yn, sub_xn, sub_yn, frames)`, separate buffers; delfx/
 *   revfx: `*_PROCESS(xn, frames)`, in place. Both interleaved stereo float.
 * - No menu params (`num_param` 0): only the panel knobs, whose values arrive as Q31.
 * - SDRAM is one static `__sdram` array (a NOLOAD section, so init clears it).
 * - Tempo is pulled per block (`fx_get_bpmf`), not pushed like NTS-1 mkII's `unit_set_tempo`.
 * The whole build scaffold is embedded, like the oscillator generator's, so an export builds on
 * its own.
 */

export interface LogueOldGenFxUnitSource {
  module: LogueEffectModule
  manifestJson: string
  projectMk: string
  fxCpp: string
  makefile: string
  unitC: string
  rulesLd: string
  /** `ld/user<module>.ld` -- the module's own SRAM/SDRAM regions. */
  moduleLd: string
  mainApiSyms: string
}

const HEADER: Record<LogueEffectModule, { header: string; prefix: string; magic: string }> = {
  modfx: { header: 'usermodfx.h', prefix: 'MODFX', magic: "'U','M','O','D'" },
  delfx: { header: 'userdelfx.h', prefix: 'DELFX', magic: "'U','D','E','L'" },
  revfx: { header: 'userrevfx.h', prefix: 'REVFX', magic: "'U','R','E','V'" }
}

/** `user_*fx_param_id_t`: the knob each param id is. Id 2 on delay/reverb is `reserved0`, and
 *  Shift+Depth (`shift_depth`, id 3) is the `mix` knob. */
const KNOB_PARAM_ID: Record<LogueEffectModule, Partial<Record<LogueKnob, string>>> = {
  modfx: { time: 'k_user_modfx_param_time', depth: 'k_user_modfx_param_depth' },
  delfx: {
    time: 'k_user_delfx_param_time',
    depth: 'k_user_delfx_param_depth',
    mix: 'k_user_delfx_param_shift_depth'
  },
  revfx: {
    time: 'k_user_revfx_param_time',
    depth: 'k_user_revfx_param_depth',
    mix: 'k_user_revfx_param_shift_depth'
  }
}

function generateManifestJson(module: LogueEffectModule, meta: LogueOldGenOscUnitMeta): string {
  // The spike's exact shape (no `params` key), which loaded on a real xd.
  const manifest = {
    header: {
      platform: 'minilogue-xd',
      module,
      api: '1.1-0',
      dev_id: meta.devId ?? 0,
      prg_id: meta.prgId ?? 0,
      version: '1.0-0',
      name: meta.name,
      num_param: 0
    }
  }
  return JSON.stringify(manifest, null, 4) + '\n'
}

const PROJECT_MK = `# Generated by logue-patcher's logue-codegen.
# NOT hand-written -- do not edit directly, re-export instead.

PROJECT = fx

UCSRC =

UCXXSRC = fx.cpp

UINCDIR =

UDEFS =

ULIB =

ULIBDIR =
`

function generateFxCpp(
  kind: UnitKind,
  pieces: ReturnType<typeof buildOscBodyPieces>,
  sinks: { l: ResolvedSource; r: ResolvedSource },
  audioInSuffix: string | undefined,
  sdram: SdramLayout
): string {
  const module = kind.module as LogueEffectModule
  const { header, prefix } = HEADER[module]
  const knobCases = kind.knobs
    .map(
      (knob) =>
        `    case ${KNOB_PARAM_ID[module][knob]}: ${KNOB_POSITION_MEMBER[knob]} = v; break;\n`
    )
    .join('')
  const readInput =
    audioInSuffix === undefined
      ? ''
      : `      const float y_${audioInSuffix}_l = in[2 * i];
      const float y_${audioInSuffix}_r = in[2 * i + 1];
      const float y_${audioInSuffix}_mono = 0.5f * (y_${audioInSuffix}_l + y_${audioInSuffix}_r);
`
  const sdramBlock =
    sdram.totalFloats === 0
      ? ''
      : `// NOLOAD: the loader doesn't clear it, init() does.
static float s_sdram[${sdram.totalFloats}] __sdram;

`
  const processHook =
    module === 'modfx'
      ? `void MODFX_PROCESS(const float *main_xn, float *main_yn, const float *sub_xn, float *sub_yn, uint32_t frames)
{
  s_fx.process(main_xn, main_yn, frames);
  // The prologue's second timbre; the xd has none, but never leave an output buffer unwritten.
  if (sub_xn && sub_yn)
    for (uint32_t i = 0; i < 2 * frames; ++i) sub_yn[i] = sub_xn[i];
}`
      : `void ${prefix}_PROCESS(float *xn, uint32_t frames) { s_fx.process(xn, xn, frames); }`

  return `// Generated by logue-patcher's logue-codegen.
// NOT hand-written -- do not edit directly, re-export instead.
#include "${header}"

${OSC_API_STAND_INS}
${sdramBlock}class Fx
{
public:
  void init()
  {
${sdramInits(sdram, 's_sdram')}    note_ = 60.f;
    noteFine_ = 0.f;
    tempo_ = 120.f;
${fixedKnobInits(kind)}${pieces.stateInits}${pieces.paramDefaultInits}${pieces.knobInits}  }

  // Delay lines and state cleared, knob positions kept.
  void reset()
  {
${sdramClears(sdram)}${pieces.stateInits}  }

  void setKnob(uint8_t index, float v)
  {
    switch (index)
    {
${knobCases}    default: break;
    }
  }

  // Every input sample of a frame is read before its outputs are written: delay and reverb
  // units process in place.
  void process(const float *in, float *out, uint32_t frames)
  {
${audioInSuffix === undefined ? '    (void)in;\n' : ''}    const float bpm = fx_get_bpmf();
    if (bpm > 0.f) tempo_ = bpm;
${pieces.blockStatements}    for (uint32_t i = 0; i < frames; ++i)
    {
${readInput}${pieces.computeStatements}      out[2 * i] = clip1m1f(${sourceVar(sinks.l)});
      out[2 * i + 1] = clip1m1f(${sourceVar(sinks.r)});
${pieces.advanceStatements}    }
  }

private:
${FX_FIXED_MEMBER_DECLS}${sdramPointerDecls(sdram)}${pieces.memberDecls}
${pieces.helperCode}};

static Fx s_fx;

void ${prefix}_INIT(uint32_t platform, uint32_t api)
{
  (void)platform;
  (void)api;
  s_fx.init();
}

${processHook}

void ${prefix}_SUSPEND(void) {}

// Cleared on resume as well, so a unit switched back in never replays a stale line.
void ${prefix}_RESUME(void) { s_fx.reset(); }

// Q31 (0..2^31-1, 10 bits of it real), not 0..1023 (the phase 0 spike, on a real xd).
void ${prefix}_PARAM(uint8_t index, int32_t value) { s_fx.setKnob(index, clip01f(q31_to_f32(value))); }
`
}

/** Korg's `tpl/_unit.c` for each module (the same file apart from the header, hook table type,
 *  magic and process signature), comments dropped like the oscillator's `UNIT_C`. */
function generateUnitC(module: LogueEffectModule): string {
  const { header, magic } = HEADER[module]
  const processDecl =
    module === 'modfx'
      ? `void _hook_process(const float *main_xn, float *main_yn,
                   const float *sub_xn, float *sub_yn,
                   uint32_t frames)
{
  (void)main_xn;
  (void)main_yn;
  (void)sub_xn;
  (void)sub_yn;
  (void)frames;
}`
      : `void _hook_process(float *xn, uint32_t frames)
{
  (void)xn;
  (void)frames;
}`
  return `#include "${header}"

extern uint8_t _bss_start;
extern uint8_t _bss_end;

extern void (*__init_array_start []) (void);
extern void (*__init_array_end []) (void);

typedef void (*__init_fptr)(void);

__attribute__((used, section(".hooks")))
static const user_${module}_hook_table_t s_hook_table = {
  .magic = {${magic}},
  .api = USER_API_VERSION,
  .platform = USER_TARGET_PLATFORM>>8,
  .reserved0 = {0},
  .func_entry = _entry,
  .func_process = _hook_process,
  .func_suspend = _hook_suspend,
  .func_resume = _hook_resume,
  .func_param = _hook_param,
  .reserved1 = {0}
};

__attribute__((used))
void _entry(uint32_t platform, uint32_t api)
{
  uint8_t * __restrict bss_p = (uint8_t *)&_bss_start;
  const uint8_t * const bss_e = (uint8_t *)&_bss_end;

  for (; bss_p != bss_e;)
    *(bss_p++) = 0;

  const size_t count = __init_array_end - __init_array_start;
  for (size_t i = 0; i<count; ++i) {
    __init_fptr init_p = (__init_fptr)__init_array_start[i];
    if (init_p != NULL)
      init_p();
  }

  _hook_init(platform, api);
}

__attribute__((weak))
void _hook_init(uint32_t platform, uint32_t api)
{
  (void)platform;
  (void)api;
}

__attribute__((weak))
${processDecl}

__attribute__((weak))
void _hook_suspend(void)
{
}

__attribute__((weak))
void _hook_resume(void)
{
}

__attribute__((weak))
void _hook_param(uint8_t index, int32_t value)
{
  (void)index;
  (void)value;
}
`
}

/** The effects' `rules.ld` is the oscillator's plus a NOLOAD `.sdram` section in SDRAM. */
const SDRAM_SECTION = `
  .sdram (NOLOAD) : ALIGN(4) SUBALIGN(4)
  {
    . = ALIGN(4);
    _usr_sdram_start = .;
    KEEP(*(.sdram*))
    . = ALIGN(4);
    _usr_sdram_end = .;
  } > SDRAM
`

function replaceOnce(text: string, from: string, to: string): string {
  if (!text.includes(from)) throw new Error(`Embedded scaffold has no "${from}".`)
  return text.replace(from, to)
}

const FX_RULES_LD = replaceOnce(RULES_LD, '  } > SRAM\n}\n', `  } > SRAM\n${SDRAM_SECTION}}\n`)

/** Korg's effect Makefiles differ from the oscillator's only in the MCU (the xd's main
 *  STM32F446, not the voice STM32F401), the linker script and the API symbols. */
function generateMakefile(module: LogueEffectModule): string {
  let text = replaceOnce(MAKEFILE, 'MCU_MODEL := STM32F401xC', 'MCU_MODEL := STM32F446xE')
  text = replaceOnce(
    text,
    'LDSCRIPT := $(LDDIR)/userosc.ld',
    `LDSCRIPT := $(LDDIR)/user${module}.ld`
  )
  return replaceOnce(
    text,
    '--just-symbols=$(LDDIR)/osc_api.syms',
    '--just-symbols=$(LDDIR)/main_api.syms'
  )
}

function generateModuleLd(kind: UnitKind): string {
  const origin =
    kind.module === 'modfx'
      ? { sram: '0x20017800', sdram: '0xC0400000' }
      : { sram: '0x20019000', sdram: '0xC0420000' }
  return `ENTRY(_entry)

MEMORY
{
  SRAM   (rx) : org = ${origin.sram}, len = ${kind.ramBytes / 1024}K
  SDRAM  (rw) : org = ${origin.sdram}, len = ${(kind.sdramBytes ?? 0) / 1024}K
}

INCLUDE rules.ld
`
}

/** The same for all three modules. */
const MAIN_API_SYMS = `k_fx_api_version = 0x0807b000;
k_fx_api_platform = 0x0807b004;
sqrtm2log_lut_f = 0x0807b100;
tanpi_lut_f = 0x0807b504;
log_lut_f = 0x0807b908;
bitres_lut_f = 0x0807bd0c;
wt_sine_lut_f = 0x0807bf10;
schetzen_lut_f = 0x0807c114;
cubicsat_lut_f = 0x0807c318;
pow2_lut_f = 0x0807c51c;
_fx_mcu_hash = 0x0807c920;
_fx_rand = 0x0807c92c;
_fx_white = 0x0807c964;
_fx_get_bpm = 0x0807ca88;
_fx_get_bpmf = 0x0807ca8c;
`

export function generateOldGenFxUnit(
  doc: PatchDocument,
  meta: LogueOldGenOscUnitMeta,
  subpatches: SubpatchDefinitions = new Map()
): LogueOldGenFxUnitSource {
  validateNoBreakingChars(meta.name, 'Unit name')
  const module = doc.settings.logueTarget?.module ?? 'osc'
  if (!isEffectModule(module)) {
    throw new UnsupportedLogueNodeError(
      'This is an oscillator patch -- it builds with generateOldGenOscUnit, not as an effect.'
    )
  }
  const kind = findUnitKind('minilogue-xd', module)!
  const { activeInstances, exposedParams, knobBindings, stereoSinks, audioInSuffix } = resolveUnit(
    doc,
    subpatches,
    'minilogue-xd',
    { maxParamCount: kind.maxParams }
  )
  const sdram = sdramLayout(activeInstances)
  const sdramBytes = sdram.totalFloats * 4
  if (sdramBytes > (kind.sdramBytes ?? 0)) {
    throw new UnsupportedLogueNodeError(
      `The delay lines need ${formatKb(sdramBytes)} of SDRAM, more than a minilogue xd ${MODULE_LABEL[kind.module].toLowerCase()} unit's ${formatKb(kind.sdramBytes ?? 0)} -- shorten a RANGE or use fewer.`
    )
  }
  const pieces = buildOscBodyPieces(activeInstances, exposedParams, 'out', undefined, knobBindings)
  return {
    module,
    manifestJson: generateManifestJson(module, meta),
    projectMk: PROJECT_MK,
    fxCpp: generateFxCpp(kind, pieces, stereoSinks!, audioInSuffix, sdram),
    makefile: generateMakefile(module),
    unitC: generateUnitC(module),
    rulesLd: FX_RULES_LD,
    moduleLd: generateModuleLd(kind),
    mainApiSyms: MAIN_API_SYMS
  }
}
