import type { PatchDocument } from '../../../src/shared/domain/patch'
import { UnsupportedLogueNodeError, type ResolvedSource } from '../oscInstances'
import type { SubpatchDefinitions } from '../subpatches'
import type { ExposedParamBinding } from '../oscParams'
import { resolveUnit } from '../resolveUnit'
import { buildOscBodyPieces, sdramLayout, sourceVar } from '../oscBody'
import {
  fixedKnobInits,
  formatKb,
  FX_FIXED_MEMBER_DECLS,
  OSC_API_STAND_INS,
  sdramClears,
  sdramInits,
  sdramPointerDecls,
  type SdramLayout
} from '../fxShared'
import { findUnitKind, isEffectModule, MODULE_LABEL, type UnitKind } from '../unitKinds'
import {
  generateHeaderC,
  generateParamStrValue,
  reserveFixedKnobSlots,
  UNIT_PARAM_NAME_MAX_LEN,
  validateMeta,
  type LogueOscUnitMeta
} from './generateOscUnit'

/**
 * A `PatchDocument` whose module is an effect (modfx/delfx/revfx) -> buildable NTS-1 mkII effect
 * unit source. The graph, params and knob bindings go through the same pipeline as an
 * oscillator (`resolveUnit`, `buildOscBodyPieces`); only the outer shape is an effect's:
 * stereo interleaved in/out (`unit_render(in, out, frames)`, 2 in / 2 out), the module's own
 * fixed knob rows (TIME/DPTH, plus MIX on delfx/revfx -- `unitKinds.ts`), no note.
 * Korg's templates: platform/nts-1_mkii/dummy-{modfx,delfx,revfx}.
 */

export interface LogueFxUnitSource {
  headerC: string
  /** The `Fx` DSP class (the templates call theirs modfx.h/delay.h/reverb.h). */
  fxH: string
  unitCc: string
}

function generateFxH(
  kind: UnitKind,
  pieces: ReturnType<typeof buildOscBodyPieces>,
  sinks: { l: ResolvedSource; r: ResolvedSource },
  audioInSuffix: string | undefined,
  sdram: SdramLayout
): string {
  const setParameterBody = !pieces.hasExposedParams
    ? '    (void)index;\n    (void)value;\n'
    : '    switch (index)\n    {\n' + pieces.setParameterCases + '    default: break;\n    }\n'
  const readInput =
    audioInSuffix === undefined
      ? ''
      : `      const float y_${audioInSuffix}_l = in[2 * i];
      const float y_${audioInSuffix}_r = in[2 * i + 1];
      const float y_${audioInSuffix}_mono = 0.5f * (y_${audioInSuffix}_l + y_${audioInSuffix}_r);
`

  return `#pragma once
// Generated by logue-patcher's logue-codegen.
// NOT hand-written -- do not edit directly, re-export instead.
#include "processor.h"
#include "unit_${kind.module}.h"
#include <cmath>

${OSC_API_STAND_INS}
class Fx : public Processor
{
public:
  // Floats of SDRAM unit_init allocates and hands to init().
  uint32_t getBufferSize() const override final { return ${sdram.totalFloats}u; }

  void setParameter(uint8_t index, int32_t value) override final
  {
${setParameterBody}  }

  void init(float *${sdram.totalFloats > 0 ? 'sdram' : ''}) override final
  {
${sdramInits(sdram, 'sdram')}    note_ = 60.f;
    noteFine_ = 0.f;
    tempo_ = 120.f;
${fixedKnobInits(kind)}${pieces.stateInits}${pieces.paramDefaultInits}${pieces.knobInits}  }

  // Korg's README: clear delay lines and state, keep param values (len_ and the dials stay).
  void reset() override final
  {
${sdramClears(sdram)}${pieces.stateInits}  }

  void setTempo(float bpm) override final { tempo_ = bpm; }

  // Every input sample is read before the frame's outputs are written: the SDK allows the
  // firmware to pass one buffer as both in and out.
  void process(const float *in, float *out, uint32_t frames) override final
  {
${audioInSuffix === undefined ? '    (void)in;\n' : ''}${pieces.blockStatements}    for (uint32_t i = 0; i < frames; ++i)
    {
${readInput}${pieces.computeStatements}      out[2 * i] = clip1m1f(${sourceVar(sinks.l)});
      out[2 * i + 1] = clip1m1f(${sourceVar(sinks.r)});
${pieces.advanceStatements}    }
  }

private:
${FX_FIXED_MEMBER_DECLS}${sdramPointerDecls(sdram)}${pieces.memberDecls}
${pieces.helperCode}};
`
}

function generateFxUnitCc(kind: UnitKind, exposedParams: Map<number, ExposedParamBinding>): string {
  return `// Generated by logue-patcher's logue-codegen.
// NOT hand-written -- do not edit directly, re-export instead.
#include "fx.h"
#include "unit_${kind.module}.h"
#include "utils/int_math.h"

static Fx s_fx_instance;
static int32_t cached_values[UNIT_MAX_PARAM_COUNT];

__unit_callback int8_t unit_init(const unit_runtime_desc_t *desc)
{
  if (!desc)
    return k_unit_err_undef;
  if (desc->target != unit_header.target)
    return k_unit_err_target;
  if (!UNIT_API_IS_COMPAT(desc->api))
    return k_unit_err_api_version;
  if (desc->samplerate != s_fx_instance.getSampleRate())
    return k_unit_err_samplerate;
  if (desc->input_channels != 2 || desc->output_channels != 2)
    return k_unit_err_geometry;

  float *sdram = nullptr;
  const uint32_t sdramFloats = s_fx_instance.getBufferSize();
  if (sdramFloats > 0)
  {
    if (!desc->hooks.sdram_alloc)
      return k_unit_err_memory;
    sdram = reinterpret_cast<float *>(desc->hooks.sdram_alloc(sdramFloats * sizeof(float)));
    if (!sdram)
      return k_unit_err_memory;
  }
  s_fx_instance.init(sdram);
  for (int id = 0; id < UNIT_MAX_PARAM_COUNT; ++id)
  {
    cached_values[id] = static_cast<int32_t>(unit_header.params[id].init);
  }
  return k_unit_err_none;
}

__unit_callback void unit_teardown() { s_fx_instance.teardown(); }
__unit_callback void unit_reset() { s_fx_instance.reset(); }
__unit_callback void unit_resume() { s_fx_instance.resume(); }
__unit_callback void unit_suspend() { s_fx_instance.suspend(); }

__unit_callback void unit_render(const float *in, float *out, uint32_t frames)
{
  s_fx_instance.process(in, out, frames);
}

__unit_callback void unit_set_param_value(uint8_t id, int32_t value)
{
  value = clipminmaxi32(unit_header.params[id].min, value, unit_header.params[id].max);
  cached_values[id] = value;
  s_fx_instance.setParameter(id, value);
}
__unit_callback int32_t unit_get_param_value(uint8_t id) { return cached_values[id]; }
${generateParamStrValue(exposedParams)}
// UQ16.16 BPM (Korg's README; its templates convert it the same way).
__unit_callback void unit_set_tempo(uint32_t tempo)
{
  s_fx_instance.setTempo((tempo >> 16) + (tempo & 0xFFFF) / static_cast<float>(0x10000));
}
__unit_callback void unit_tempo_4ppqn_tick(uint32_t) {}
`
}

export function generateFxUnit(
  doc: PatchDocument,
  meta: LogueOscUnitMeta,
  subpatches: SubpatchDefinitions = new Map()
): LogueFxUnitSource {
  validateMeta(meta)
  const module = doc.settings.logueTarget?.module ?? 'osc'
  if (!isEffectModule(module)) {
    throw new UnsupportedLogueNodeError(
      'This is an oscillator patch -- it builds with generateOscUnit, not as an effect.'
    )
  }
  const kind = findUnitKind('nts1mkii', module)!
  const { activeInstances, exposedParams, knobBindings, stereoSinks, audioInSuffix } = resolveUnit(
    doc,
    subpatches,
    'nts1mkii',
    {
      maxParamCount: kind.maxParams,
      maxLabelLength: UNIT_PARAM_NAME_MAX_LEN,
      reservedKnobSlots: new Map(kind.reservedSlots.map((slot) => [slot.index, slot.knob]))
    }
  )
  reserveFixedKnobSlots(exposedParams, knobBindings, kind)
  const sdram = sdramLayout(activeInstances)
  const sdramBytes = sdram.totalFloats * 4
  if (sdramBytes > (kind.sdramBytes ?? 0)) {
    throw new UnsupportedLogueNodeError(
      `The delay lines need ${formatKb(sdramBytes)} of SDRAM, more than a ${MODULE_LABEL[kind.module].toLowerCase()} unit's ${formatKb(kind.sdramBytes ?? 0)} -- shorten a RANGE or use fewer.`
    )
  }
  const pieces = buildOscBodyPieces(activeInstances, exposedParams, 'out', undefined, knobBindings)
  return {
    headerC: generateHeaderC(meta, exposedParams, kind),
    fxH: generateFxH(kind, pieces, stereoSinks!, audioInSuffix, sdram),
    unitCc: generateFxUnitCc(kind, exposedParams)
  }
}
