/**
 * Measures every primitive's minilogue xd CPU cost on the emulator and writes
 * `src/cpuCostTable.ts`. A primitive's cost is its WORST variant -- alone, with every inlet wired
 * (from white noise, a gate from a square LFO: `cpuVariants.ts`' `oscUnit`, their own cost taken
 * off), with each checkbox flipped, and for granular (two) and the multistage
 * envelope (one) their documented costliest settings -- minus a unit that's just one constant (the fixed per-unit overhead,
 * stored as the baseline). Each entry records a hash of the primitive's xd codegen snapshot, so
 * `logue-cpuCostTable.spec.ts` fails once the generated code changes without a re-measure.
 *
 * Usage (slow, ~1 build + emulator run per variant):
 *   EMU_PYTHON=<python with unicorn/capstone/pyelftools> npx tsx measureCpuCosts.ts [id ...]
 * With ids, only those entries are re-measured and the rest of the table is kept.
 */
import { existsSync, writeFileSync } from 'fs'
import { dirname, join } from 'path'
import { findLoguePrimitive, recognizedLoguePrimitiveIds } from '../src/primitives'
import { CPU_COST_TABLE, CPU_COST_BASELINE_CYCLES } from '../src/cpuCostTable'
import { measure as measureJob, type MeasureJob, type MeasureResult } from './measureXdCycles'
import { GATE_SOURCE, MOVING_SOURCE, oscUnit as unit, snapshotHash, variants } from './cpuVariants'
import { LOGUE_AUDIO_OUT_TYPE } from '../src/oscInstances'
import type { PatchDocument } from '../../src/shared/domain/patch'

const here = dirname(new URL(import.meta.url).pathname)

/** One reused staging folder, rather than a folder per variant in the user's SDK checkout. */
const measure = (job: MeasureJob): MeasureResult => measureJob({ ...job, dir: 'lp-measure-cpu' })

const only = process.argv.slice(2)
const baseline = measure({
  name: 'baseline-constant',
  doc: unit('logue/util/constant', [], 'none')
}).cyclesPerSample
console.log(`baseline ${baseline.toFixed(0)}`)
/** A source alone into the output, above the baseline: what `unit` adds only to measure. */
const sourceCost = (type: string): number => {
  const doc: PatchDocument = {
    nodes: [
      { kind: 'obj', type, name: 's', x: 0, y: 0, params: [] },
      { kind: 'obj', type: LOGUE_AUDIO_OUT_TYPE, name: 'out', x: 0, y: 0, params: [] }
    ],
    nets: [{ sources: [{ obj: 's', outlet: 'out' }], dests: [{ obj: 'out', inlet: 'in' }] }],
    settings: {},
    notes: ''
  }
  return measure({ name: `source-${type.replace(/\W/g, '_')}`, doc }).cyclesPerSample - baseline
}
const sources: Record<string, number> = {
  [MOVING_SOURCE]: sourceCost('logue/osc/noise'),
  [GATE_SOURCE]: sourceCost('logue/lfo/square-lfo')
}
console.log(`sources ${JSON.stringify(sources)}`)
const overhead = (doc: PatchDocument): number =>
  doc.nodes.reduce((sum, n) => sum + (sources[n.name ?? ''] ?? 0), 0)
type Entry = { variants: Record<string, number>; worst: number; snapshotHash: string }
const table: Record<string, Entry> = only.length ? { ...CPU_COST_TABLE } : {}
const failures: string[] = []
for (const id of recognizedLoguePrimitiveIds()) {
  if (only.length && !only.includes(id)) continue
  const p = findLoguePrimitive(id)!
  if (p.platforms && !p.platforms.includes('minilogue-xd')) continue
  if (p.modules && !p.modules.includes('osc')) continue
  const measured: Record<string, number> = {}
  for (const job of variants(id, unit, { still: true })) {
    try {
      measured[job.key] = Math.max(
        0,
        Math.round(measure(job).cyclesPerSample - baseline - overhead(job.doc))
      )
    } catch (err) {
      const stderr = (err as { stderr?: Buffer }).stderr?.toString() ?? String(err)
      const why = /undefined reference to `(\w+)'/.exec(stderr)?.[1]
      failures.push(`${job.name}: ${why ? `link error, undefined ${why}` : stderr.split('\n')[0]}`)
    }
  }
  if (Object.keys(measured).length === 0) continue
  table[id] = {
    variants: measured,
    worst: Math.max(...Object.values(measured)),
    snapshotHash: snapshotHash(id)
  }
  console.log(`${id.padEnd(32)} ${JSON.stringify(measured)}`)
}

const out = join(here, '..', 'src', 'cpuCostTable.ts')
const base = only.length && existsSync(out) ? CPU_COST_BASELINE_CYCLES : Math.round(baseline)
const body = Object.keys(table)
  .sort()
  .map(
    (id) =>
      `  '${id}': ${JSON.stringify(table[id])
        .replace(/"(\w+)":/g, '$1: ')
        .replace(/"/g, "'")}`
  )
  .join(',\n')
writeFileSync(
  out,
  `// GENERATED by scripts/measureCpuCosts.ts -- do not edit by hand; re-run it instead.
// Emulator estimates (scripts/emulateXdCycles.py) of minilogue xd cycles per voice-sample, on the
// emulator's own scale -- not hardware measurements. See estimateOscCpuCost.ts.

/** The fixed per-unit overhead: a unit that's just one util/constant. */
export const CPU_COST_BASELINE_CYCLES = ${base}

/**
 * Cycles per voice-sample above the baseline, per primitive (xd only), per measured variant:
 * \`base\` (audio inputs wired, control inputs free), \`control\` (every inlet wired; inputs from
 * a moving source, so per-sample paths are measured), \`control-still\` (control inputs from
 * per-block values instead: a knob, knob-only math), \`<CHECKBOX>\`
 * and \`<CHECKBOX>+control\` (that checkbox flipped); \`heavy-*\` are extra worst-case settings.
 * \`worst\` is the largest of them.
 */
export const CPU_COST_TABLE: Record<
  string,
  { variants: Record<string, number>; worst: number; snapshotHash: string }
> = {
${body}
}
`
)
console.log(`wrote ${out}`)
if (failures.length) {
  console.log(`\n${failures.length} variant(s) failed to build:\n  ${failures.join('\n  ')}`)
  process.exitCode = 1
}
